freedomofpress/securedrop-client

.circleci/config.yml
Porting the security checks we have in other SecureDrop repos (added by @emkll :tada:) over here
=> CI: Check for known vulnerabilities and perform static analysis

securedrop_client/app.py
=> setup signal handlers for SIGINT/TERM exit

securedrop_client/app.py
=> force terminal prompt on to newline in except hook

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #61. You have no idea how many *wrong* answers to this problem can be found via Google. In the end, this is the shortest, simplest and (most importantly) actually works. ;-)
=> Scroll to bottom.

securedrop_client/logic.py
This PR goes some way to automate the fix for #75. It's a very simple fix. ;-) I'm not sure we need tests for this (happy to add some if need be).
=> Sync the API after 5 minutes.

README.md
=> *TRIVIAL* updated README to explain how to install xvfb.

securedrop_client/gui/widgets.py
=> Don't hide two-factor code while typing

securedrop_client/__init__.py, setup.py
built new version of securedrop-client, upload to apt-test-qubes.freedom.press in progress
=> securedrop-client 0.0.3

Pipfile, Pipfile.lock
update to latest securedrop-sdk (0.0.4)
=> specify securedrop-sdk 0.0.4 in Pipfile

securedrop_client/app.py
=> skip single instance check on non-linux platforms

requirements.txt, securedrop_client/__init__.py, setup.py
for building new packages that are using the latest SDK
=> securedrop-client 0.0.5

securedrop_client/gui/widgets.py, tests/factory.py, tests/gui/test_widgets.py, tests/test_logic.py
=> Keep selected item after refresh

README.md
(Based on work done during 2018-11-12 documentation sprint
by @redshiftzero @conorsch @emkll @eloquence)
Resolves #72
=> Update README with additional context and current limitations

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Takes care to escape user-generated content before it's added to the UI.
Closes #160
=> Html escape messages

securedrop_client/__init__.py, setup.py
Bump securedrop-client to 0.0.6
=> securedrop-client 0.0.6

Makefile
to shake out issues due to state not being cleaned up between tests
=> Run tests in random order

tests/test_models.py
=> ensure data attr is present during tests

Pipfile, Pipfile.lock, securedrop_client/message_sync.py
=> Bump sdk to version 0.0.6

.circleci/config.yml, README.md
exactly what it says on the tin
=> updates how we call pipenv to ensure depenendencies aren't updated

.github/CODEOWNERS
=> added github code owners

securedrop_client/gui/widgets.py
No longer set an unknown `align` property in CSS
Run the client `./run.sh` and see "Unknown property align" message appear in stdout
=> remove unknown css property

securedrop_client/logic.py, tests/test_logic.py
=> remove incorrect use of keyword argument

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
This has been reviewed here: https://github.com/freedomofpress/securedrop-client/pull/330
/cc @redshiftzero
=> section layouts inside source widget layout

Makefile, securedrop_client/config.py, securedrop_client/crypto.py, securedrop_client/db.py, securedrop_client/utils.py
towards #25, should be a pretty quick review, now enforcing full annotation coverage for these three files in CI (to be incrementally increased)
=> [type checking] enforce 100% annotation in config, db, crypto

Pipfile, securedrop_client/storage.py, securedrop_client/utils.py, tests/test_storage.py
=> [type checking] utils.py, storage.py

securedrop_client/gui/widgets.py
Fixes #331 
See issue for STR and more info
=> Fixes sourcelist repaint issue

Makefile, securedrop_client/message_sync.py, securedrop_client/storage.py
towards #25: add some annotations and note that these file are now 100% type checked
=> type checking: add storage.py and message_sync.py to 100% type annotation

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #361
1. Follow STR in #361, confirm bug is fixed
2. Revert fix, make sure regression test fails
=> ensure conversation items are updated when content changes

.circleci/config.yml, README.md, update_version.sh
Changes in this repo for https://github.com/freedomofpress/securedrop-debian-packaging/issues/48
Closes #126
CI/dev only so read the diff, make sure all makes sense, and ensure CI build and test jobs pass
=> update pip mirror update policy, build deb package on each PR to verify policy is adhered to

securedrop_client/api_jobs/updatestar.py, securedrop_client/logic.py, tests/api_jobs/test_updatestar.py, tests/test_logic.py
Now we are using the same general queue for update_star calls.
Fixes #412 
`make test`
=> Moves update_star calls under queue

securedrop_client/db.py, securedrop_client/logic.py, securedrop_client/storage.py, tests/test_logic.py, tests/test_models.py, tests/test_storage.py
Resolves #451 
1. Log into the journalist interface
2. Add firstname and lastname in the name field
3. Log into the client
4. Using the sqlite cli, query the users table and see first and last name
=> update user on auth success

MANIFEST.in, README.md, changelog.md
Fixes #367
Adds a new changelog file and updates readme's release section to include adding changelog entries.
=> Issue 367 changelog

run.sh
Fixes #500.
0. Don't use Qubes
1. `./run.sh`
2. Client should appear as usual
=> fix developer environment on non-qubes

README.md
Just an update to our Environments section in the readme. 
Closes https://github.com/freedomofpress/securedrop-workstation/issues/301
=> update developer environments and recommendations

securedrop_client/gui/widgets.py, securedrop_client/resources/images/ellipsis.svg
Resolves https://github.com/freedomofpress/securedrop-client/issues/542
Date will be reformatted when this issue is addressed: https://github.com/freedomofpress/securedrop-client/issues/332
=> style conversation header

pytest.ini
Suppress a bunch of third-party deprecation warnings.
=> Ignore third party dep warnings

CODE_OF_CONDUCT.md
Ready for review. Docs-only change.
=> Remove Loic from CoC contacts (no longer involved)

dev-requirements.txt
Updates sdk dev-requirements.txt
1. run `pip install -r dev-requirements.txt` and see that sdk 0.0.12 gets installed
2. make sure you are able to log into the client
=> update sdk in dev-requirements

.github/pull_request_template.md
=> Add checklist items for AppArmor profile changes to PR template

securedrop_client/logic.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/745
Follow both STRs in https://github.com/freedomofpress/securedrop-client/issues/745#issuecomment-579958342 and confirm that what we expect to happen is what actually happens.
=> update conversation view on login

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #762.
Follow STR in #762
=> bugfix 762: ensure drafts are displayed when clicking between sources

securedrop_client/gui/widgets.py
Removes the shadow from the SIGN IN button
=> remove shadow on sign in button

README.md
=> Clarify use of staging env; state of supported features

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Have `ReplyBoxWidget` event handlers catch `ObjectDeletedError`.
Fixes #895.
Follow STR in #895. The app should not crash, sources should just be quietly replaced.
=> Stop ReplyBoxWidget event handlers crashing app when source deleted

securedrop_client/gui/widgets.py, securedrop_client/resources/images/star_hover.svg, securedrop_client/resources/images/star_off.svg, securedrop_client/resources/images/star_on.svg, tests/gui/test_widgets.py
Fixes #523.
@ninavizz checks and confirms (or else tells me what to fix).
=> Align star -> source name -> paperclip in source list item.

securedrop_client/gui/widgets.py
Fixes #973.
See screenie:
Use of Eyeball Mk.1. :eyes:
=> Fix horizontal scrollbar in source list.

.github/pull_request_template.md
Related to https://github.com/freedomofpress/securedrop-client/issues/665
=> PR template: AppArmor profile was moved to this repository

README.md
Update and move instructions on how to run the client into one place.
=> Developer docs

README.md
- Remove brew install 
Fixes #614 
=> Update OSX setup instructions

securedrop_client/logic.py, tests/test_logic.py
Fixes #1237 
Estimated testing time: 30 minutes, if you have a Qubes staging and SecureDrop server environment already provisioned.
1. In a Qubes environment, run the client version in this branch against a production server.
2. Attempt to log in using incorrect credentials. (This will quickly cause an `AuthError`.)
3. - [ ] Observe that the error message corresponds to "Auth error" in [the spreadsheet](https://docs.google.com/spreadsheets/d/1JTZ6XTSmtMmoiXEcgnxnHtQczAnjLuRdajbYQxpO2-U/edit#gid=1724968705)
4. Pause your `sd-whonix` VM and attempt to log in. (This will ultimately cause a `ServerConnectionError`.)
3. - [ ] Observe that the error message corresponds to "Connection error on login" in [the spreadsheet](https://docs.google.com/spreadsheets/d/1JTZ6XTSmtMmoiXEcgnxnHtQczAnjLuRdajbY …
=> Distinguish login error cases: connection, auth, everything else

README.md
=> Fix outdated instructions for development virtual environemnt

.github/ISSUE_TEMPLATE/release.md
Update the release template's test plan section to include information about server versions, release candidates, and release order.
=> Add more information around test plan to the release template

securedrop_client/gui/widgets.py
=> Hide seen-by checkmark for pending messages

files/usr.bin.securedrop-client, securedrop_client/logic.py
(Content identical to #1485 which seems to be stuck in GitHub hell.)
=> Apparmor fix redux

README.md
Replace python 3.7 references in README
=> Update README to show correct python version (3.9)

securedrop_client/database.py, securedrop_client/locale/messages.pot, securedrop_client/state/__init__.py, securedrop_client/state/domain.py, securedrop_client/state/state.py
The internationalization tooling update the year automatically and causes tests to fail.
This PR also updates existing licensing headers.
:fire: This CI failure prevents any other PR from being merged.
=> Fix i18n copyright year... happy new year!

README.md
Tweak readme to allow for using client from source in sd-app
=> Update qubes staging instructions

securedrop_client/gui/actions.py
Tiny change to reduce repetition of a constant string
=> Pull out string transcript.txt into constant

Makefile
Fixes <https://app.circleci.com/pipelines/github/freedomofpress/securedrop-client/3692/workflows/81e5706e-e1b1-44e7-9a3e-dcf6909a34b5/jobs/30216>.  See commit message for rationale.
=> chore: ignore urllib3 CVE-2023-43804

.github/pull_request_template.md
Just like the server repository has. Also switch the headers to level 2, so they're not so giant (this PR still has level 1 headers).
=> Add "Status" section to PR template

Makefile
=> Add "build-debs" make target

scripts/build-debs.sh
* Print success message to console after successful build
* Redisplay shasums at end of successful build - mostly for developer convenience 
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and- …
=> Show completion message after successful build

scripts/backport.py
* Ran `make fix`; both PRs were merged at the same time so the missing linting wasn't noticed.
=> Reformat scripts/backport.py with ruff

.github/dependabot.yml
Accidentally deleted this in 87c09f9f but should've kept it.
=> Restore dependabot group configuration

changelog.md
* Add a few missing entries
* Split out a "Provisioning" section since that was a major focus
* Remove specific development dependency updates and add a generic bullet for it, since there are way too many to list.
=> [0.11.0] Improve changelog

client/securedrop_client/export.py
=> [0.11.0] Backport printer preflight status fix (#2102)

CONTRIBUTING.md
=> Don't point people to the SecureDrop forum

client/securedrop_client/gui/base/dialog_button.css, client/securedrop_client/gui/base/dialogs.css, client/securedrop_client/gui/conversation/export/print_dialog.py, client/securedrop_client/gui/conversation/export/print_transcript_dialog.py
=> [0.12.0] Backport "Add more UI feedback to print, print transcript dialogs"

changelog.md
Ready for review, refs #2172 
- Update release changelog with #2174 
=> Update 0.13.0 changelog

.github/ISSUE_TEMPLATE/proposal.md
Adds engineering proposal issue template.
N/A
=> Add engineering proposal template, for large changes

client/securedrop_client/sdk/__init__.py
When we introduced retries with `Range` support, it was the first time we started mutating the request headers. At the time we didn't realize that headers are stored in a single dict that is used across requests, so the `Range` header would get reused in other requests, and then of course fail.
This affected any session in which a Range request was needed, so if no download ever failed, you'd never hit it.
To fix it, we now generate a fresh dictionary on each request. This will add a small amount of performance overhead, but it's not going to be noticeable and more importantly, makes it impossible to re-use the header dictionary across requests.
Add some more debug entries for future operations as well.
Fixes #2194.
=> Don't let Range header persist into other requests

client/securedrop_client/sdk/__init__.py
=> [0.13.2] Backport #2195: Don't let Range header persist into other requests

changelog.md, debian/changelog
Fixes #2203 
(cherry picked from commit 1d3cff5ebc26be9c72fefa99976fb20f9a5e37e2)
=> Backport 0.13.2 changelog

.github/workflows/cargo-vet.yml, .github/workflows/ci.yml, .github/workflows/security.yml, .github/workflows/test.yml, rust-toolchain.toml, scripts/Dockerfile
Doesn't appear to require any changes from us.
Fixes #2207.
=> Upgrade Rust toolchain to 1.81.0

client/securedrop_client/sdk/README.md
Closes #2147 by documenting the upstream/downstream assumptions of the SecureDrop SDK.
Visual review.
=> docs: document the SDK's upstream/downstream assumptions

client/run.sh
Most of the time we're developing the client, we are not testing the login screen, and just want to quickly log in. With a combination of xdotool and oathtool, we can script typing the correct values and login.
It's a bit fragile for two reasons. First, we're just blindly typing, so if some other window takes focus or switch, it'll be typed into that window. Second, we're kicking off a background process that sleeps, launching the window in the foreground, and then the background process will do the typing into the foreground.
Also this doesn't work on Wayland; there are some alternatives that use uinput but they have other restrictions/consequences.
It would've been easier to just have this be in the client Python code itself, but that would've meant it also gets shipped …
=> Automatically login to the dev client

client/securedrop_client/logic.py
Exceptions can be other types, so we should use a wider type and isinstance checks. This brings `on_message_download_failure` and `on_reply_download_failure` in line with `on_file_download_failure`.
This is mostly a bandage over the regression seen in #2274 and doesn't really substitute for the lack of more coordinated error handling.
Fixes #2274.
=> Don't assume all download failures are DownloadExceptions

client/securedrop_client/gui/source/delete/dialog.py, client/securedrop_client/locale/messages.pot, client/tests/functional/data/test_confirm_before_deleting_lots_of_sources.yml, client/tests/functional/test_delete_sources.py
=> [0.14.0] Backport "feat(`DeleteSourceDialog`): when lots of sources are selected for deletion, block the continue button for 5 seconds"

client/securedrop_client/gui/actions.py, client/securedrop_client/gui/source/delete/dialog.py, client/securedrop_client/gui/widgets.py, client/securedrop_client/locale/messages.pot, client/securedrop_client/logic.py, client/tests/gui/source/delete/test_dialog.py, client/tests/gui/test_actions.py, client/tests/gui/test_widgets.py, client/tests/integration/conftest.py
=> [0.14.0] Backport "Add warning when all sources are selected for deletion"

Cargo.lock, supply-chain/audits.toml, supply-chain/imports.lock
Addresses CVE-2024-12224 per Dependabot.
=> chore: update `url` to v2.5.4 for CVE-2024-12224

client/securedrop_client/locale/messages.pot
=> Update year in messages.pot

export/README.md
Follow-up to #2332, which enabled support for IPP (driverless printing).
Fixes #2087.
=> Update export README to reflect expanded printer support

.github/ISSUE_TEMPLATE/release.md
Template improvements following the latest client release (0.15.0)
=> 0.15.0 Release Template Improvements

app/src/main/database/index.test.ts, app/vitest.config.ts
- Unit tests -> Unit and component tests
- Note that integration tests may use testcontainers
Small follow-up from #2597
=> Minor tweak to test organization

app/src/renderer/utils.test.ts
Towards #2624
This implements tests for `app/src/renderer/utils.ts`.
```sh
pnpm test
```
=> Test utils.ts

app/src/main/index.ts, app/src/renderer/views/Inbox/Sidebar.tsx
This is a tiny PR that increases the window size, and also increases the width of the sidebar, so we can read more info in the sources list.
Now the minimum window size (as well as default window size) is 1200x900, and the sidebar width is increased to 384px.
=> Increase the sidebar width
