freedomofpress/securedrop-client

CODE_OF_CONDUCT.md
Adding CoC here (it's in the other SecureDrop-related repos already)
=> Add SecureDrop Community Code of Conduct

alembic/env.py, securedrop_client/models.py
For some reason in my environment running `alembic` lead to errors where `securedrop_client/models` was not able to be found. This looks like https://stackoverflow.com/questions/15648284/alembic-alembic-revision-says-import-error/15734665#15734665, and is solved here in a similar way (explicitly adding the path to the project root to `sys.path`. It's not clear why alembic works for others without this hack.
This PR also removes logic from `models.py` whereby the DB would be created automatically if it didn't already exist. A new DB is made (even if the .sqlite file doesn't exist) from running `alembic upgrade head` in a freshly-checked-out repo.
=> make alembic happy for josh

README.md
In this PR:
- Adds diagram for context and links back to discussion in workstation repo
- Adds steps describing how to start working on the client when interacting with the server (in a non-Qubes machine, will add docs later about testing in Qubes when https://github.com/freedomofpress/securedrop-sdk/issues/16 is done)
=> Dev docs: Explain how to get started with client development

Pipfile, Pipfile.lock, alembic/versions/fe7656c21eaa_add_remainder_of_database_models.py, securedrop_client/models.py, securedrop_client/storage.py, tests/test_models.py, tests/test_storage.py
This PR contains a solution for #5. However, it's a work in progress and given that I'm "new" to this project I'm keen to get feedback about style/approach.
This is stacked on PR #23.
Questions:
* I've included unit tests. What about integration tests. Thoughts / approaches please?
* I'm using the dependency injection pattern -- I'm assuming the app will make the api and database session objects these functions depend upon.
* The concept of a "reply" is not addressed, but I imagine will need to be in a similar fashion to sources and submissions. It would be trivial to add, so happy to do so as additional work on this PR.
=> Sync logic

Makefile, README.md, run.py, run.sh, securedrop_client/__main__.py, securedrop_client/app.py, securedrop_client/logic.py, securedrop_client/models.py, securedrop_client/utils.py, tests/conftest.py, tests/test_app.py, tests/test_logic.py, tests/test_utils.py
Fixes #37
Fixes #38
Fixes #39 
Adds an arg parser and makes everything injectable. There is no longer shared global state.
=> Added CLI args and set inject home directory

Pipfile.lock, securedrop_client/app.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/models.py, securedrop_client/storage.py, securedrop_client/utils.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_models.py, tests/test_storage.py, tests/test_utils.py
Very much a WiP PR for file download. 
* Behaviour for decryption needs to be decided for further progress in when handling downloaded files.
* We need to agree user feedback in the UI for status indication or for when things go wrong (timeouts / API errors etc...). I've raised a ticket for this #63.
=> File download UI / API plumbing

securedrop_client/logic.py, tests/test_logic.py
This is stacked on #77 and fixes #80 and #71.
Things to note:
* The event handler taking the completed outcome, is expected to guard / check that the result is correct.
* I've updated the existing event handlers (please check!)
* Happy to change anything!
:-)
=> Robustify threading

securedrop_client/logic.py, tests/test_logic.py
Fixes #83
Test plan:
1. Set up client in Qubes workstation, using the proxy
2. Submit a test file to the source interface of your test instance
3. Run client via `./run.sh` and login
4. Ensure you can download the test file (you download by double clicking on the file)
I was encountering a strange issue while testing this where I tried to download files, but they were not getting moved to the `sd-svs` VM (instead `qvm-move-to-vm` was just hanging). Please let me know if you spot that.
=> [Qubes] fix file download moving

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Adds a refresh button next to the logout button, which manually triggers a call to `sync_api`. 
Resolves #75 (remainder)
=> Adds a refresh button to client UI

securedrop_client/app.py, tests/test_app.py
Resolves #44
Uses Unix domain sockets to see if the client is already running. If it's already running, the new process displays an error dialog and exits upon user acknowledgement.
=> Added concurrent application launch prevention

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py
This is part of the messages audit in #53. Specifically, here we
are:
- consistently using "sign in" / "sign out"
- consistently using "refresh" instead of "sync"
- consistently using sentence case
- avoiding ambiguity between server/workstation errors by being
explicit
=> Minor tweaks to UI messages

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #98.
Simply overrides a different default event handler (`mouseReleaseEvent` - http://doc.qt.io/qt-5/qwidget.html#mouseReleaseEvent) to catch a completed single click.
=> FileWidget responds to completed *single* clicks.

securedrop_client/__init__.py, setup.py
made a debian package based on the latest code, available here: https://apt-test-qubes.freedom.press/pool/main/s/securedrop-client/
=> securedrop-client 0.0.2

securedrop_client/models.py
Fixes #47
`Boolean`s have `name` added because the `sqlite` driver creates a check constraint for them that must be explicitly named.
=> added sqlalchemy naming conventions

securedrop_client/gui/widgets.py
Resolves #120
I've taken the liberty to remove the TODO since it's better covered in issues.
=> Remove placeholder text from source list for now

MANIFEST.in, files/securedrop-client.desktop, securedrop_client/__init__.py, setup.py
Towards https://github.com/freedomofpress/securedrop-workstation/issues/198
Build logic will also need to be updated to copy this file when the .deb is installed.
Test plan:
=> Add .desktop file and bump version to 0.0.4

Makefile, securedrop_client/app.py, securedrop_client/crypto.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/message_sync.py, securedrop_client/models.py, setup.cfg, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_app.py, tests/test_crypto.py, tests/test_logic.py, tests/test_message_sync.py, tests/test_storage.py
- Uses the standard SD `Makefile`
- Splits `check` into `lint` and `test` (because it's nice to run one but not the other)
- Moves to `flake8` for linting
- Fixes lint errors
- **HIGHLY CONTROVERSIALLY** sets the max line length to 100
- I am very prepared to squabble over why this change is A Good Thing™
- Only runs tests with `xvfb-run` if it's present
fixes #139 
fixes #111
fixes #57
=> Standardize dev env

securedrop_client/logic.py, tests/test_app.py, tests/test_logic.py
Fix defect #146 discovered by @zenmonkeykstop
Also adds a conditional test skip on macOS as followup from #148 
Test plan:
1. Submit a test document via the source interface
2. Sign in and sync
3. Sign out
4. Click the download
5. The application should not crash :wink: and you should see:
=> Fix crash in offline mode

securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py
Quick POC of doing this without any significant changes to the code. It'd be good to get comments on some thoughts I had about how the API call is handled in the model and view (below)
The current API code makes this tricky to do particularly well:
- auto refresh and manual refresh could be simultaneously called
- the callbacks will be fired whether it's auto or manual
It'd be nice to create a `Promise` object or similar to return from API calls, which the caller could connect to, e.g:
```python
promise = self.controller.sync_api()
self.refresh.setEnabled(False)
promise.on_settled(lambda: self.refresh.setEnabled(True))
```
=> Disable refresh button while API call is in progress

alembic/versions/cd0fbb73bf8e_capture_document_count.py, securedrop_client/gui/widgets.py, securedrop_client/models.py, securedrop_client/storage.py, tests/factory.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_models.py
Added a factory module to DRY up creating test objects. Stops a new attribute etc requiring a lot of updating. Also makes it clearer which attributes are important for a test.
I named the field `document_count` to keep it consistent with `interaction_count`. Might be a worse option than matching the server's field name `number_of_documents` however. 🤷‍♂️
=> Only show attachment icon when document count is > 0

securedrop_client/crypto.py
Just run the standard tests.
```
make check
```
=> Fixes #132 removes the temporary file

securedrop_client/data.py, securedrop_client/logic.py, securedrop_client/storage.py, tests/test_data.py, tests/test_logic.py, tests/test_storage.py
Closes #153
1. Start the dev container.
2. Log into the client.
3. Make sure that one downloads a file from a source. 
4. This files should now be in the data folder (inside the SecureDrop homedir).
5. Log into the journalist interface and delete the submission you downloaded (NOT a reply, we will run through that separately).
6. Back in the client, click Refresh.
7. Now look in the data directory: the file associated with the submission you deleted should be gone.
1. Now using the journalist interface, submit a reply to a source.
2. Wait until that reply downloads and decrypts.
3. Verify the file is there in the data folder locally.
4. Now delete the reply from the journalist interface.
5. Back in the client, click Refresh.
6. Now look in the data directory: the file associated with the …
=> delete submissions, replies on disk when source, submission, or reply is deleted

securedrop_client/logic.py, tests/test_logic.py
Closes #107
1. Login to client
2. Click on source in sidebar
3. The messages and replies are downloading... wait six seconds
4. The messages and replies should appear decrypted in the conversation view. The user should not have to sync again or take any other manual action
=> Refresh conversation view

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
This prevents sending invalid passwords/usernames to the server (these same checks done client-side in this PR you can see in models.py in the SecureDrop server repo)
Closes #133
=> improve login validation input

securedrop_client/logic.py, tests/test_logic.py
Closes #174 
One should follow the STR in that issue to test this fix
=> Fix defect #174: application crash on source collection deletion

securedrop_client/logic.py, securedrop_client/message_sync.py, tests/test_logic.py
=> Fix security bug regarding long lived threads

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/resources/images/cross.svg, securedrop_client/resources/images/ellipsis.svg, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py
* **Description:** Adding a functionality to delete a Source when you are a Journalist.
* **Status:** In progress
* **Fixing:** #18 
* **How to test?:** Pending. Will add as soon as I will complete the work.
* **Video demonstration of feature:**
~~[Outdated YouTube link](https://youtu.be/Jsjg3lPvl4U)~~
[Youtube link](https://youtu.be/RhZZwFE4K6I)
=> Add functionality for deleting sources

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
**Description:** In conversation, messages with single quote **'** or double quote **"** quote
wasn't rendered correct. It was difficult for journalist to read those
messages. This commit is fixing that problem of parsing quote based
messages and improves readability of the text in the conversation.
**Resolves**: #175
[Video demonstration](https://youtu.be/8nXX1R3HnfY) of this feature.
=> Fix for displaying quote based messages in conversation

run.sh
Fix #193
(Test by running `./run.sh --sdc-home path-to-my-homedir` twice and verifying the app does not crash)
=> bugfix: resolve application crash due to existing gpg homedir

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
This will display accurate count of messages and files at dialog box
giving warning at the time of deleting source.
Resolves: #194
=> Fix for wrong files and messages number at delete source dialog

Makefile, run.sh, securedrop_client/app.py, securedrop_client/db.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/message_sync.py, securedrop_client/storage.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_app.py, tests/test_logic.py, tests/test_message_sync.py
Fixes #185 
This fixes the problem of the UI flickering every time there is a API sync or message-download-decrypt sync. This is done by caching the conversation views and swapping between them instead of dropping and recreating them.
(Also I updated some of the code and tests to try to logically separate code blocks to avoid walls of text because I found it hard to read some times)
=> Prevent UI flicker on conversation switch / update

README.md, securedrop_client/db.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/message_sync.py, securedrop_client/storage.py, tests/gui/test_widgets.py, tests/test_logic.py
Fixes #16
This PR does implements the following behavior:
- Journalist can type and sent replies
- Replies are immediately sent to the API with no queuing / ordering
- Replies that succeed are stored in the DB
- Replies that fail are turned red in the UI
- this is not the final behavior, but is "good enough" for now and can use used as the base for more complex behavior
- The original ticket discussed using the `reply.filename` to order messages in the UI, but for now we are naively assuming order sent == order received (i.e., not implementing that behavior). We have additional tickets that will change the underlying DB and this ticket was annoying enough to close as is that I think it's preferable to get this base behavior in now and the add the server-defined ordering in a follow up.
- …
=> Send replies from a journalist to a source

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/226 and `[Conversation Reordering]` issue noted in https://github.com/freedomofpress/securedrop-client/pull/240
**STR**
1. start client
2. refresh
3. resize window (should no longer see bubble layering issue)
4. send message from source
5. refresh, resize (should see no bubble layering issues)
=> Clear old items in conversation view on refresh

Makefile
Fixes https://github.com/freedomofpress/securedrop-client/issues/245
=> Send xvfb-run command check output to /dev/null

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Work in progress (tests missing)
Fixes #144 is a way that is simple enough. Structural changes are still needed for #187 but for the time being this solves the issue.
renamed `move_to_bottom` function in `widgets.py` to `update_conversation_position` as it does not always go to the bottom. Added checks to see what parts of the conversation are currently visible. The way it works currently is it detects whether or not it is within a view-port distance of the last message (since it is hard to detect exactly the length of the last message)
Open conversation with source. Type enough text such that it covers more than the window. Pull to the top and receive a msg from the source. It should stay in the same place. move to the bottom and do the same and see that it scrolls with the new content. …
=> Improve scrolling logic in conversation view

run.sh
Fixes https://github.com/freedomofpress/securedrop-client/issues/251
=> Fix gpg issue with importing public key

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py
Fixes #243
Testing:
- Start client
- Skip login
- See warning instead of reply box
- Sign in
- See reply box
- Sign out
- See warning again
Also:
- Check that the type annotations I added are correct
=> Prevent user from sending replies when client is not authenticated

README.md, alembic/versions/2f363b3d680e_init.py, securedrop_client/db.py, securedrop_client/logic.py, securedrop_client/message_sync.py, securedrop_client/storage.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_message_sync.py, tests/test_models.py, tests/test_storage.py
Update:
Fixes #229
--------------------
Toward #229
I considered using an [abstract concrete base](https://docs.sqlalchemy.org/en/latest/orm/inheritance.html#abstract-concrete-classes) pattern as described in the SqlAlchemy docs, but didn't actually see much benefit in it at first since we mainly use these as separate entities and do a lot of the manipulations like ordering in the code anyway. Adding back the `Submission` class as an `AbstractConcreteBase` is trivial should we want to do that.
This is a draft PR that establishes the models that we'd use for the rest of the ticket. Since the DB tends to be a subject that warrants debate and is something a lot of us have opinions on, I opened this as a draft for discussion on just this aspect before I put the rest of the …
=> Split submissions table into files/messages

securedrop_client/app.py, securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/248 where the client crashes when a user clicks on a source from the sources list.
When debugging the client I could see that crash happened when adding the widget to the `view_layout`:
```
(Pdb) w
/usr/lib/python3.5/runpy.py(193)_run_module_as_main()
-> "__main__", mod_spec)
/usr/lib/python3.5/runpy.py(85)_run_code()
-> exec(code, run_globals)
/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/__main__.py(3)<module>()
-> run()
/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/app.py(187)run()
-> start_app(args, qt_args)
/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/app.py(180)start_app()
-> sys.exit(app.exec_()) …
```
=> segfault when clicking on Source

securedrop_client/gui/widgets.py, tests/factory.py, tests/gui/test_widgets.py
Fixes #265
This bug was mainly an error where an attribute was no renamed in the code. A small amount of logic was fixed to make this more robust. Tests were updated and somewhat de-mocked to ensure `AttributeError`s in the code appear in the test runs.
=> Fix deletion of source from the UI

securedrop_client/db.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/message_sync.py, securedrop_client/storage.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_message_sync.py, tests/test_storage.py
Stores decrypted messages in the database. Pretty simple.
fixes #217
toward #263
=> Store decrypted messages / replies in the DB

securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_logic.py
The traceback I reported in #266 was resolved with #231, but this addresses my comment [here](https://github.com/freedomofpress/securedrop-client/issues/266#issuecomment-476775068) on that ticket about the FileWidget not updating after download. 
Confirm the following to test this PR and confirm that #266 is resolved:
0. Submit a file as a source
1. Sign into the client, then click once to download a document
2. Confirm that the file widget updates to "Open" without needing to refresh
3. Confirm the application does not crash
Closes #266
=> update FileWidget via signal emitted when file downloads + decrypts

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #289
/cc @heartsucker or @rmol
=> undo changes to adding a reply to the gui

securedrop_client/crypto.py, securedrop_client/message_sync.py, securedrop_client/storage.py, tests/factory.py, tests/test_crypto.py, tests/test_storage.py
Fix #276
Previously:
* Files that failed to decrypt would not get re-downloaded
* Once that was addressed, once decryption failed (which you can simulate using the STR in #276 after 287752c05bc2825811ae40db2c8c24f397c65ddc), every 5 seconds, the client would re-download the same message or reply and attempt to decrypt, meaning a lot of repeated/pointless network activity
Now:
* Files that fail to decrypt will get decrypted 5 seconds after a key becomes available
* If decryption is failing, the file will only be downloaded once and then saved on disk. The message sync / reply sync threads will resume and decrypt 
Test with STR in #276 and ensure that the `download` endpoints are only hit once per file
=> Handle messages and files that fail to decrypt

securedrop_client/app.py, securedrop_client/gui/widgets.py
* Fixes https://github.com/freedomofpress/securedrop-client/issues/304
This one line fixes the issue: https://github.com/freedomofpress/securedrop-client/pull/305/commits/6d7e1448c0116ddbabf9fba020623552afdb20bb
* Does not fully resolve https://github.com/freedomofpress/securedrop-client/issues/273 because I don't fully understand iwhether or not this is related to https://github.com/freedomofpress/securedrop-client/issues/304. See Comments below.
* We now do not add CSS to the `ConversationView` widget. There is a comment in the class docstring that points to https://github.com/freedomofpress/securedrop-client/issues/304 saying not to add CSS here.
* I uncommented a line of code that loads `sdclient.css` and its corresponding comment about …
=> CSS bug in ConversationView

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/storage.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_storage.py
Fixes #302 
Fixes #297 
Fixes #195 
* `on_source_changed` now checks if the current source exists before trying to set the conversation
* `on_source_changed` clears the conversation from the conversation view if the source does not exist
* Removed calls to `self.controller.session.refresh` since it isn't necessary (might have been a fix for some bug that no longer exists)
* We now show the number of replies being deleted in the popup that checks if the user wants to delete a source. Before we showed only counts for messages and files.
1. Log into the client
2. Delete the first source by selecting 'x' next to the source in the source list and see conversation view cleared (app no longer crashes) after source and conversation are deleted
3. Delete the second source using the source menu in …
=> no longer try to show conversation for deleted src

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py
Resolves #286 
Note: This does not include any styling
* When you start the client, instead of showing both the main window and login dialog, we now only show the login dialog
* There's now an option to click on "offline mode" which shows the main window without allowing behavior that requires authentication
* When you log in via the main window 'SIGN IN' button, the login dialog still pops up without hiding the main window
* Exiting the login dialog when it's the only window that shows closes the application
1. Start the client and see login dialog appears without main window
2. Click "offline mode" and main window appears in offline mode
3. Log in using the 'SIGN IN' button and see login dialog popup. Here you can click offline mode again or login.
4. Start the client again and log in …
=> LoginDialog going solo

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #318 
Override default behavior for Esc key pressed event, see https://doc.qt.io/qt-5/qdialog.html#escape-key:
> If the user presses the Esc key in a dialog, QDialog::reject() will be called. This will cause the window to close: The close event cannot be ignored.
Looks like `QDialog::reject` actually hides the modal dialog rather than closing it. Either way, we don't want to hide or close the dialog, especially now that we show a "standalone" modal dialog when the application starts.
Bug fix, see #318
=> ignore Esc key pressed event

securedrop_client/app.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_app.py, tests/test_logic.py
Fixes #70 
We have had the problem of overloaded terms making discussion of the app confusing. Right now client means:
- The entire app
- The SDK's API client
- The "controller"
This reduces use of the client down to two distinct things.
=> renamed logic.Client to logic.Controller

securedrop_client/gui/widgets.py
I noticed when testing the client on macOS that the dropdown arrow didn't scale nicely. I thought this was fixed since it looked fine to me on debian. It would be helpful to add future scaling code that can resize without changing aspect ratio of icon images and SVGs. I've seen some useful QImage methods for this, but I don't think we want to have to convert our SvgWidgets or Icons to QImages. I might be wrong, I need more time to research this. For now, I just updated the dropdown arrow so that it can look sharp like the others.
=> fix dropdown arrow

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/resources/__init__.py, tests/gui/test_init.py, tests/gui/test_widgets.py
Move logic for toggling stars from `SourceWidget` to `StarToggleButton`. This change should not be noticeable when running the client. The behavior is the same. However, this change made it very easy to add a star toggle to the conversation view and for stars to update state when either button is pressed.
1. Toggle star when in offline mode.
2. Toggle star when authenticated.
Make sure star toggling behavior hasn't changed.
=> Create class for starring

securedrop_client/logic.py, tests/test_logic.py
Changes the check on the completion handler to correctly check for the presence of an `Exception`. This supersedes https://github.com/freedomofpress/securedrop-sdk/pull/74
=> Fixes the login with latest SDK python API changes

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Resolves #280
This restructures `SourceWidget` to show timestamp, star, delete, and attachment icons in preparation for:
* Delete icon overlay Attachment icon: #300
* Add message preview: #135
* And to look similar to: 
We have a separate issue for styling and polishing, which will fix off-by-one pixels issues, etc.
* There is now a `timestamp` row. The change here is a proposal for the team, leaning on @ninavizz and @eloquence for feedback. I noticed when testing the changes that our "x days ago" humanized timestamp is cut off by the message preview. I suggest that, for now, we lower the timestamp so that we won't have this problem, and create a new Issue if we want a different solution. I could also place the timestamp somewhere else in this PR if we find another location that makes …
=> Restructure the layout of SourceWidget

Pipfile, Pipfile.lock, securedrop_client/logic.py, tests/test_logic.py
The SDK update means logic.APIController.api.token is now a str, not a dict, and the journalist UUID is stored separately in logic.APIController.token.token_journalist_uuid.
Tests/mocks updated accordingly.
Fixes #292.
=> Update securedrop-sdk to 0.0.8

securedrop_client/app.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_app.py
Just a quick refactor where we were passing `sdc_home` to `Window` and then not doing anything with it. We also don't need to pass the `is_authenticated` to `show_conversation_for` because we already have a reference to the `Controller`.
Client should behave exactly the same as before. Automated and [manual tests](https://github.com/freedomofpress/securedrop-client/wiki/Test-plan) should pass.
=> remove unused sdc_home

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_storage.py
Small change to make it obvious when we have a `Reply` database object and when we don't. 
Just as before, both adding a reply from reply box and adding a reply from a source database object results in a new ReplyWidget added to the layout. Now we just have separate methods for adding them.
Client should behave exactly the same as before. Automated and [manual tests](https://github.com/freedomofpress/securedrop-client/wiki/Test-plan) should pass.
=> more obvious two-state reply

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_storage.py
This PR moves the management of `SourceConversationWrapper` from `Window` and `Controller` into `MainView`. Just like the `MainView` has a `SourceList`, it now also has a `SourceConversationWrapper`.
This means we no longer need a `conversations` dictionary for `Controller` and `Window` to manage. Apparently there was a UI "flicker" before, but this change does not reproduce the flicker.
To using signals and slots, of course!  `MainView` will connect the two so that `SourceConversationWrapper` can respond to a source selection change, and `SourceList` can respond to new activity shown in the `SourceConversationWrapper` (for previews). 
There will be a follow-up PR for no longer recreating the `SourceConversationWrapper` in `on_source_changed` and instead creating it once in …
=> remove unnecessary conversations cache

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_storage.py
Here we remove reply box logic out of `SourceConversationWrapper` into `ReplyBoxWidget`. `ReplyBoxWidget` now emits a `reply_sent` signal to tell the `ConversationView` to update. `SourceConversationWrapper` is only responsible for wiring `ReplyBoxWidget` and `ConversationView` together.
Client should behave exactly the same as before. Automated and [manual tests](https://github.com/freedomofpress/securedrop-client/wiki/Test-plan) should pass.
=> replybox emits reply_sent signal

securedrop_client/gui/widgets.py
Since we no longer display the whole client window on launch, the
"shown here" message is now inaccurate. This text will likely go away
in the final rev; this is just to keep things in an internally
consistent state until then.
=> Tweak login text for accuracy

Makefile, Pipfile, Pipfile.lock, securedrop_client/logic.py, tests/test_logic.py
Fixes #323. Fixes #324. Fixes #325. Toward #326. Fixes #327.
This is the first pass that shows that we can easily remove the timeouts from the client. This is only toward #326 and doesn't fix it since we should add logic to extend the timeout to be even longer for very large files.
~Blocked by https://github.com/freedomofpress/securedrop-sdk/pull/80 (PR that adds timeouts to the SDK itself).~
To test this, login. Then, go into SD core, go into `journalist_app/api.py`, and in `setup_g` add `import time; time.sleep(30)`. Save the file. Flask will refresh. Now all requests will be delayed by 30 seconds, and the SDK timeout is 20. This will cause all requests to raise a timeout error. Check the logs for the presence of this error.
=> Remove timeouts for API calls from the client and use SDK for timeouts

securedrop_client/crypto.py, securedrop_client/logic.py, tests/test_crypto.py, tests/test_logic.py
Fixes #363 
The reviewer of this PR should test this on both Qubes and non-Qubes. If you need/want additional clarity on how to test please let me know and I will happily elaborate on any unclear parts of the test plans below.
1. Make sure you’re running the server container on latest `develop` 
2. Start the client on this branch, and ensure you can successfully send a reply to a source (warning: due to #365, you should verify either using the client logs which will log a line when a reply is successfully sent OR the dev server output on the server side by watching for a 201 response from the `POST /api/v1/sources/<source uuid>/replies` endpoint)
1. Make sure you have applied the RPC policy change merged in https://github.com/freedomofpress/securedrop-workstation/pull/254. If you like you …
=> fix gpg key import / replies / encrypt to source on qubes

Makefile, create_dev_data.py, securedrop_client/app.py, securedrop_client/crypto.py, securedrop_client/db.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/message_sync.py, securedrop_client/queue.py, securedrop_client/storage.py, tests/conftest.py, tests/factory.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_alembic.py, tests/test_app.py, tests/test_crypto.py, tests/test_logic.py, tests/test_message_sync.py, tests/test_models.py, tests/test_queue.py, tests/test_storage.py
Fixes #224
Adds the initial implementation of the `ApiJobQueue`. This diverged a bit from the original design spec, but still fundamentally accomplishes the task of strict ordering of replies. This PR only contains `ApiJob`s for downloading files from the API, but using the patterns here, the rest should be relatively easy to implement.
An `ApiJob` only needs to implement one method called `call_api` that should do everything needed to process an API including writing it to the local DB. This method might be renamed `run_job` for clarity.
On success/failure, respective signals are emitted. These are connected to callbacks on the `Controller` which then takes action directly and possible relays the signal to other `QObjects`. In the case of a `DownloadSubmissionJob`, we don't want to …
=> Implementation of the API queue

securedrop_client/logic.py
Fixes #issue https://github.com/freedomofpress/securedrop-client/issues/386 by adding back "synced" signal.
Run through STR in issue and see the actual behavior match expected behavior:
Refresh icon returns back to static image after sync, indicating that the gui is properly being notified of a sync finishing.
=> fix sync bug

Makefile, securedrop_client/api_jobs/base.py, securedrop_client/api_jobs/downloads.py, securedrop_client/queue.py, tests/api_jobs/test_base.py, tests/api_jobs/test_downloads.py, tests/factory.py, tests/test_queue.py
Towards #390
We are going to be adding _quite_ a few more API jobs (even without
considering any additional functionality that might be added to the
application). Let's break the logic up a bit (organizing the api jobs and removing them from `queue.py`) so that it's easier to move around the codebase.
I'm putting this in a separate commit because we're starting to work on #389 and #390 in parallel so let's merge this first since the diff is large
=> app: pure refactor/reorganize to separate *Queue and APIJob objects

Makefile, securedrop_client/api_jobs/base.py, securedrop_client/api_jobs/uploads.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/api_jobs/test_uploads.py, tests/test_logic.py
=> add SendReplyJob and use it for sending replies to the general queue

securedrop_client/api_jobs/base.py, securedrop_client/logic.py, securedrop_client/queue.py, tests/test_logic.py, tests/test_queue.py
Fixes #397
Fixes #380
In a single run of the client:
1. Log in
2. Ensure you can download a file (must be a file not a message)
3. Log out 
4. Ensure that you cannot download a file (there isn't good user messaging in the UI - see [my comment here](https://github.com/freedomofpress/securedrop-client/issues/379#issuecomment-499218609))
5. Log back in
6. Ensure you _can_ download the file now
=> deauth queue when user logs out (#397), restart threads if they fail (#380)

dev-requirements.txt, requirements.in, requirements.txt, securedrop_client/logic.py, tests/test_logic.py
Towards #397 , Fixes #223 .
- Install new requirements, start client on this branch, and log in as $USER
- On the bar on the left, click on $USER and "SIGN OUT"
```
172.17.0.1 - - [12/Jun/2019 20:23:24] "POST /api/v1/logout HTTP/1.1" 200 -
```
```
2019-06-12 16:23:24,904 - urllib3.connectionpool:393(_make_request) DEBUG    : http://localhost:8081 "POST /api/v1/logout HTTP/1.1" 200 48
2019-06-12 16:23:24,907 - securedrop_client.logic:265(completed_api_call)     INFO: Completed API call. Cleaning up and running callback.
2019-06-12 16:23:24,908 - securedrop_client.logic:628(on_logout_success)     INFO: Client logout successful
```
- Now test the negative scenario, where logout fails: log into the client, and shut down/disconnect the server
```
2019-06-12 16:24:06,148 - …
```
=> Call logout endpoint when signing out in the client

securedrop_client/api_jobs/downloads.py, securedrop_client/message_sync.py, securedrop_client/storage.py, tests/test_storage.py
This is part of breaking down a large PR https://github.com/freedomofpress/securedrop-client/pull/409
This and following smaller refactors are a way to help us avoid bugs around file management when we download and decrypt, which is tricky.
This refactor generalizes the way we mark objects as downloaded in a function called `mark_as_downloaded`
and updates `set_object_decryption_status_with_content` to take a type and uuid instead of a database object.
This PR is the easiest of the bunch because it does not modify how we decrypt or download, just how we mark things as downloaded and decrypted.
1. Send messages and files as a source
2. Refresh on the client to see messages downloaded and decrytped. Click on files to trigger a download and decrypt. When you see "Open" next to the filename …
=> make generic mark_as_download db function

securedrop_client/api_jobs/downloads.py, securedrop_client/crypto.py, tests/api_jobs/test_downloads.py, tests/test_crypto.py
This is part of breaking down a large PR https://github.com/freedomofpress/securedrop-client/pull/409
This and following smaller refactors are a way to help us avoid bugs around file management when we download and decrypt, which is tricky.
This refactor generalizes the way we decrypt and will need to be tested on Qubes. The major changes are:
* Now if an object is already decrypted, we do not decrypt again.  The logic in `call_api` goes: if decrypted return uuid, if downloaded, just decrypt, return uuid, otherwise both download and decrypt.
* Instead of building the target file for the decrypted text inside the `decrypt_submission_or_reply` method, we now just pass it the target file. This also fixes a minor issue where `FileDownloadJob` was passing db object filenames that were unused. …
=> Generalize decrypt

alembic/versions/fecf1191b6f0_remove_decryption_vs_content_contraint.py, securedrop_client/api_jobs/downloads.py, securedrop_client/db.py, securedrop_client/logic.py, securedrop_client/message_sync.py, securedrop_client/storage.py, tests/api_jobs/test_downloads.py, tests/test_logic.py, tests/test_queue.py, tests/test_storage.py
Closes #406
This is part of breaking down a large PR https://github.com/freedomofpress/securedrop-client/pull/409
This and following smaller refactors are a way to help us avoid bugs around file management when we download and decrypt, which is tricky.
* Moved `call_api`, `_download`, and `_check_file_integrity` into a new base class called `DownloadJob` from `FileDownloadJob` and `MessageDownloadJob`.  `_decrypt` will also be moved into `DownloadJob` from its derived classes in a followup PR.
* This also introduces new behavior: checking file integrity of everything that gets downloaded. So now message downloads also get checked.
No need to test in Qubes, but always feel free. This PR doesn't modify how we decrypt or download, and the extra file integrity checks is not qubes-specific.
1. …
=> Add DownloadJob

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Closes #393
To confirm regression coverage, revert fix in 72076e248759dad5647ee1acf10bc9fac912421b to see that the regression test fails.
Otherwise the manual test plan is basically the STR from #393:
0. Start up server and client, click on source A.
1. Type some text into the reply box but do not send.
2. Click on source B.
3. Click _back_ to source A: the reply box text you added should still be there.
This PR is GUI only, so no Qubes testing is required
=> save in-progress replies via persisting SourceConversationWrapper

securedrop_client/api_jobs/downloads.py, securedrop_client/api_jobs/uploads.py, securedrop_client/logic.py, tests/api_jobs/test_downloads.py, tests/api_jobs/test_uploads.py, tests/test_logic.py
Fixes #432
1. Checkout `master` branch, send a reply on Qubes against an app server running SD version 0.13.0 or SD version 0.13.1 with [this line of code](https://github.com/freedomofpress/securedrop/blob/0005dc5890e48ad39604b72cb394c9b8a3449cd9/securedrop/models.py#L172) commented out, and see the app crash.
2. Checkout this PR branch, send a reply on Qubes, and see that the app no longer crashes. Also look for the log message that the reply failed to send.
=> Issue 432 fix

.circleci/config.yml
This is a followup from: #422
`master` must _always_ produce a packaged client that is in a working state after build: in #422 we verified that the build succeeds on `master`. However: if `build-requirements.txt` is out of sync with `requirements.txt`, the client may not work as expected if it relies on functionality added in the new dependency added in `requirements.txt`. This would have been the case if #421 was merged as is (in that branch `requirements.txt` is updated but _not_ `build-requirements.txt`)
This PR runs `make requirements` prior to build such that the build will fail if `build-requirements.txt` is out of sync with `requirements.txt`
1. See branch `ci-test-this-job-fails`, which updates a dependency in `requirements.txt` without updating the `build-requirements.txt`
2. See …
=> ci: fail build if build requirements need update

Makefile
=> unpin bandit

securedrop_client/gui/widgets.py, securedrop_client/resources/images/error_icon_white.svg, tests/gui/test_widgets.py
Resolves #437 
Note: The error bar color is the same as the error bar color used in the client.
All should work as it did before, but errors are displayed in a bar with an error icon now. Run the client and trigger the four different validation errors that you see in the screenshots in #437.
=> Issue 437 error state

securedrop_client/api_jobs/downloads.py, securedrop_client/logic.py, tests/api_jobs/test_downloads.py, tests/test_logic.py
Fixes #383
Notes:
* The job will keep getting added to the queue until it succeeds (the retry is only for hash mismatches, not for ETags missing or other kinds of download failures).
* To that end, I know we discussed this, but I haven't made the downloads autofail if the ETags are missing or the hash algorithm is wrong. These ETags exist only to prevent corrupted downloads and are not a security mitigation, and failing to open files (failing closed) even if the downloads are likely fine seems aggressive. Again, note that this PR still has the downloads fail if the hash is present _but incorrect_.
* I'm not raising any messaging to the user when this validation/hash mismatch is happening. I could imagine that "Your download failed! Trying again..." might be a useful status to raise, but …
=> app: automatically rerun download jobs until the hashes validate

securedrop_client/queue.py, tests/test_queue.py
Fixes #419. @creviera is correct: since we're not running this queue in the GUI thread, events will be processed without needing to explicitly call `QApplication.processEvents`.
You can verify for yourself that events are being processed by checking out this diff, adding a `time.sleep(5)` at the end of the queue loop [here](https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/queue.py#L51)  and running the application. You'll see each job finish and the UI update as expected after each job. 
=> remove now unnecessary QApplication.processEvents calls

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py
Resolves #411 without the ellipsis or hover-over overlay, which I believe @rmol is working on a generic solution for.
Here's an example of what this looks like (without styling) and only a first name:
Here's an example of what this looks like (again, without styling) and with a long first and last name:
Log in to the journalist interface and try setting different names to see initials and fullname change in user profile widget.
=> Issue 411 user profile name

securedrop_client/gui/widgets.py
Sets standard message spacing and message width as speced in zeplin. Closes #466 
Adds a tiny 5px color bar (as defined in zeplin) to the bottom of each message:
and the reply will turn coral on reply failure: 
Closes #365 (will file followups for the other reply failure tasks)
Test the GUI changes seem reasonable, and also verify the reply failure case updates the UI (I put in an `abort(500, 'TEST')` [here](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/journalist_app/api.py#L233) to test)
Also follow STR from #466 in order to test that the message spacing is now uniform 28px and cannot push down the color bar. 
If these changes modify code paths involving cryptography, the opening of files in VMs, network (via the RPC service) traffic, or fine tuning of the …
=> app: add color bar on bottom of message bubbles, set standard message spacing

.circleci/config.yml, tests/test_resources.py
Without a QApplication the code will core dump as menioned
in the issue.
Fixes #478
`make test TESTS=tests/test_resources.py`
Not required.
=> Fixes #478 creates QApplication for QPixmap

securedrop_client/api_jobs/uploads.py, securedrop_client/crypto.py, tests/api_jobs/test_uploads.py, tests/test_crypto.py
Fixes TypeError bug (partial fix for https://github.com/freedomofpress/securedrop-client/issues/475)
1. Run regression test on `master` branch: `TESTS=tests/api_jobs/test_uploads.py::test_send_reply_failure_when_repr_is_none make test` see it fail
2. Run regression test on `issue-475-reply-bug` branch and see it pass
3. Send a reply in Qubes and you'll no longer see the error log: 
```
ERROR: Job <securedrop_client.api_jobs.uploads.SendReplyJob object at 0x65ed9994dc18> raised an exception: SendReplyJobException: Failed to send reply for source 31838d94-872c-496f-8828-0af5ae44c6bb due to TypeError("Can't convert 'NoneType' object to str implicitly",)
```
You will see this underlying error, which will be fixed in a follow-up PR: 
```
gpg: [stdin]: encryption failed: No public key
```
If …
=> Issue 475 reply bug

README.md
Docs to clarify the difference between various developer environments
=> docs: clarify the difference between developer environments

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #467 
Fixes #463
(medium term refactor in #473, this fix unblocks other development tasks for now)
0. Log into client
1. Create new source via source interface
2. Refresh client and click on source
3. Add message in source interface
4. Refresh again, new message should appear
5. Add message in source interface
6. Star source
7. New message should appear
=> Fix conversation refresh bugs 467, 463

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, tests/gui/test_init.py, tests/gui/test_widgets.py
`SecureQLabel` automatically applies `html.escape` to its text.
Fixes #369.
- run `make check`
- Run the client against a SecureDrop server and confirm that the places where `QLabel` has been replaced with `SecureQLabel` (speech bubbles, the file Download button) still work and that if you submit a message or reply containing HTML, that it appears in the conversation as escaped text.
=> Add SecureQLabel

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
=> gui: center all popup windows

securedrop_client/api_jobs/base.py, securedrop_client/api_jobs/downloads.py, securedrop_client/gui/widgets.py, securedrop_client/queue.py, tests/api_jobs/test_base.py, tests/gui/test_widgets.py, tests/test_queue.py
Fixes #423.
After investigation, #423 is a worthwhile architectural change as we get some major benefits:
* We can continue to use a single general (priority) queue instead of many separate queues (what we were previously considering) for different actions (i.e. a priority queue is the right data structure for the situation where e.g. we want a metadata sync to occur with high priority every 5 minutes and then other tasks at lower priorities when we get time e.g. starring or flagging). Still worth having the file download queue to be separate so that file downloads (which can take a long time) occur concurrently with other shorter-lived actions (all in the general priority queue). 
* This PR adds an execution priority for each server-related (job) action - unimplemented options are …
=> use priority queue for job processing

securedrop_client/gui/widgets.py
This issue focuses on using the same background color for scrollarea, conversation view, selected source.
Towards https://github.com/freedomofpress/securedrop-client/issues/299
=> Same bg for scrollarea, conversation view, selected source

MANIFEST.in
Fixes https://circleci.com/gh/freedomofpress/securedrop-debian-packaging/272?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link and required to test/merge https://github.com/freedomofpress/securedrop-debian-packaging/pull/72
- check out https://github.com/freedomofpress/securedrop-debian-packaging/tree/sd-svs-filehandlers-in-package
=> Add sd-svs-qubes-gpg-domain.sh to manifest

securedrop_client/gui/widgets.py
Removes borders around source list, send icon, and reply box. 
Towards https://github.com/freedomofpress/securedrop-client/issues/299
/cc @kushaldas
=> No borders

securedrop_client/gui/widgets.py, securedrop_client/resources/images/error_icon.svg, tests/gui/test_widgets.py
Towards https://github.com/freedomofpress/securedrop-client/issues/438
Resolves https://github.com/freedomofpress/securedrop-client/issues/492 and while updating weights to match zeplin, I updated colors, and sizes to match zeplin as needed (since I was already closely looking at so many fields in zeplin)
Note: some colors and fonts do not look exactly the same because of how zeplin has styled many fonts to use different letter spacing, font stretch, shadowing, and line height. This work has been moved to a separate issue which will be tracked in https://github.com/freedomofpress/securedrop-client/issues/438
See results:
If these changes modify code paths involving cryptography, the opening of files in VMs, network (via the RPC service) traffic, or fine tuning of the graphical user …
=> update font weights to numbers and match zeplin

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Closes https://github.com/freedomofpress/securedrop-client/issues/340
1. Start the client, see text (if there are sources):
```
Select a source from 
the list, to:
• Read a conversation
• View or retrieve files
• Send a response
```
2. Delete sources until there are no more sources and see text:
```
Nothing to see just yet!
Source submissions will be listed to the left, once downloaded and decrypted.
This is where you will read messages, reply to sources, and work with files.
```
UI polishing for this text being tracked in https://github.com/freedomofpress/securedrop-client/issues/509
=> Add EmptyConversationView

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Pushing one of the commits for the preview text that's been sitting as a WIP PR for a long time. This moves the date to the bottom right corner and star to the left "gutter".
=> move star and date in source widget

securedrop_client/api_jobs/downloads.py, securedrop_client/queue.py, tests/api_jobs/test_downloads.py
=> set realistic timeouts, scale file/message download timeouts using file size metadata

securedrop_client/gui/__init__.py, tests/gui/test_init.py, tests/gui/test_widgets.py
Fixes #183
Submit a message with quotes, see that it appears normally:
instead of:
=> SecureQLabel now does not escape quotes

.github/CODEOWNERS, .github/pull_request_template.md
Followup to recent Qubes dev env changes, we want to ensure that since there are multiple ways of testing or developing on Qubes (as specified in the README), that changes are done in a dev env with the RPC service and split-gpg
=> pr template: ensure Qubes testing is done with RPC service, split-gpg

README.md
Small readme update where python3.5 is replaced with python3.7
=> python3.5 -> python3.7

README.md
~Upgrade our PyQt dev dependency and~ **update readme docs about updating dependencies.**
~Even though we're no longer seeing #273 occur, we know that the upstream qt bug was fixed in a version of Qt later than the one we've been using.~
~Resolves https://github.com/freedomofpress/securedrop-client/issues/273~
=> Update docs around upgrading dependencies

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Previously the left click event would not be triggered on the QPushButton - instead slightly above the QPushButton on the parent FileWidget. This event handler which we can reuse for multiple buttons if we like (we can also use to trigger alternative logic for e.g. right clicks) should make it so clicking exactly on the button triggers the download action. 
Important note: The last commit I was not able to test due to an error on download due to an unrelated issue I'm also seeing on master (will file bug if I'm not able to figure out what is going on) - please test that! We do need to ensure that the left click also fires on click to open the file (since the download button will be hidden).
=> ui: add event handler on FileWidget

securedrop_client/api_jobs/base.py, securedrop_client/api_jobs/uploads.py, securedrop_client/logic.py, securedrop_client/queue.py, tests/api_jobs/test_base.py, tests/api_jobs/test_uploads.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/533
Towards https://github.com/freedomofpress/securedrop-client/issues/443
Now when SendReplyJob fails because of a timeout, the api call is retried 5 times, and then re-processed in the queue until the timeout issue is resolved.  
This is the same behavior for other jobs that receive timeout errors.
Note: This does not fix https://github.com/freedomofpress/securedrop-client/issues/294 because that happens when replies are in the queue and never reach the server (the timeout issue is never resolved during the client session).
In addition to making sure the two issues are no longer reproduced, follow these steps to test:
1. Send reply after pausing the staging app server vm, wait and observe 5 `Keyring access` qubes …
=> Keep trying failed replies

securedrop_client/api_jobs/base.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/queue.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_queue.py
The queues now pause when there is either an auth error, api connection failure, or request timeout error. The queues resume when the user clicks "Retry" or upon a sync/refresh after the issues are resolved.
Resolves https://github.com/freedomofpress/securedrop-client/issues/443
Towards https://github.com/freedomofpress/securedrop-client/issues/391
Make sure acceptance criteria is satisfied: https://github.com/freedomofpress/securedrop-client/issues/391#issue-449547635, and follow these steps:
1. Send reply after pausing the staging app server vm, wait and observe 5 Keyring access qubes notication popups and reply bar turn red in the gui and the SecureDrop error message and Retry link.
2. Unpause the staging app server vm
3. Click Retry link and wait until the next sync happens or …
=> Pause queue on auth errors, connection failures and timeouts

Makefile
Run security checks for target that is supposed to run all CI checks so that a dev knows ahead of time when CI will fail.
=> add bandit to check target

securedrop_client/export.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_export.py, tests/test_logic.py
Adds export functionality to the client.
From Qubes:
1. Start the client and make sure the Export VM is running and configured correctly
2. Plug in your luks-encrypted transfer device and click Export next to the file you want to export
3. Type in your passphrase and click Submit
4. Once the transfer is successful, you will see a SecureDrop Qubes notification saying so
5. Check you transfer device for the file
Test this with the wrong password and without a transfer device plugged in. If you see any strange behavior, first check the known issues in the securedrop-export repo to see if it's already documented.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. …
=> Basic export integration with placeholder messaging

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
If there is an error during the preparation stage, make sure to hide the message "Preparing export..."
=> Hide "Preparing export" message when error occurs during preparation stage

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Small PR to fix bug with showing two sets of instructions for after a bad passphrase.
Messaging before:
> The passphrase provided did not work. Please try again.
> Enter password for safe USB drive.
> Passphrase
Messaging now:
> The passphrase provided did not work. Please try again.
> Passphrase
=> Show/hide instructions in USB passphrase dialog depending on bad_passphrase

securedrop_client/export.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_export.py, tests/test_logic.py
Fixes #561
Also for testing I've added some debug lines (which are worth leaving in) to demonstrate these export actions are running in the right thread (`export_thread`), logs from a test run just now: 
```
2019-10-10 11:14:24,538 - securedrop_client.api_jobs.downloads:130(_download) INFO: File downloaded: 2-somber_junction-doc.gz.gpg
2019-10-10 11:14:24,588 - securedrop_client.api_jobs.downloads:147(_decrypt) INFO: File decrypted: 2-somber_junction-doc.gz.gpg
2019-10-10 11:14:24,980 - securedrop_client.logic:617(run_export_preflight_checks) DEBUG: Calling export preflight checks from thread 140735889998720
2019-10-10 11:14:24,981 - securedrop_client.export:237(run_preflight_checks) DEBUG: beginning preflight checks in thread 123145349275648
2019-10-10 11:14:29,982 - …
```
=> app: move export calls to separate thread

.circleci/config.yml, securedrop_client/utils.py, tests/test_app.py
towards #527
add buster test job (build job we can't add until we update our pip mirror) and gets tests passing on buster / python 3.7.
the one application change here is to ensure that calling `safe_mkdir(sdc_home)` directly actually creates `sdc_home` - previously it would just return without creating the directory.
1. Make a python 3.7 virtualenv
2. Ensure you can start the application
3. New CI job should also pass
=> ci + test: buster, python 3.7 support

securedrop_client/api_jobs/downloads.py, tests/api_jobs/test_downloads.py
This is a quick adjustment to our timeout estimation function that scales the timeouts per file so that in general it increases as the file size increases.
It turns out that we could only download very small files due to a scaling bug which added 7.5 seconds to the timeout for every single byte in the file. This change makes it so that timeout is calculated by dividing the size of the file by the estimated download rate, which we get from Tor metrics: https://metrics.torproject.org/torperf.html?start=2019-05-02&end=2019-07-31&server=onion
Couple notes:
* This is not a final solution. This is a quick fix to make it so that most of the time our download timeouts are pretty good and we can download files. It does not account for unexpected network latency issues. This will be addressed in a …
=> Adjust download size scaling factor (part 1)

securedrop_client/storage.py
Fixes database warnings about double deletion
warnings were caused by double deletion of messages
- once upon updating the sources
- another upon updating files, messages and replies
The bug was in `update_local_storage()` in the file `securedrop_client/storage.py`. Bellow is a copy of the buggy version.
```python
def update_local_storage(session: Session,
remote_sources: List[SDKSource],
remote_submissions: List[SDKSubmission],
remote_replies: List[SDKReply],
data_dir: str) -> None:
local_sources = get_local_sources(session)
local_files = get_local_files(session)
local_messages = get_local_messages(session)
local_replies = get_local_replies(session)
remote_messages = [x for x in remote_submissions if x.filename.endswith('msg.gpg')]
remote_files = [x for x in remote_submissions if not …
```
=> close #360 fix db warnings upon source deletion

securedrop_client/export.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/storage.py, tests/gui/test_widgets.py, tests/test_export.py, tests/test_logic.py, tests/test_storage.py
Tells the user that the file they're trying to export is missing from the file system. Next step is to show a Download link once again for the file that no longer exists on the filesystem, captured in this issue: https://github.com/freedomofpress/securedrop-client/issues/565
=> Handle missing files during an export and open

.circleci/config.yml
Fix ported from freedomofpress/securedrop-proxy#48, we use similar logic here in our build job so we should add the fix here also. See that PR for more details, but in short this PR ensures that diffs that update `build-requirements.txt` without updating `requirements.txt` fail CI.
CI only
=> ci: ensure that requirements files are in sync

securedrop_client/app.py
Makes it so we can change log levels for each client run and now default to INFO level.
1. `tail -f $HOMEDIR/logs/client.log`
2. `./run.sh`
See only info and error logs.
3. Ctrl+C
4. `LOGLEVEL=debug ./run.sh`
See debug logs and up.
=> add changeable log levels

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
The commit is fully functional. I just have some questions regarding tests.
Tweaks reply box according to #594:
- placeholder It should be removed as soon as soon as textbox is active. 
- added formatting to placeholder: "Compose a reply to **[source name]**" (with color)
Fixes #594
1. Login to client
2. Check the reply box has text `Compose a message to [source name]`
3. Click on text box and verify placeholder is cleared
4. Click outside text box and verify that the placeholder comes back
5. Log out and check appropriate behavior (placeholder with other text)
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, …
=> Replybox richtext placeholder with modified behavior

securedrop_client/export.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_export.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/607
=> emit export errors properly and move cleanup

securedrop_client/logic.py, tests/factory.py, tests/test_logic.py
Fixes #575 following option 1 presented in the bottom of that ticket: avoiding the round-trip to the /user endpoint by presenting everything we need at login time in the response to the /token endpoint
⚠️ This is marked as "Draft" until the corresponding SDK changes are merged and released
0. Apply small server diff: https://github.com/freedomofpress/securedrop/compare/api-journo-names
1. Merge SDK change - or simply apply it during review of this PR via `pip install -e git+https://github.com/freedomofpress/securedrop-sdk.git@token-endpoint-journo-names#egg=securedrop-sdk`
2. Confirm that login still works, and verify in the diff that there is now no second call to the server prior to the main window being displayed
If these changes modify code paths involving cryptography, the opening of …
=> app: skip round trip to user endpoint during login (fix #575)

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Towards #274
Keyboard use works in success case:
1. Provide complete credentials and log in by pressing [Enter] or [Return]
2. Confirm that you are successfully logged in
Keyboard use works in error case:
1. Provide incomplete or incorrect credentials and attempt to log in by pressing [Enter] or [Return]
2. Confirm that you see the expected error message
Clicking button still works:
1. Verify the above behavior by clicking "Sign in" instead of pressing [Enter] or [Return]
2. Confirm that the behavior is unchanged
=> Submit login form if user presses [Enter] or [Return]

securedrop_client/gui/widgets.py
Fixes #331 where the bottom source was disappearing from the source list when the window
was maximized.
It was achieved with the workaround of doing the styling in the border instead of in the background and making the border very large so that the default style is shrinked until it no longer exists. See #331 for discussion.
1. log in
2. maximise window
3. check that bottom source is still there and color and styling is correct
4. repeat 2, 3 several times as the original bug seemed to be a bit random
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please …
=> close #331 fix bug of sources disappearing from source list

securedrop_client/logic.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/622
1. Manual functional test: send a reply from a source
2. Log out and make sure you can't send a reply (otherwise we would see an error when trying to access `self.api.token_journalist_uuid`
=> update user uuid ref

securedrop_client/logic.py, tests/test_logic.py
Closes #577
I investigated what was going on with #577, turns out it's a fast fix:
the controller's `update_sources()` method is used to display in the
source list whatever is contained in local storage. If we wait until
after `sync_api` is called _before_ calling it (what we're doing on `master`),
there will be a delay of potentially several seconds until the round-trip 
to the SecureDrop server completes. In this commit we just call the 
`update_sources()` method immediately upon login.
0. Reproduce #577, i.e. confirm the the source list populates slowly (will only happen if you're going over tor)
1. Check out this branch and login
2. Confirm the source list appears populated immediately upon login
If these changes modify code paths involving cryptography, the opening of files in VMs or …
=> bugfix: populate source list immediately upon login (#577)

.circleci/config.yml
Fixes #527
Before this https://github.com/freedomofpress/securedrop-debian-packaging/pull/89 needs to get merged. Then we will have to kick the CI for rebuild.
- Get the branch from https://github.com/freedomofpress/securedrop-debian-packaging/pull/89 and then try to build the package.
```
./update_version.sh 1000.0  # Dummy version number, doesn't matter what we put here python3 setup.py sdist
cd ../securedrop-debian-packaging
export PKG_VERSION=1000.0
export PKG_PATH=/home/circleci/project/dist/securedrop-client-$PKG_VERSION.tar.gz
make securedrop-client
```
=> Updates CI to run on Buster for Debian packaging

securedrop_client/gui/widgets.py
Update strings per https://github.com/freedomofpress/securedrop/pull/5014 in SecureDrop core.
Ready for review. No Qubes-specific considerations.
=> Consistently use "two-factor code", as in SD core

securedrop_client/export.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_export.py, tests/test_logic.py, tests/test_queue.py
Resolves https://github.com/freedomofpress/securedrop-client/issues/477
Resolves #632
If you have an HP LaserJet printer like me, then update the export script with this change: https://github.com/freedomofpress/securedrop-export/tree/laserjet-printers.
1. Do not attach the printer to the Export VM
2. Print a document and see message to plug in printer
1. Plug in an unsupported printer or modify the export script to expect a dummy uri so that this check does not pass: https://github.com/freedomofpress/securedrop-export/blob/312f9f8ac5d8b2bdde66671d51ac4f075639885b/securedrop_export/export.py#L353
2. Print a document and see error message to contact admin.
1. Move /usr/share/cups/drv/brlaser.drv to /usr/share/cups/drv/brlaser.drv.bak so it's not found
2. Print a document and see error …
=> Add print integration

securedrop_client/api_jobs/downloads.py, securedrop_client/logic.py, securedrop_client/queue.py, tests/api_jobs/test_downloads.py, tests/test_logic.py
Fixes #461 
Fixes #489 (between this change and the pending reply change we should not see that bug any more)
This PR implements the `MetadataSyncJob`. A couple notes:
* I left in `on_sync_failure` which is what is creating the "The SecureDrop server cannot be reached" messages so we can observe over the coming days/weeks how often this is failing (if we still see failures, we can bump up the number of automatic tries in the queue)
* I hit an upstream `cpython` bug where a line is incorrectly showing as uncovered, see full explanation in and relevant links in e0370803aeb131941adea40af9b5bf0b85a047df
0. Open client
1. Check client populates with messages/replies/etc.
2. Send a message as a new source
3. Click sync, check the new message appears
If these changes modify code paths involving …
=> move metadata sync to api queue

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Towards #560.
Ready for review. I have tested these changes in Qubes.
=> Bring export dialog language closer to spec, add filename

securedrop_client/api_jobs/downloads.py, securedrop_client/api_jobs/updatestar.py, securedrop_client/api_jobs/uploads.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/queue.py, securedrop_client/storage.py, tests/api_jobs/test_downloads.py, tests/gui/test_widgets.py, tests/test_logic.py
Resolves https://github.com/freedomofpress/securedrop-client/issues/610
Resolves #181
* we no longer ask the user to manually refresh if a bg sync job fails, instead we auto retry in the background (this is what resolves #610)
* adds a `manual_refresh` option to `sync_api` so that if a user clicks the refresh icon and the sync fails, we show an error in the status bar with a retry link
* bumps the default timeout to 60 seconds used for login and delete (this is what resolves #181)
* queue jobs still use a default of 5 seconds for timeouts, so if the server cannot be reached, we will show the error immediately to the user if they click on the refresh icon
=> health checker/ auto-retry bg sync + adjusted timeouts

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Resolves https://github.com/freedomofpress/securedrop-client/issues/638
1. apply diff to cause some replies to fail:
```
diff --git a/securedrop/journalist_app/api.py b/securedrop/journalist_app/api.py
index aa776d520..8eb8f26c8 100644
--- a/securedrop/journalist_app/api.py
+++ b/securedrop/journalist_app/api.py
@@ -230,6 +230,13 @@ def make_blueprint(config):
{'replies': [reply.to_json() for
reply in source.replies]}), 200
elif request.method == 'POST':
+            import time
+            time.sleep(2)
+
+            import random
+            fail_early = random.choice([True, False])
+            if fail_early:
+                abort(409, 'That UUID is already in use.')
source = get_or_404(Source, source_uuid,
column=Source.uuid)
if request.json is None:
```
2. send some replies and …
=> add failure message for replies

README.md
The test suite fails on a clean install of the dev environment on an Ubuntu based machine and requires the installation of the `sqlite3` command. This PR ensures such a requirement is addressed in the appropriate place in the README.
N/A
=> Add mention of possible requirement for sqlite3 command

securedrop_client/api_jobs/sources.py, securedrop_client/logic.py, securedrop_client/queue.py, tests/api_jobs/test_sources.py, tests/test_logic.py
Add `api_jobs/sources.py` containing `DeleteSourceJob`, add its priority to `queue.JOB_PRIORITIES`, and use it in `logic.delete_source`. Add tests.
Fixes #402.
- Run `make dev` in your `securedrop` working copy
- Check out this branch in your `securedrop-client` working copy
- Run the client with `run.sh`
- Delete a source.
=> Use queue for source deletion

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Now that we no longer use [persistent attachement in Qubes for the Export VM](https://github.com/freedomofpress/securedrop-workstation/pull/323), we no longer need the workaround to ask the user to insert their drive if we see an error that might have been from the VM not booting.
=> Export VM no longer requires device to boot

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #591 . Getting the middot in there was fun. In the end I just copied and pasted an actual middot into a Python string. Was expecting Qt to have something like this already built in. 
Unit tests updated. Checked with eyeball Mk1 ~ see enclosed screenie.
=> Hover polish for file download clickables. Fixes #591.

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #606. Implements the following functionality:
* Pressing `CTRL+ENTER` while focused in the text area will send the message.
* Pressing `TAB` while in the text area will move focus to the send button (airplane).
* Pressing either `ENTER` or `SPACE` while the send button is highlighted causes it to be activated so the message is sent.
*NOTE*: Please see the GIF of a demo below and see how the scrolling of the messages jumps around. Is this expected. My feeling is you should always see the newest message (at the bottom of the message area) rather than the strange behaviour seen in this GIF.
Minor additions to the unit test suite to ensure the updated state of the UI is configured correctly.
If these changes modify code paths involving cryptography, the opening of files in VMs or …
=> Add shortcuts for sending replies. Fixes # 606.

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes ##684.
This was an adventure. After exploring a Qt rabbit hole I proved my hunch was correct (the size of the QLabel wasn't being redrawn when the `setText` method was called, hence the truncated text). Investigating a workaround ended up with the first commit which was created because I was unaware of the `adjustSize` method on the QWidget base class. However, once I found it, I scratched by work-around approach and now it works. :-)
None (needed).
=> Work around (not bug fix) for issue #684.

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, securedrop_client/resources/__init__.py, tests/gui/test_init.py, tests/gui/test_widgets.py, tests/test_resources.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/388
We're having discussions on removing the RefreshButton all together, so this fix is temporary - I just happened to be in this area of the code while consolidating load_toggle_icon with load_icon.
1. add a sleep in storage::get_remote_data
2. run the client and click refresh multiple times
3. only see the first sync that happens on login + one sync at a time from clicking refresh
=> Disable refresh

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/331 which was reintroduced at some point.
See how the first item in the SourceList is highlighted when nothing is displaying for that source. Also the highlight coloring is using the QListView default instead of our own:
1. Log into the client in offline mode and now see that the first item is not highlighted. Also when you select an item in the source list it will appear with the correct highlight color, see:
=> remove default highlight for source in source list

.circleci/config.yml
CI is currently failing, see #699 and all PRs with CI that has ran recently (e.g. #698)
This is a minimal PR to get CI passing on the test jobs to unblock merge of anything that's ready. Removing the stretch jobs and adding back the build job will happen in #699, which I'm not going to finish today hence this PR disabling the jobs temporarily.
=> ci: temporary disabling of build jobs

.circleci/config.yml
@ntoll hit a CI failure in #698, that's due to the removal of the fetch-wheels target we made in https://github.com/freedomofpress/securedrop-debian-packaging/pull/124
I'm putting this up for awareness, still working on another outstanding git-lfs issue inline tho..
=> fix ci after migrating our pip mirror to git-lfs

securedrop_client/app.py, tests/test_app.py
Now all log lines will go to `/var/log/syslog` file.
Also `black` reformatted the file.
You should be able to see the log entries in `/var/log/syslog` file. 
=> Adds SysLogHandler to log everything on rsyslog

securedrop_client/gui/widgets.py
Fixes #695.
Simple CSS update did the trick.
N/A or eyeball mk.1 :eyes: 
=> Ensure width of colour bar at bottom of replies/messages is full width.

securedrop_client/gui/widgets.py
Just realized while using the client that the eye icon should be crossed out when the characters are not visible.
=> reverse password toggle icon images

securedrop_client/db.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_models.py
Fixes #135.
The UI elements were already there. This was simply a plumbing task. I tried various approaches but this is the simplest one. The result looks like this:
**NOTE** The "not yet available" messages on initial start are cleared when the client refreshes (see screenie above). I did try to connect signals to make this work "automagically" but the code was messy and then I remembered that we're going to make the client update automatically after N-seconds in an upcoming change (i.e. the default behaviour of the client app will ensure the "not yet available" messages will update to the real content of the messages). Trust me, I much prefer this simpler approach. ;-)
One other thing, I've added `__str__` methods to the `db` based classes this touches on, since we re-use the "show me …
=> Preview last message in source list.

securedrop_client/gui/__init__.py, tests/gui/test_init.py, tests/gui/test_widgets.py
Fixes #644. Fixes #645 .
I agree with and have followed @emkll's suggestion for the fix.
Updated unit tests to reflect changes.
=> Fix HTML entities being escaped in speech bubbles.

securedrop_client/queue.py
Fixes #657
In terms of testing, you _can_ test interactively in Qubes but I think determining if you agree with the following logic is sufficient for merge:
1. User-triggered actions should be as fast as possible
2. File downloads happen in another queue so it doesn't really matter what priority they are
3. Metadata syncs will be moved in #652
If these changes add or remove files other than client code, packaging logic (e.g., the AppArmor profile) may need to be updated. Please check …
=> app/queue: prioritize user-triggered state changes

securedrop_client/storage.py, tests/test_storage.py
Closes #689
Related to @rmol's investigation in #648, we need to reduce the total number of round trips per sync. On master the number of calls during sync is scaling as N_{sources}, this reduces it to a constant (3 calls, one to each of the reply, source (still too slow due to the gpg keys but we will need to handle some server side changes first), and submission endpoints). 
Start server (`NUM_SOURCES=20 make dev` - this `NUM_SOURCES` env var adds sources with 2 submissions and 2 replies per source), run this branch.
Instead of a bunch of individual API calls for submission metadata, one per source:
```
[18/Jan/2020 05:46:29] "GET /api/v1/sources/cf74425f-d8a0-4ba3-8949-31cd208db210/submissions HTTP/1.1" 200 -
```
you'll see just one for submission metadata:
```
[18/Jan/2020 05:43:34] …
```
=> app/perf: reduce round trips during sync by N_{sources} - 1

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #706 , ensures the message previews are properly escaped. Reply previews are also escaped.
- Build a deb on this branch
- install into `sd-app` or `sd-app-buster-template`
- submit a message with rich text tags on source interface
- observe tags are escaped properly
- the tests provided in this pr provide sufficient coverage
=> Use SecureQLabel for message previews

securedrop_client/gui/widgets.py
Closes https://github.com/freedomofpress/securedrop-client/issues/718
Closes  https://github.com/freedomofpress/securedrop-client/issues/332 
[Implementing last activity timestamp](https://github.com/freedomofpress/securedrop-client/issues/538) remains open
To test:
1. Click on a source and see that the timestamp matches the format of the timestamp for the source in the source list.
=> show DD MMM format for source title

securedrop_client/gui/widgets.py, tests/factory.py, tests/gui/test_widgets.py
Fixes #473.
Fixes #635.
Fixes #691.
This is proof of concept ensures we're not deleting and recreating messages in a conversation each time a new message is added to the conversation or an update occurs.
It also handles cases where the messages are re-ordered after an update, and makes it possible to inline-update further attributes of messages as they change through time.
It was also an opportunity for me to deep-dive back into the guts of the application and figure out how it all fits together again..! :microscope: :eyes: :snake: What you see is my stab at a simple and flexible solution.
The comments / annotations in the code should explain what's going on. Please take a look and, as always, I welcome ideas, constructive criticism and other feedback. Assuming, via discussion of the PR, …
=> Inline conversation updates. Fixes #473.

securedrop_client/api_jobs/downloads.py, securedrop_client/logic.py, tests/test_logic.py
Fixes #716 
**DO NOT MERGE** this is a work in progress while further investigation takes place.
The initial removal of `update_sources` on message download ensures the UI remains responsive.
However, given a server with 200 sources, while the UI is now responsive, I no longer see the results I was able to see with far fewer sources (50) in previous tests. The server activity looks like this:
```
172.17.0.1 - - [27/Jan/2020 11:51:51] "POST /api/v1/token HTTP/1.1" 200 -
172.17.0.1 - - [27/Jan/2020 11:52:20] "GET /api/v1/sources HTTP/1.1" 200 -
172.17.0.1 - - [27/Jan/2020 11:52:43] "GET /api/v1/sources HTTP/1.1" 200 -
2020-01-27 11:52:45,411 INFO Clearing shredder
2020-01-27 11:52:45,411 INFO Files to delete: 0
```
Which suggests something is pinging the API every 20 seconds or so. Not sure …
=> Ensure UI remains responsive at all times during sync with server.

securedrop_client/queue.py, tests/test_queue.py
Found while fixing #716. Perhaps addresses #662?
If the queue has an upper limit (like the metadata queue does), then the `re_add_job` method may try to do something that results in a `queue.Full` exception being thrown. This can be safely ignored. Because this case wasn't handled, I encountered an application crash while investigating #716 which led to this fix.
In addition I noticed there being a possibility of jobs being put onto the metadata queue if the user wasn't logged in (something which shouldn't happen). This has also been fixed.
Unit tests updated to reflect both changes.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the …
=> Fix potential crash situation WRT queue.

securedrop_client/api_jobs/downloads.py, securedrop_client/crypto.py, tests/api_jobs/test_downloads.py
This improves MetadataSyncJob to only import source keys we don't yet have.
Fixes #735.
- Start a SecureDrop development server with `make dev`
- Start the client with `LOGLEVEL=debug ./run.sh` and log in.
- Tail `$SDC_HOME/logs/client.log`. You should see lines like:
`Importing key with fingerprint 35A20B41C773755691BFF27110776C0CDBECCC6F`
- Wait a minute for the next metadata sync. Now in the logs you should see that we're not importing the keys we just imported:
`Skipping import of key with fingerprint 35A20B41C773755691BFF27110776C0CDBECCC6F`
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any …
=> Don't import source pubkeys we already have

securedrop_client/logic.py, tests/test_logic.py
Resolves https://github.com/freedomofpress/securedrop-client/issues/660
1. Send a reply
2. See it updated in the gui
=> no longer sync after sending a reply

securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/resources/__init__.py, tests/gui/test_widgets.py, tests/test_logic.py
Closes https://github.com/freedomofpress/securedrop-client/issues/670
1. Download a file
2. Delete it from the filesystem
3. Try to open it and see that the gui is updated to show that the file needs to be downloaded
Repeat steps 1-3 for export and print
Currently refreshing the file object in the session clears the error status message so I removed the error message for now, see: https://github.com/freedomofpress/securedrop-client/issues/723
=> update gui instead of sync when file missing

securedrop_client/crypto.py
It's the same as universal_newlines, so just use the one that works with our specified target of Python 3.5.
Same as #749.
=> Revert usage of subprocess.check_output text parameter

alembic/versions/fb657f2ee8a7_drop_file_original_filename.py, securedrop_client/api_jobs/downloads.py, securedrop_client/crypto.py, securedrop_client/db.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/storage.py, tests/factory.py, tests/gui/test_widgets.py, tests/test_crypto.py, tests/test_logic.py, tests/test_storage.py
Eliminate `File.original_file` column and hard links to downloaded files. Now as files are downloaded and decrypted, `File.filename` will be updated.
Instead of downloading directly into the root of the data directory, create a directory therein for each downloadable object, named with its UUID, and process downloaded files in that directory. This should
eliminate collisions if multiple sources upload documents with the same names.
Fixes #714.
- Start a SecureDrop development server with `make dev`
- Visit the source interface and upload a file.
- Run the client with `run.sh`. Find your source in the list and:
- download the file
- verify that it can be opened in a disp VM by clicking on it
- verify that it can be exported
- verify that a metadata sync does not change the filename
- In …
=> Improve download file handling

securedrop_client/gui/main.py, securedrop_client/logic.py, securedrop_client/queue.py, securedrop_client/storage.py, tests/gui/test_main.py, tests/test_logic.py, tests/test_queue.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/662
Fixes https://github.com/freedomofpress/securedrop-client/issues/736
Related: https://github.com/freedomofpress/securedrop-client/issues/420 remains open
1. With a valid token, log out of the client when there are pending jobs and no longer see error message reported in #662: https://user-images.githubusercontent.com/213636/70762572-d5f70880-1d05-11ea-97c0-f7e2c9b086a5.png
1. Update `/securedrop/journalist_app/api.py` in the securedrop repo to return `AuthError` when making a `get_sources` or `get_all_replies` or `get_submissions` request and see the client log you out and open a login window, you can use this diff if you'd like, [see how this results in an `AuthError`](https://github.com/freedomofpress/securedrop-sdk/blo …
=> When token invalid user must log back in

securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_logic.py
Ready for review.
Fixes #707.
This is a preview. **There are performance issues with the code as it stands** (tested with 200 sources), but I wanted to give you a sense of the progress made so far.
It took a while to work around SqlAlchemy, but got there in the end.
* On start, the snippets are updated as soon as the messages / replies etc are downloaded from the server.
* If a new message comes in while the client is active, the snippet is appropriately updated.
* When a new reply is sent and succeeds, the snippet is appropriately updated.
* When a file is downloaded from the server, the snippet is appropriately updated.
Screenie of some of this here:
Performance refactoring currently underway.
I've updated the unit tests. Please check with Eyeball mk.1 :eyes: for functionality described …
=> Immediate update of snippets

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #639
If a source has no public key a warning message is displayed in the ReplyBox area and the widget is set to disabled so they can't send anything.
Added unit test to exercise additional logic.
=> Show warning if source has no public key.

securedrop_client/logic.py, tests/test_logic.py
The File object no longer has an original_filename attribute, which was causing a crash when downloading.
Fixes #770.
Run the client. Download a file. Confirm it crashes.
Check out this branch and repeat that process. Confirm that it does not crash.
=> Update obsolete original_filename usage in file_ready

securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/771
Fixes https://github.com/freedomofpress/securedrop-client/issues/774
Fixes https://github.com/freedomofpress/securedrop-client/issues/769
Fixes https://github.com/freedomofpress/securedrop-client/issues/766
I recommend testing on Qubes to be able to see slower state changes. Follow each bug's STR to verify that it no longer happens and for issue #771 just make sure slots expect the right arguments from their respective signals.
Still need to add tests
=> update slots and signals to match

files/usr.bin.securedrop-client
Fixes #776
Now the client can create directories under
/home/user/.securedrop-client/data/
for different sources.
=> Fixes #776 fixes mkdir permission in apparmor

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #442
Adds a new signal, slot and unit tests to ensure the timestamp is updated when new files or messages from the source arrive in the client.
Updated unit tests.
=> Add fix and tests for issue #442

securedrop_client/logic.py, tests/test_logic.py
Related to #761
Standard test plan is the way to go here
=> pure refactor: move auth checks into decorator

securedrop_client/sync.py, tests/test_sync.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/781
This bug was introduced when I made a change to stop recreating MetadataSyncJob every time we run the sync method: https://github.com/freedomofpress/securedrop-client/pull/739/commits/417473be8954ef499aae3de3d38013eac3d03aa3. This made it so that whenever sync was called, the remaining attempts would equal `NUMBER_OF_TIMES_TO_RETRY_AN_API_CALL` - 1 and eventually equal zero, so we would no longer process the job.
I added a regression test to make sure we reset the remaining attempts each time sync is called.
1. Verify that on `master` the number of syncs you see is equal to 1+ `NUMBER_OF_TIMES_TO_RETRY_AN_API_CALL`. Go into the code and modify `NUMBER_OF_TIMES_TO_RETRY_AN_API_CALL` so that you can see this is True. Also, …
=> reset remaining attempts for each sync

securedrop_client/queue.py, tests/test_queue.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/785
These changes should not need testing in Qubes
=> only resume if queue thread is running

securedrop_client/api_jobs/downloads.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/api_jobs/test_downloads.py, tests/gui/test_widgets.py, tests/test_logic.py
To export or print, a file must have been decrypted, so present `FileWidget` affordances based on that, not just whether it's been downloaded.
Also change how `FileWidget`'s download animation happens: now it starts immediately, and the timer is used when stopping instead, to ensure it always runs for at least 300ms. Credit to @eloquence for that idea.
Finally, start a `DownloadException` hierarchy, adding `DownloadDecryptionException` to the existing
`DownloadChecksumMismatchException`, so we can better diagnose retrieval problems.
Fixes #756.
Also fixes #754 as I had to fix the animation to test.
- Start a SecureDrop development server instance with `make dev` in a local working copy.
- Run the client with `run.sh`
- In a web browser, upload a file through the dev server's source …
=> Predicate FileWidget state on File.is_decrypted, not is_downloaded

securedrop_client/logic.py, securedrop_client/queue.py, tests/test_logic.py, tests/test_queue.py
This is purely a refactor.
* updated and added more documentation on how we pause, stop, and resume queues. 
* removed unnecessary code: 
- removed `resume_queues` in `on_authentication_success` since we were already starting the queues in that method
- removed `clear_error_status` from all the job success handlers and added it to the Controller's `logout` and `resume_queues` methods.
* split `on_queue_paused` into `on_file_download_queue_paused` and  `on_main_queue_paused` so we could have clear debug logs on which queue we're pausing
* updated logs and log levels for clarity
=> Refactor queue resume/stop/start

securedrop_client/api_jobs/sync.py, securedrop_client/crypto.py, securedrop_client/storage.py, tests/api_jobs/test_sync.py, tests/factory.py, tests/test_storage.py
Only set `db.Source.public_key` and `db.Source.fingerprint` when a source's key is successfully imported to the local key ring. This allows us to use those columns to check the presence of the key and save a call to GPG during sync.
Fixes #757.
Run the client against a local dev server with `LOGLEVEL=debug`. Observe in the logs that the initial sync imports source public keys, and subsequent ones skip the imports. Observe that there is no keyring access popup for syncs where no new keys are imported.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check …
=> Improve efficiency of source key management

securedrop_client/gui/main.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/806
+ a little name refactor
=> update sync method names and message

securedrop_client/api_jobs/uploads.py, tests/api_jobs/test_uploads.py
#820 consists of two parts:
1. Ensuring that exceptions in reply job processing cannot crash the app, and
2. Resolving races between the sync and the reply job (see comment [here](https://github.com/freedomofpress/securedrop-client/issues/820#issuecomment-591585400)).
This just addresses the first part. I do not see crashers now locally, instead the reply will show up as failed. 
1. Apply diff here from the case @creviera found:
```diff
diff --git a/securedrop_client/api_jobs/uploads.py b/securedrop_client/api_jobs/uploads.py
index 8616b71..dac78c1 100644
--- a/securedrop_client/api_jobs/uploads.py
+++ b/securedrop_client/api_jobs/uploads.py
@@ -98,7 +98,7 @@ class SendReplyJob(ApiJob):
-        api_client.default_request_timeout = 5
+        api_client.default_request_timeout = 0.01 …
```
=> ensure exceptions in reply job processing don't crash the application

securedrop_client/api_jobs/uploads.py, tests/api_jobs/test_uploads.py
Fixes #653.
supersedes #818
follow STR in 653
=> app: fix reply ordering

securedrop_client/api_jobs/uploads.py, securedrop_client/logic.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/604
Towards https://github.com/freedomofpress/securedrop-client/issues/653
We have another draft PR (https://github.com/freedomofpress/securedrop-client/pull/818) that I'll be looking at today that is working to fix #653. This PR fixes the out-of-order issue for replies that time out (since we no longer mark them as failed). https://github.com/freedomofpress/securedrop-client/pull/818 will fix the out-of-order issue for replies that fail for some other reason.
This will go from draft->ready for review once I update tests.
Run through STR#1 for #653 and make sure replies are no longer out of order and that replies that time out are still shown as pending.
If these changes modify code paths involving cryptography, the opening …
=> no longer mark replies as failed if they time out

securedrop_client/storage.py, tests/test_storage.py
Fixes #717 .
This is hard to test manually. I've added an automated test in `test_storage.py::test_sync_delete_race`; please scrutinize that to make sure it's faithful to the hypothetical scenario.
=> If a source is deleted during sync, don't add its messages

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Both `ReplyBoxWidget` and `ReplyTextEdit` must be disabled when no keypair is available for a source. I have changed the method names to `set_logged_in`/`set_logged_out`, consistent with the use in ReplyTextEdit, because this more accurately describes what they do (the widget can be in online mode, but disabled).
Resolves #803 
1) Start a development or staging server environment and generate a couple of sources.
2) Disable keypair generation for _new_ sources on the server (easiest by returning immediately in the `async_genkey` function in `securedrop/source_app/utils.py`).
3) Log in with the client to the server
4) - [ ] Confirm that the reply box for the sources you created in step 1 works as expected (i.e. you can reply as normal and the "Compose a reply" placeholder text is shown). …
=> Clearer message in "no keypair" case, fix styling

securedrop_client/gui/__init__.py, tests/gui/test_init.py
Fixes #815.
I use the built-in `textwrap` module with its default behaviour (which seems eminently sensible) to ensure that long words / sentences are wrapped in a way that fits properly in a `SecureQLabel`'s text area.
See the following screenies for example output:
Added unit test to ensure default word wrapping works as expected. Please check with eyeball Mk.1 :eyes:
If these changes add or remove files other than client code, packaging logic (e.g., the AppArmor profile) may need to …
=> Fix word wrap issue in SecureQLabel.

securedrop_client/logic.py, tests/test_logic.py
Towards https://github.com/freedomofpress/securedrop-client/issues/775 
This implements the part where we add the "Retrieving new messages" notification, but instead of it remaining until the last download job is finished, the notification will last 2.5s.
1. Send a message or more as a source
2. Right after a sync see the "Retrieving new messages" notifcation for 2.5s
=> show a short notification when new messages about to download

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/test_logic.py
Resolves https://github.com/freedomofpress/securedrop-client/issues/798
Resolves https://github.com/freedomofpress/securedrop-client/issues/811
1. run the client against staging
2. pause the staging server vm
3. send a reply and see "The SecureDrop server cannot be reached. Trying to reconnect..." without a retry link
4. send another reply and see the same message without a retry link
5. unpause the staging server vm
6. see the error message go away
1. apply this diff so a reply will timeout:
```diff
--- a/securedrop_client/api_jobs/uploads.py
+++ b/securedrop_client/api_jobs/uploads.py
@@ -96,7 +96,7 @@ class SendReplyJob(ApiJob):
-        api_client.default_request_timeout = 5
+        api_client.default_request_timeout = 0.01
return api_client.reply_source(sdk_source, encrypted_reply, …
```
=> Standardize connection errors

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #791 
A trivial change. Took a while to spot why the flicker was happening. Parenthesis to clarify logical order of precedence.
No unit test change needed. Eyeball Mk.1 used to confirm flickering no longer happens. :eyes:
=> Fix flicker on mouse over in download button.

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #796.
Updated unit tests to ensure change of state only occurs if a source has been selected.
=> On update, only select a current source if it's already selected.

securedrop_client/api_jobs/uploads.py, tests/api_jobs/test_uploads.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/833
=> fix reply succeeds but still shows up as failed

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Sets ReplyWidget state to succeeded when its text is updated. Apply CSS to its children according to its state.
This solves the problem of replies being stuck in pending state if their uploads only seemed to the client to fail, but did in fact succeed.
It also works around a new failure in Qt stylesheet handling which _might_ be due to changes in the Debian package `qtbase-opensource-src` at `5.11.3+dfsg1-1+deb10u2`, which incorporated upstream changes that changed how stylesheets are applied to children. 
That theory is a bit shaky, though, because with the same system packages installed, installing the same version of PyQt5 in a virtualenv results in the old approach working fine. That's unfortunately not an option for us at this time, as it would be a huge addition to the production …
=> Change how ReplyWidget style is updated on changes

securedrop_client/logic.py, securedrop_client/storage.py, tests/test_logic.py
Fixes #808 .
I generally work by the "rule of three" when it comes to refactoring repeated code (i.e. the section where there's an iteration over the missing files in `logic.py`). Happy to refactor if you'd like. In any case, UI behaves like this:
Updated unit tests to encompass handling of missing file.
=> Ensure UI updates if local copy of downloaded file is no longer available.

securedrop_client/gui/widgets.py, securedrop_client/resources/images/login_bg.svg
Fixes #710.
This branch introduces four changes to fix #710 and thus https://github.com/freedomofpress/securedrop-ux/issues/86
1. The background SVG is set to the latest version provided by @ninavizz 
2. Left padding of 5px has been added to text input.
3. Version information has been (re)added -- see further discussion below.
4. When the "SIGN IN" button is clicked its text changes to "SIGNING IN".
Obligatory screenie of this all in action:
**Further discussion:**
The images in the original ticket (#710) used the colour `#9fddff` which looked like this:
To my eyes this didn't provide enough contrast, so I've used Grimace Blue instead:
Finally, the SVG referenced in the original ticket (https://github.com/freedomofpress/securedrop-ux/issues/17#issuecomment-478797141) didn't work with Qt …
=> Update login screen to latest design.

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #804.
Removes the line causing the hover state to be ignored. AFAICT the line that has been deleted shouldn't need to be there since the colour is correctly specified in the CSS for the FileWidget as is. I'm not sure why this was added. Can someone please check I'm not missing some wider context here..?
Checked with Eyeball Mk.1 :eyes:
If these changes add or remove files other than client code, packaging logic (e.g., the AppArmor profile) may need to be updated. Please check as …
=> Fix problem where download_button CSS was ignored

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #843.
- Ensure that the client will not receive server confirmation of sent replies -- the easiest way is to probably set the job timeout to `0.001` [here](https://github.com/freedomofpress/securedrop-client/blob/8a1fddb4130b6c02abede2b51a63e6f5aaaee3ec/securedrop_client/api_jobs/uploads.py#L122).
- Send a reply. It should not be marked successful because of the timeout.
- Wait for sync. The reply, which actually made it to the server, should be downloaded, and its widget should transition to the success state.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is …
=> Remove ReplyWidget._update_text

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/828
In addition to ensuring the "expected" section of the STR in #828 now happens, also ensure that the close button still closes the dialog when it is clicked or when you press Enter while it's focused (by tabbing to it).
=> enter no longer closes dialog

files/usr.bin.securedrop-client, securedrop_client/logic.py, securedrop_client/storage.py, tests/test_logic.py, tests/test_storage.py
Fixes #856
There are two ways sources can be deleted: via the metadata sync (since sources and submissions can be deleted by other users) and via the source deletion job (if the client user deletes a source). In the latter place, we were previously only deleting the source database row, the documents would remain on disk. 
1. Apply the AppArmor profile change and this code diff. You can do either by building the deb on this branch and installing it in `sd-app`, OR by copying the AppArmor profile into place (in `/etc/apparmor.d/`), running `sudo service apparmor restart`, and copying the code on top of the existing installed code (e.g. in the root of the git repository `sudo cp -r securedrop_client /opt/venvs/securedrop-client/lib/python3.7/site-packages/`).
2. Start client via …
=> app: delete source collection when source is deleted locally

securedrop_client/gui/widgets.py
This ensures that we will eventually be able to reply to a source who gains a public key after sync.
Fixes #862.
The problem seems easier to reproduce in a staging or production environment. 
1. You can either build a `securedrop-client` .deb and install it in `sd-app`, or check out this branch, then copy `securedrop_client/gui/widgets.py` to `/opt/venvs/securedrop-client/lib/python3.7/site-packages/securedrop_client/gui/widgets.py`.
2. Run the client with `LOGLEVEL=debug` so you can see the key handling messages.
3. In the source interface, log in as a new source.
4. Back in the client, watch for the new source to appear. It will likely not yet have a public key, so you should see the `Awaiting encryption key...` message in the reply box.
5. After no more than a couple of syncs, the …
=> Update ReplyBoxWidget on sync

securedrop_client/logic.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/882
=> only force relogin if not already logged out

securedrop_client/logic.py
Fixes #875
1. Download a file in the client
2. Verify that "Downloading file" message no longer appears in top left
=> Remove "Downloading file" message in sync area

securedrop_client/api_jobs/sources.py, securedrop_client/logic.py, tests/api_jobs/test_sources.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/878
Watch out for https://github.com/freedomofpress/securedrop-client/issues/859 which this does not resolve.
See that #878 is fixed. You will want to test with `RequestTimeoutError`, `ServerConnectionError`, and `Exception` (any error other than `RequestTimeoutError` and `ServerConnectionError` should show the "Failed to delete source at server" message. Also still open to suggestions on a rewrite of that error message.
=> retry on source deletion timeout

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #880
This is a rare crasher, so you're going to need to verify that the following logic is sound:
=> app: ensure we do not keep references to a SourceWidget that has been deleted

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, tests/gui/test_init.py, tests/gui/test_widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/841
Fixes https://github.com/freedomofpress/securedrop-client/issues/854
Must test in Qubes
1. run the client and see that "ENCRYPTED FILE ON SERVER" no longer word wraps
2. make a reply fail and see that "Failed to send" no longer wraps
3. download a file and see that a long filename no longer word wraps and instead shows the truncated text with `...` at the end and a hoverover tooltip with the full filename length
4. click on export and see that a long filename shows the truncated text with `...` at the end (no tooltip support yet) 
5. click on print and see that a long filename shows the truncated text with `...` at the end (no tooltip support yet) 
If these changes modify code paths involving cryptography, the opening of …
=> Update SecureQLabels to address new wordwrapping behavior

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py
Similar fix to #887 but for the remaining crasher bugs
Fixes #859
Fixes #857
0. Start dev server
1. Run client with debug-level logs: `LOGLEVEL=DEBUG ./run.sh`
2. Click on a source (this creates its `SourceConversationWrapper`). 
3. Delete the source locally, see that the `SourceConversationWrapper` was deleted: 
```
2020-03-09 17:58:59,541 - securedrop_client.storage:61(delete_local_source_by_uuid) INFO: Deleted source with UUID c84874c7-cf7c-4d66-9fdb-c98334a4de07 from local database.
2020-03-09 17:58:59,598 - securedrop_client.gui.widgets:729(delete_source) DEBUG: Deleting SourceConversationWrapper for c84874c7-cf7c-4d66-9fdb-c98334a4de07
```
4. Use the JI to delete a source that you haven't clicked on yet in the client. Wait for a sync. See that you see the following:
```
2020-03-09 …
```
=> fix remaining app crasher bugs

securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/905
Fixes https://github.com/freedomofpress/securedrop-client/issues/352
We currently delete all source widgets and recreated them every time a user logs in, a user deletes a source, and whenever the client syncs with the server.
This PR makes it so only add source widgets when there are new sources and delete source widgets when the source has been deleted.
Performance testing on a large source list will need to be done over the next day or so. Also we should check if this helps with the flicker issue.
Make sure there are no regressions. This is a refactor so the source list should behave the same.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) …
=> no longer delete all source widgets each update

securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/858
1. Delete a source and see the new pending state
2. confirm https://github.com/freedomofpress/securedrop-client/issues/858 no longer happens
=> waiting delete confirmation support

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #913
More details on the issue: `delete_source` can be deleting a `SourceConversationWrapper` at the same time the source is selected and  `on_source_changed` is called which will delete the `SourceConversationWrapper` if the source no longer exists.
This change makes it so that `on_source_changed` no longer deletes the conversation since we can rely on `delete_source` (renamed to `delete_conversation` to be clearer about how we already deleted the source item and source widget in the source list and now are deleting the corresponding conversation widget) to be called once the source is deleted.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For …
=> only delete conversation in one place

securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/test_logic.py
Part of #53. Makes error messages a bit more consistent and (hopefully) friendly:
- Always use "passphrase", not sometimes "password".
- Use "that won't work" for form submissions that instantly fail validation, followed by the reason
- Use "that didn't work" for form submissions that fail after being sent, followed by actionable advice (use a fresh two-factor code).
Switches the error bar to SecureQLabel as apostrophes were otherwise displayed incorrectly.
Updates the version string as previously discussed [here](https://github.com/freedomofpress/securedrop-client/pull/789#issuecomment-584782944).
- Verify that all errors are handled as expected per the screenshots below, including in Qubes.
<details>
<summary>Click to expand</summary>
</details>
=> Update login UI messages per UI messages audit

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, tests/gui/test_init.py, tests/gui/test_widgets.py
Fixes #869.
TL;DR width of the LHS pane, width of the preview in the source preview widget, textwrap increased to 80 [was 70] characters a line. Screenie:
@ninavizz looks at it and provides comments. :eyes:
=> Fix wider with to LHS of UI. More space for source preview.

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #847. **THIS IS A DRAFT** pending feedback from @ninavizz.
I went for using "rich text" in the QLabel since this avoid hand rolling a bunch of new Qt Widgets. This has had mixed success. Here's a screenie so you see what I mean:
I don't have any control over the size of the bullet points, and the only HTML-ish control I have over the text in Qt is described here: https://doc.qt.io/qt-5/richtext-html-subset.html As a result, while I know the screenie shows something similar or "inspired by" @ninavizz's design, it's honest-to-god the closest damn thing I can get to the design. Also, Qt's HTML doesn't do fixed widths (see their HTML spec) ergo, the behaviour of resizing is shown in the following screenie:
Yes... I realise the `<hr/>`'s are black -- I don't have control over that. :-( …
=> HTML-ize the no-source selected text.

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py
Fixes #877. This branch is stacked on top of #897.
This branch ensures that the `textwrap` related work in the `SecureQWidget` class has the optimal value for the max-width for wrapping. I'd like feedback on this approach and a heads-up on what, if anything, this approach may take (as far as I can tell, it's not broken anything).
The end result looks like this:
Visual check with Eyeballs Mk.1 to ensure various previously problematic cases are rendered correctly by Qt.
If these changes …
=> Fix word wrap in source

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, tests/gui/test_init.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/930
Fixes https://github.com/freedomofpress/securedrop-client/issues/885
This fixes the regression where we started condensing message text in order to show 3 lines of preview text. Since we only show one line of preview text now, I removed the code that condenses text, which fixes #885. 
This also makes sure we indeed only show one line of preview text and removes duplicate wrapping code. We now solely rely on QLabel's setWordWrap method.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please …
=> Preview oneline and no longer condense text

securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py
`StarToggleButton.on_authentication_changed` would just keep connecting signal handlers without ever disconnecting those previously installed.
When not authenticated, we'd set a signal handler to show the "You must sign in" message when pressed. That handler was never disconnected once authentication was successful, so if the timing were right at startup, it would get installed permanently.
Similarly, we could end up with multiple `on_toggle` handlers, sending multiple `UpdateStarJob`s for a single click on the `StarToggleButton`.
This change disconnects all handlers for the previous authentication state when authentication state changes.
Also, the `Controller.is_authenticated` setter emitted the `authentication_state` signal before updating `self.__is_authenticated`. To prevent that ever …
=> Ensure correct StarToggleButton signal handler state

securedrop_client/api_jobs/base.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/sync.py, tests/gui/test_widgets.py, tests/test_sync.py
Fixes #888.
In `widgets.SourceList.update`, make sure that existing `SourceWidget`s are updated. This requires refreshing each source's state in the controller session. On sync, sources were being properly updated in the database via `storage.update_sources`, but without this refresh, a source being unstarred on the server, for example, wouldn't be reflected in the UI until some other operation caused the source to be refreshed in the controller's session.
Commit after updating a source's `is_starred` field in `widgets.StarToggleButton.on_update`, preventing a `sqlite3.OperationalError` saying "database is locked".
In `sync.ApiSync.on_sync_failure`, keep syncing no matter the error, and have the log message say less about the cause.
Log more details about API job failure in …
=> Ensure that sources are properly refreshed on sync

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #935 .
- Start the client and log in.
- Confirm that you can star and unstar sources and the star icons behave.
- Log out.
- Confirm that you can not star or unstar sources, and that the star icons do not change, and there's no hover state suggesting they can.
=> Ensure StarToggleButton hover states honor offline status

securedrop_client/gui/widgets.py
The icon was being reset to always-on even if the source weren't starred. This adds a check for that, and also corrects the misleading naming of the attribute determining whether the star API calls should be made when the widget state changes. (If it only takes a weekend for your naming to start tripping you up, it was clearly not thought through.)
Fixes #938.
Follow #938 STR. Unstarred sources' stars should not be starred on hover, nor suggest they can be in the offline state. The latter is counter to the `Expected behavior` section of #938, but seems less surprising.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user …
=> Fix StarToggleButton hover leave

securedrop_client/db.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_main.py
Fixes #891.
Fixes #939.
1. Login to client, click on a source
2. Delete a single submission via the JI for that source
3. You should see the submission be deleted from the conversation view after sync
4. For good measure, try sending a reply from the JI and ensure it appears in the conversation view
**Precondition:** Submit a file as a source
1. Login to client, click on a source
2. Delete a single file via the JI for that source
3. You should see the file be deleted from the conversation view after sync
4. Now submit another file as a source
5. You should see the new file appear in the conversation view after sync
6. For good measure, try sending a reply from the JI and ensure it appears in the conversation view
7. For good measure, try sending a message from the source and ensure it …
=> app: fix conversation refresh/syncing

securedrop_client/api_jobs/downloads.py, securedrop_client/gui/widgets.py, securedrop_client/storage.py, tests/gui/test_widgets.py, tests/test_app.py, tests/test_storage.py
Fixes #892.
Given the importance of the deletion functionality, I recommend testing the following cases:
**_Precondition for each case:_** Via the source interface, create a source with at least one file. Log into the client and download the file.
1. Source is deleted by the local user. The entire source directory `~/.securedrop_client/data/intrusive_smattering` should be deleted. 
2. Source is deleted by another user (you can simulate this by deleting an entire source in the JI). The entire source directory `~/.securedrop_client/data/intrusive_smattering` should be deleted. 
3. An individual submission is deleted by another user (you can do this by deleting an individual submission in the JI). The file _and_ its enclosing folder should be deleted: …
=> ensure we delete individual submissions on disk

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #922.
Follow #922 STR. ~Note that the FileWidget may not be deleted automatically on sync. I believe that will be fixed by #937.~ Indeed it was. Everything should behave as you'd expect now.
=> Make sure snippet is updated on submission deletion

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/947
#947 is happening when a source that was deleted outside of the client is selected just after logging back in. When a source is selected, we check to see if it still exists in:
```py
def get_current_source(self):
source_item = self.currentItem()
source_widget = self.itemWidget(source_item)
if source_widget and source_exists(self.controller.session, source_widget.source.uuid):
return source_widget.source
```
But if it doesn't exist, then ` source_widget.source.uuid` will fail with the error you see in #899, which we're not catching. Since we only want to delete source widgets and their corresponding conversations in one place (in `show_sources` after a sync is successful), I modified …
=> use the id of the widget, not the db object

securedrop_client/logic.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/951
=> show pending status right after deletion job enqueued

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Small tweaks to dialogs for print/export. Final pre-beta portion of #53
=> Tweak print/export dialog texts per messages audit

run.sh
The cleanup function was busier than it needed to be, and because of the exec of the client, was never actually being invoked. This change:
- reworks cleanup to use `gpgconf --kill` to stop the agent
- invokes it explicitly before the client is run
- removes the exec so that `trap cleanup EXIT` works and cleanup happens after the client exits
Making sure gpg-agent is stopped should prevent any problems it might have if `GNUPGHOME` is pulled from under its feet between client runs.
This should make run.sh more robust when developers are mucking about with `SDC_HOME`.
We might consider adding similar agent cleanup in production, but since `SDC_HOME` should be consistent and in normal usage should never be removed, the problems we've seen with the GPG agent should not arise in production …
=> Clean up cleanup in run.sh

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Towards https://github.com/freedomofpress/securedrop-client/issues/906 and minimizing access of database objects in the GUI.
1. Regression test the preview snippet
2. Review code to see that we no longer need to worry about source db object deletions in `set_snippet` because it no longer accesses `self.source.collection` or `self.source.uuid`
(Next step/PR is to make sure `update` doesn't raise an exception in the SourceWidget constructor.)
=> no longer access source db obj in snippet

securedrop_client/gui/widgets.py
Fixes #971.
Making the login widget modal is the *ideal* solution since this is precisely the use case for such modal dialogs. Let Qt do the work for you. ;-)
Please check with Eyeball Mk1. :eyes: Feedback from @ninavizz and @eloquence on possible UI change of behaviour.
=> Make the login modal, thus ensuring only one instance is possible at once.

securedrop_client/api_jobs/downloads.py, securedrop_client/app.py, securedrop_client/config.py, securedrop_client/db.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_logic.py
Towards https://github.com/freedomofpress/securedrop-workstation/issues/397
There's also some logging in `securedrop-export` that we'll want to remove (original filenames), I will do that separately 
=> logging audit

securedrop_client/gui/widgets.py, tests/functional/cassettes/test_download_file.yaml, tests/functional/cassettes/test_export_dialog.yaml, tests/functional/test_download_file.py, tests/functional/test_export_dialog.py
Adds two new functional tests, one is for downloading a file.
And the second is for export dialog.
=> Adds more functional tests for the client

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Towards #285.
Screenie of modified behaviour:
Took a while to work out the simplest / easiest approach. But in the end I just created a child class from QLabel which emitted click events and connected the emitted click to the button with the menu.
Added unit test.
=> Adjust the clickable area for logging out to include the user's icon.

securedrop_client/api_jobs/updatestar.py, securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/api_jobs/test_updatestar.py, tests/functional/test_star_source.py, tests/functional/test_unstar_source.py, tests/gui/test_init.py, tests/gui/test_widgets.py, tests/test_logic.py
WIP until I update unit tests and write a test plan.
Fixes https://github.com/freedomofpress/securedrop-client/issues/946
Resolves https://github.com/freedomofpress/securedrop-client/issues/760
Closes https://github.com/freedomofpress/securedrop-client/issues/811
Fixes https://github.com/freedomofpress/securedrop-client/issues/954
This fixes the crash reported in #946, resolves #760 and part of #954 by no longer updating sources whenever a source is starred, closes #811 by retrying star jobs that fail due to timeout, and fixes the rest of #954 so that stars are updated immediately and only toggle back at the same time an error is displayed that says "Failed to update star" or when a star is updated on the server. This also removed the extra callback that toggled stars unpredictably given …
=> Fix starring behavior

securedrop_client/api_jobs/sources.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/api_jobs/test_sources.py, tests/gui/test_widgets.py, tests/test_logic.py
Fixes #966.
0. First add to the source deletion server API endpoint (above [this](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/journalist_app/api.py#L149) line): 
```
+            early_fail = random.choice([True, False])
+            if early_fail:
+                abort(404)
```
such that you get failures half the time.
1. Delete a source locally.
2. Upon deletion success, the pending status works as expected: the pending status is shown and the source disappears from the UI.
3. Upon deletion failure (_not_ due to timeouts), an error message is shown, the pending status is removed from both the `SourceWidget` in the source list and the conversation wrapper. 
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the …
=> app: reset source pending status upon unexpected source deletion at server

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #116.
This is a UI layer solution for the purpose of the beta to resolve the above issue where multiple clicks result in attempting to download a file multiple times (see `prevent-duplicate-jobs` for a generic approach for ensuring duplicate jobs in general cannot be added to the queue).
0. Submit a file as a source.
1. Sign into the client with debug level logging (`LOGLEVEL=DEBUG ./run.sh`), attempt to download the file.
2. While it is downloading (note: for test purposes you should submit a large file that takes some time to download OR add a `time.sleep(2)` in the submission download endpoint server-side), keep clicking.
3. Ensure that no additional jobs are added. 
You should see the following line only once. indicating that duplicated clicks did not result in duplicate …
=> app: prevent duplicate file downloads at the UI level

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Replace `SourceList.get_current_source` with `SourceList.get_selected_source`. `QListWidget.currentItem()` returns something even if no item has been selected, which is not what we want when deciding whether to populate the conversation view after sync.
Fixes #962.
- Start the client. Don't touch nothin'.
- Wait through a sync.
- No source should be selected after the sync; the empty conversation view with instructions should still be shown.
If these changes add or remove files other …
=> Stop selecting a source on sync

securedrop_client/gui/widgets.py
Fixes #932.
I use the `FontMetric` instance on the `status_bar` object to set the new minimum width, then reformat to dynamically adjust the width.
Screenie:
Eyeball Mk1 to ensure the UI changes take effect as expected. :eyes:
=> Automatically resizes status bar to width of error message string.

tests/functional/cassettes/test_login_from_offline.yaml, tests/functional/test_login_from_offline.py
Fixes #980
It first logs in, and then logsout, and then log in again.
=> Adds new functional test to login from offline mode

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/826
=> show frame and make dialogs modals

securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/storage.py, tests/functional/test_download_file.py, tests/functional/test_export_dialog.py, tests/gui/test_widgets.py, tests/test_storage.py
Fixes #917
This still needs unit test case. I need help with that
Follow the steps from #917
=> Updates the filesize after download and decryption

securedrop_client/gui/widgets.py
Switches the order of the "Continue" and "Cancel" buttons so that the "Continue" button is on the right side.
=> switch button order

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/993
1. Export and continue until you reach the passphrase field and make sure it's selected by default.
=> focus passphrase field

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py
Allow `SecureQLabel` to disable tooltips via the `with_tooltip` constructor argument, which if `False` will prevent tooltips being automatically set for the `SecureQLabel` when its `setText` method is called.
Set `with_tooltip=False` on `SourceWidget`'s preview `SecureQLabel` so that no tooltip appears when hovering over it.
Fixes #999.
- Check out this branch.
- Run the client. 
- Verify that hovering over the preview labels in the source list does not produce any tooltips.
- Upload a file with a very long name, download it in the client, and ensure that:
- its name is truncated in the conversation view
- its full name is shown in a tooltip if you hover over it
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, …
=> Prevent tooltips on source preview labels

securedrop_client/gui/widgets.py
Fixes #985
Towards #986
This PR fixes the above two issues to the extent that Erik has described the expected initial solution (todo: hover background).
Screenie here:
Eyeball Mk.1 :eyes:
=> Fix star hover state

securedrop_client/db.py, securedrop_client/gui/widgets.py, tests/gui/test_widgets.py, tests/test_models.py
Fixes #997. The previews should show activity from the server only (cc @ninavizz), that is successful replies, and activity from the source. 
0. Add to below [this line](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/journalist_app/api.py#L231) in the server endpoint:
```diff
+            early_fail = random.choice([True, False])
+            if early_fail:
+                abort(404)
```
1. Submit replies until one fails.
2. Verify that the preview snippet does not contain the text of the failed reply. 
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes …
=> app: do not show drafts in preview

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/992
If you're not in Qubes:
1. apply this diff:
```diff
--- a/securedrop_client/logic.py
+++ b/securedrop_client/logic.py
@@ -727,7 +727,8 @@ class Controller(QObject):
return
if not self.qubes:
-            self.export.export_usb_call_success.emit()
+            import threading
+            threading.Timer(4, lambda: self.export.export_usb_call_success.emit()).start()
return
self.export.begin_usb_export.emit([file_location], passphrase)
(END)
```
2. Export a file and see the cancel button disabled until it succeeds.
3. Also emit a failure signal and see the cancel button reenable.
Otherwise, just export a file in Qubes and test both cases.
If these changes modify code paths involving cryptography, the opening of files in …
=> disable the cancel button right before we export the file

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Tooltips are only needed in the conversation view for long filenames that get truncated.
Fixes #1015.
Start the client. Confirm that tooltips are not shown for the preview snippets in the source list, or any content in the conversation view except for long filenames that need to be truncated. You'll need to upload a document with a long filename to test that.
If these changes add or remove files other than client code, packaging logic (e.g., the AppArmor profile) may need to be …
=> Revert the addition of tooltips to most SecureQLabel occurrences

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes #914.
Ensure the widgets are ordered by timestamp on update in the source list. Screenie of the behaviour:
Implementation of this was interesting. I was quite a way through doing something in the `update` method since the `sources` list passed into the method is in the correct order. However, I took a detour and wondered if Qt had some way to order widgets in a QListWidget. Turns out that it does and so I went for this far simpler code. Also, this will be a faster ordering since the ordering is being done in the Qt (C++) level rather than in pure Python.
Updated the unit tests to patch the new `SourceListWidgetItem` class. Eyeball Mk.1 to ensure the order is correct (see screenie). :eyes:
If these changes modify code paths involving cryptography, the opening of files in VMs or …
=> Re-order widgets in the SourceList on update.

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/998#issuecomment-606310514
Fixes https://github.com/freedomofpress/securedrop-client/issues/694
Also download icon is no longer misaligned
Fixes https://github.com/freedomofpress/securedrop-client/issues/953
=> Fix truncation and alignment issues in conversation view

securedrop_client/storage.py, securedrop_client/utils.py, tests/api_jobs/test_sync.py
Adds a context manager that logs its block's execution time, and uses it in `storage.update_local_storage`.
Run the SD core dev server. Run the client with `LOGLEVEL=debug`, and after it completes the first sync, grep for `duration` in the log to ensure it contains measurements of the functions called in `update_local_storage`.
=> Add utils.chronometer for measuring block execution time

Makefile, dev-requirements.in, dev-requirements.txt, requirements.txt
Also adds `--verbose`, `--rebuild`, and `--annotate` to `pip-compile` arguments in `update-pip-requirements` Makefile target.
Fixes #1039 .
Verify that CI is no longer broken by safety pointing out the problem with pyyaml.
=> Update pyyaml to 5.3.1

securedrop_client/api_jobs/sync.py, securedrop_client/crypto.py, securedrop_client/storage.py, securedrop_client/sync.py, tests/api_jobs/test_sync.py, tests/factory.py, tests/test_crypto.py, tests/test_storage.py
Stop importing source GPG keys during sync. We have a place on Source to store fingerprint and key, which is all we need for the import, and which is what we check when deciding whether to enable the reply box, so let's just update the database here and defer import to the keyring until someone actually wants to reply. It takes milliseconds that won't be noticed then, but do add up during sync.
This is based on and should be reviewed after #1034.
Run the SD core dev server. Run the client with `run.sh` and a fresh data directory. Ensure that you can still reply to sources. If you can, then deferring the key import until replying is working.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the …
=> Defer source key import

securedrop_client/storage.py, tests/test_storage.py
Avoid dirtying synced objects on update unless they've actually changed, and reduce the number of commits.
This is based on and should be reviewed after #1035.
Run the SD core dev server. Ensure that syncing completes, that the source list and conversation view populate correctly, and that you can reply to sources.
=> Minimize sync db work

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1033
Must be seen on Qubes because it looked fine on Debian.
=> align file name and PRINT button

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/987
See that journalist designation and preview are aligned
=> align source name and preview

securedrop_client/storage.py, tests/test_storage.py
Retrieving submissions and replies for the most recently active sources first will make the initial sync feel faster, as the visible part of the source list is updated first, and will make it possible to for journalists to work with what are likely the most interesting sources sooner.
Fixes #1042.
Fixes #883.
- Check out this branch.
- Run the dev server with NUM_SOURCES=20.
- Start the client. The sources at the top of the list should have their messages and replies populated first. You should be able to see the progress of the sync as it works down through the source list (unfortunately, retrieving the individual submissions and replies is still that slow).
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, …
=> When finding new files/messages/replies, work back in time

securedrop_client/storage.py, securedrop_client/utils.py, tests/test_storage.py
Reduce the number of database queries during sync: cache sources or journalists instead of looking them up for each incoming object associated with them.
Use maps instead of sets to hold local objects in the `update_` functions, so it's faster to check if we already have a record of incoming objects.
This is based on and should be reviewed after #1036.
Run the SD core dev server. Ensure that syncing completes, that the source list and conversation view populate correctly, and that you can reply to sources.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please …
=> Minimize sync lookups

securedrop_client/api_jobs/uploads.py, securedrop_client/storage.py, securedrop_client/utils.py, tests/test_storage.py
A bit more progress toward #1009.
- Run the dev server with 1000 sources.
- Check out this branch and run the client. 
- Ensure that syncing completes, that the source list and conversation view populate correctly, and that you can reply to sources. If you `grep duration` in the client log, `update_replies` should take around 2.5 seconds on this branch, compared to just over three on the `minimize_sync_lookups` branch upon which this is based.
If these changes add or remove files other …
=> Speed update replies

securedrop_client/api_jobs/sync.py
We are increasing the qrexec subprocess timeout for `get_sources`, `get_all_submissions`, and `get_all_replies` from 40 to 60 while we continue to investigate workstation performance.
I also think it would make sense to decrease the number of retries to 1 so that we can inform the user of a connection issue after 2 minutes instead of 3. I can add that to here if others agree.
Make sure there are no regressions.
If these changes add or remove files other than client code, the AppArmor …
=> increase sync timeout

securedrop_client/api_jobs/sources.py, securedrop_client/api_jobs/updatestar.py, securedrop_client/api_jobs/uploads.py
Increase the timeouts to rely on the sdk's default of 20 seconds for any requests that we agressively killed after 5 seconds until we gather more staging/prod data on how long each request takes, see https://github.com/freedomofpress/securedrop-client/issues/648. We also are continuing to discuss the value of increasing the timeout each time a job retries until it runs out of retries.
|Endpoint|SDK subprocess timeout|
|:-|-:|
|`get_sources`| 60 |
|`get_all_replies`| 60 |
|`get_all_submissions`| 60 |
|`reply_source`| 20 |
|`add_star`| 20 |
|`remove_star`| 20 |
|`delete_source`| 20 |
|`authenticate`| 60 |
|`logout`| 60 |
Make sure there are no regressions.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes …
=> rely on sdk default for most requests

securedrop_client/gui/widgets.py
Fixes #1052. 
Previously when adding text selectability to `QLabel`/`SecureQLabel` the application crashed with a segfault. After investigation this was due to [an upstream bug](https://bugreports.qt.io/browse/QTBUG-69204) that is fixed in qt 5.12.x but not in qt 5.11.x which we are currently using. There is a workaround (22e1b34) to handle this case until we are on a more recent version of qt. 
If these changes add or remove files other than client code, the AppArmor profile may need …
=> app: make QLabel text selectable

securedrop_client/api_jobs/downloads.py
Fixes #1060. The changes in #965 switched to the wrong variable to get the folder name, so that we ended up logging empty strings instead of the intended (journalist designation) folders.
1. Start the client from this branch (dev env should be fine) and sync with a server environment
2. - [ ] Observe that the logs for messages, replies and files no longer exhibit the behavior described in #1060, and the folder names are correct 
3. - [ ] Observe that the logs do not include sensitive original filenames (e.g., an uploaded file `moscow.avi` should not appear in the logs under that name after the file is downloaded in the client)
=> Log intended folders instead of empty strings

securedrop_client/gui/main.py, securedrop_client/logic.py, tests/gui/test_main.py, tests/test_logic.py
Fixes #1051 by clearing the system clipboard contents after logging into online or offline mode.
- Run the client from this branch, preferably in Qubes
- While the login screen is displayed, copy some string into the clipboard, e.g., "asdf" or your password
- Log into the client
- Run the client from this branch, preferably in Qubes
- Copy some string into the clipboard, e.g., "asdf"
- Click the offline mode option
=> Clear clipboard after login screen

tests/conftest.py, tests/functional/test_delete_source.py, tests/functional/test_download_file.py, tests/functional/test_export_dialog.py, tests/functional/test_login.py, tests/functional/test_login_from_offline.py, tests/functional/test_logout.py, tests/functional/test_offline_delete_source.py, tests/functional/test_offline_read_conversations.py, tests/functional/test_offline_send_reply.py, tests/functional/test_offline_star_source.py, tests/functional/test_receive_message.py, tests/functional/test_send_reply.py, tests/functional/test_star_source.py, tests/functional/test_unstar_source.py
Test only, addresses my comment [here](https://github.com/freedomofpress/securedrop-client/pull/1022#discussion_r404871812)
=> functional tests: use named constants for wait times

securedrop_client/api_jobs/base.py, securedrop_client/api_jobs/downloads.py, securedrop_client/crypto.py, securedrop_client/logic.py, tests/api_jobs/test_downloads.py, tests/test_logic.py
Clean up noisy logs around decryption errors: https://github.com/freedomofpress/securedrop-client/pull/1083#issuecomment-625668989
```
2020-05-08 16:57:36,949 - securedrop_client.api_jobs.downloads:167(_download) INFO: File downloaded to /home/creviera/.securedrop_client/data/unlike_canvas/1-unlike_canvas-msg.txt
2020-05-08 16:57:36,957 - securedrop_client.crypto:112(decrypt_submission_or_reply) ERROR: GPG Error: gpg: encrypted with RSA key, ID C3E7C4C0A2201B2A
gpg: decryption failed: No secret key
2020-05-08 16:57:36,957 - securedrop_client.api_jobs.downloads:343(call_decrypt) WARNING: Error deleting decryption directory of message 4fe17e03-8196-4700-9d40-a41164cbeb90: [Errno 39] Directory not empty: '/home/creviera/.securedrop_client/data/unlike_canvas'
2020-05-08 16:57:36,979 - …
```
=> Cryptoerror logs

securedrop_client/storage.py, tests/gui/test_widgets.py, tests/test_storage.py
It was missing from the list of attributes updated on existing sources during sync, so a source which had no key when first synced would never be completed, even once the keypair were generated on the server, and journalists would never be able to reply to them.
Fixes #1091.
Tough to test manually, as the failure is dependent on a new source being synced before having its keypair generated. 
If these changes add or remove files other than client code, the AppArmor profile may need to …
=> Make sure source fingerprint is updated on sync

Makefile, securedrop_client/app.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/resources/css/file_download_button.css, securedrop_client/resources/css/modal_dialog_button.css, securedrop_client/resources/css/modal_dialog_error_details.css, securedrop_client/resources/css/reply_message.css, securedrop_client/resources/css/reply_status_bar.css, securedrop_client/resources/css/sdclient.css, securedrop_client/resources/css/speech_bubble_message.css, securedrop_client/resources/css/speech_bubble_status_bar.css, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/integration/conftest.py, tests/integration/test_placeholder.py, tests/integration/test_styles_file_download_button.py, tests/integration/test_styles_modal_dialog_button.py, tests/integration/test_styles_modal_dialog_error_details.py, tests/integration/test_styles_reply_message.py, tests/integration/test_styles_reply_status_bar.py, tests/integration/test_styles_sdclient.py, tests/integration/test_styles_speech_bubble_message.py, tests/integration/test_styles_speech_bubble_status_bar.py, tests/test_app.py
Towards https://github.com/freedomofpress/securedrop-client/issues/1078
Goals behind this PR:
* Start using `.css` files instead of strings or dictionaries of strings or dictionaries of dictionaries of strings
* Separate css stylesheets from Qt application logic
* Use standard CSS object names that correspond to Qt Widget class names
* Set the stylesheet for the application once, except for when we need to change the CSS of an object based on an action.
* Add integration tests to make sure the styles are what we expect
* Add regression tests to make sure if a class name changes then the CSS object name needs to be updated and vice versa
There are many integration tests that you'll see check to see that the widget styles are what we expect them to be. We are almost at 100% UI style …
=> Move CSS to CSS files and add new tests for stylesheets

securedrop_client/gui/widgets.py, tests/functional/test_delete_source.py, tests/functional/test_download_file.py, tests/functional/test_export_dialog.py, tests/functional/test_offline_delete_source.py, tests/functional/test_offline_read_conversations.py, tests/functional/test_offline_send_reply.py, tests/functional/test_offline_star_source.py, tests/functional/test_receive_message.py, tests/functional/test_send_reply.py, tests/functional/test_star_source.py, tests/functional/test_unstar_source.py, tests/gui/test_widgets.py
* Fixes https://github.com/freedomofpress/securedrop-client/issues/1113
* Fixes issue 8 documented here: https://github.com/freedomofpress/securedrop-client/issues/906#issuecomment-601410639
* Fixes https://github.com/freedomofpress/securedrop-client/issues/1116
* No STR for the second half
* Fixes issue 1 documented here: https://github.com/freedomofpress/securedrop-client/issues/906#issuecomment-601410639
* Fixes https://github.com/freedomofpress/securedrop-client/issues/1117
* No STR for the second half
* While working on this fix, a side effect/refactor I made was to no longer delete widgets on behalf of a different ongoing sync running on a separate thread since the ongoing sync will delete the widgets shortly after.
* Verify …
=> delete source widgets for current sync update

securedrop_client/api_jobs/downloads.py, securedrop_client/config.py, securedrop_client/export.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/resources/css/reply_message.css, securedrop_client/resources/css/sdclient.css, securedrop_client/resources/css/speech_bubble_message.css, setup.py, tests/api_jobs/test_downloads.py, tests/api_jobs/test_sync.py, tests/api_jobs/test_uploads.py, tests/conftest.py, tests/factory.py, tests/gui/test_widgets.py, tests/integration/test_styles_reply_message.py, tests/integration/test_styles_sdclient.py, tests/integration/test_styles_speech_bubble_message.py, tests/test_app.py, tests/test_export.py, tests/test_logic.py, tests/test_storage.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1074, see what it currently looks like:
This PR makes it so the client fits within a 1280x1024 screen when it opens and adds support for a small variation in size in the sourcelist when you change the window size.
Also small fix to the sign-in button so that it no longer does this when you shrink the client to its smallest height. This is what it used to look like:
Known issues that need to be addressed as follow-up or as part of this PR:
* journalist designations vary in size and sometimes don't fit within the smaller window with the current font size, see how the journalist designation gets cut off in the conversation header and reply box:
* speech bubbles don't yet vary in size, so you'll have to horizontal scroll, but my …
=> reduce minimum size

.github/pull_request_template.md, README.md
Fixes #1122 
Docs changes only
=> Update references to default branch in docs

securedrop_client/gui/main.py, tests/gui/test_main.py
Signed-off-by: Allie Crevier <allie@freedom.press>
Fixes https://github.com/freedomofpress/securedrop-client/issues/1109
1. Test with one monitor in Qubes
2. Test with multiple monitors in Qubes
=> fix fullscreen in qubes

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1121
1. Run through STR in issue that this fixes and verify that expected state is what happens now
2. Send a new message from the SI and see that it gets displayed in the preview
---
Once tests are written, I will move this out of a draft PR state
=> Only show a preview if its the *last* message/file/reply for a source

securedrop_client/gui/main.py, tests/gui/test_main.py
Qubick off-sprint PR to no longer start the client in fullscreen.
=> do not start fullscreen in nonqubes

securedrop_client/api_jobs/sync.py, tests/api_jobs/test_sync.py, tests/functional/cassettes/test_delete_source.yaml, tests/functional/cassettes/test_download_file.yaml, tests/functional/cassettes/test_export_dialog.yaml, tests/functional/cassettes/test_login_as_journalist.yaml, tests/functional/cassettes/test_login_from_offline.yaml, tests/functional/cassettes/test_logout_as_journalist.yaml, tests/functional/cassettes/test_offline_delete_source_attempt.yaml, tests/functional/cassettes/test_offline_read_conversation.yaml, tests/functional/cassettes/test_offline_send_reply_to_source.yaml, tests/functional/cassettes/test_offline_star_source.yaml, tests/functional/cassettes/test_receive_message_from_source.yaml, tests/functional/cassettes/test_send_reply_to_source.yaml, tests/functional/cassettes/test_star_source.yaml, tests/functional/cassettes/test_user_icon_click.yaml
Towards https://github.com/freedomofpress/securedrop-client/issues/76
Next step (after this PR): update gui auth widget to show updated name
1. log in
2. change first and last name of the account you're logged into from the admin UI
3. wait until next sync then check local client db
4. change first and last name to empty string
5. wait until next sync then check local client db
6. change first and last name from journalist UI (not admin UI)
7. wait until next sync then check local client db
8. change username from admin UI (can't do this from journalist UI)
=> update current user info during sync

README.md
Remove reference to old TOTP code and update README around functional testing.
=> update test docs

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
Resolves #1120
Elides the source designation if needed as the window is resized, while allocating a fixed width to the label to ensure that layout is not disrupted.
- Test resizing the window on Qubes for multiple sources to ensure it behaves as shown in the GIF animation below.
- Test switching to offline mode and back to online mode to ensure no regression in the placeholder display.
- Test sending replies from multiple sources to ensure no regression in placeholder hide/show behavior.
=> Elide source designation at lower window widths

securedrop_client/api_jobs/uploads.py, securedrop_client/logic.py, tests/api_jobs/test_uploads.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1148
When creating a Reply object, journalist_id needs to match the id of the authenticated user, not the uuid supplied in the token. There is ongoing work around how we manage authentication so this PR provides a minimal solution. 
1. Send succesful, pending, and failed replies (you can apply these diffs to simulate failed and pending replies: https://gist.github.com/creviera/7f19a7d10334359f40dbdbb2354cd13a, https://gist.github.com/creviera/5ba70d50c12b6a6df6f98ed40ad09645)
2. Check that sending replies still works
3. Log out and check that you cannot send a reply
4. Invalidate token and check that you cannot send a reply
1. Checkout `main` and send a successful reply, a failed reply, and pending reply (you can apply these …
=> pass id instead of uuid for journalist_id

files/sd-app-qubes-gpg-domain.sh, files/securedrop-client, files/usr.bin.securedrop-client
Fixes #1141 
Towards https://github.com/freedomofpress/securedrop-workstation/issues/471
Install this package in sd-app-buster-template.
-  [ ] The client does not start in sd-app-buster-template TemplateVM (you can also try installing it in other VMs)
=> Disable client and vault config in VMs other than sd-app

files/sd-app-qubes-gpg-domain.sh
Towards https://github.com/freedomofpress/securedrop-workstation/issues/621
Changes in #1153 required changes to the AppArmor profile. In order to apply these changes prior to running the client, running aa-enforce was required to ensure the profile was updated prior to running the client. We should instead handle this in the postinst for this package.
See test plan in https://github.com/freedomofpress/securedrop-workstation/pull/623
If these changes add or remove files other than …
=> Remove AppArmor profile enforcement in profile.d, into postinst

README.md
This was recommended to reduce migration run time by reducing the number of times data had to be transferred between tables. If someone is on an old version of the client and has a lot of data, it does make sense that combining the schema migrations and then doing one single data migration would save time, however it's harder to maintain and reason about the merged migration. It's probably worth the extra time to keep these migrations logically separate, and in the average case, there isn't any performance gain anyway.
=> remove recommendation to merge migrations

alembic/versions/a4bf1f58ce69_fix_journalist_association_in_replies.py, tests/migrations/test_a4bf1f58ce69.py, tests/migrations/utils.py, tests/test_alembic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1149
Fixes https://github.com/freedomofpress/securedrop-client/issues/1068
1. `rm -r /tmp/sdc-*`
2. `TESTS=tests/test_alembic.py::test_alembic_migration_upgrade_with_data make test `
3. `sqlite3 /tmp/sdc-<random-string>/svs.sqlite`
4. repeat steps above but for the downgrade test
=> add data migration testing and fix journalist association in replies table

alembic/versions/bd57477f19a2_add_seen_tables.py, securedrop_client/db.py, tests/migrations/test_bd57477f19a2.py, tests/migrations/utils.py, tests/test_alembic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1163
(In draft mode until https://github.com/freedomofpress/securedrop-client/pull/1162 is merged)
1. `rm -r /tmp/sdc-*`
2. `TESTS=tests/test_alembic.py::test_alembic_migration_upgrade_with_data make test `
3. `sqlite3 /tmp/sdc-<random-string>/svs.sqlite`
4. repeat steps 1-2 above but for the downgrade test
=> Add seen tables

alembic/versions/a4bf1f58ce69_fix_journalist_association_in_replies.py, tests/migrations/test_a4bf1f58ce69.py, tests/migrations/utils.py
(cherry picked from commit 824e0a2c1fe147ca25f66455aecef953a4a05f92)
Fixes #1185, backport changes from #1184
=> Fix journalist association bug in draftreplies

requirements/dev-mac-requirements.txt
Related to https://github.com/freedomofpress/securedrop-client/pull/1172 , some requirements were dropped from the requirements file due to lack of access to a mac computer.
=> Update dev mac requirements

securedrop_client/gui/main.py, tests/gui/test_main.py
Fixes  issue with maximizing the window when switching between offline and online mode.
1. start the client in offline mode and change the main window size
2. sign in from the user auth menu
3. sign out form the user auth mentu
4. close the client and log in
This needs to be tested in Qubes.
=> only maximize if window not already displayed

securedrop_client/gui/widgets.py, securedrop_client/resources/css/sdclient.css, securedrop_client/resources/css/source_name.css, securedrop_client/resources/css/source_preview.css, securedrop_client/resources/css/speech_bubble_message.css, securedrop_client/resources/images/paperclip.svg, tests/gui/test_widgets.py, tests/integration/test_styles_sdclient.py
Resolves https://github.com/freedomofpress/securedrop-client/issues/1174
1. Log into the client select sources and see source name turn blue when selected
2. Log out and verify the same behavior ^
3. Compare layout to https://scene.zeplin.io/project/5c807ea562f734bd2756b243/screen/5f35fbb85de1037e11c88dab or the image in #1174 (make sure it's zoomed out to 100% to match the client size)
=> Source widget ui polish

securedrop_client/db.py, securedrop_client/storage.py, tests/gui/test_widgets.py, tests/test_storage.py
Towards #1189 
Fixes issue caught here during QA:
> Global read/unread
>    - :x: A source shows up as read (not bold) when someone other than the logged-in user has read the source from the web JI
* See the regression tests adding to this PR fail on `main` but succeed on the PR branch.
* See that both STRs [reported by @eloquence during QA](https://github.com/freedomofpress/securedrop-client/issues/1189#issuecomment-741423671) are fixed:
1. Download all submissions of an unseen source via the JI as a user who has _never sent a reply_
The source is no longer bold in the source list of the client
The source remains bold
1. Set `downloaded` to `1` for a message of an unseen source on the server db - make sure no seen records exist for this message.
2. Download all submissions of the unseen …
=> Client 0.4.0 qa bug fix

securedrop_client/logic.py
Fixes issue reported during QA by @eloquence:
> *However, note that when going online, I have to wait until the next sync for the change to be correct again.*
Log into the client
For the client to immediately display sources as seen/unseen according to what's in the local db
The client displays the sources as all seen until the first sync completes
(Also test by starting off in offline mode then switching to online mode. And test once more by logging out and logging back in - do not close the client.)
Test the the STRs above are now seeing the expected state.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, …
=> set is_authenticated first on login success

requirements/dev-mac-requirements.txt, requirements/dev-requirements.in, requirements/dev-requirements.txt
- Updates py to >= 1.10.0 to address CVE-2020-29651
- Updates pip-tools to 5.5.0 to address issues with pip-compile
- Other changes should be limited to formatting output due to newer version of pip-tools
- Dependency changes are dev-only.
=> Update py to 1.10.0 for dev dependencies dependencies

securedrop_client/gui/__init__.py, securedrop_client/gui/widgets.py, securedrop_client/resources/css/sdclient.css, tests/gui/test_widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1207
Towards scalable client
Merge before https://github.com/freedomofpress/securedrop-client/pull/1206
Known issue: #815
1. Run the client against a server with some sources
2. Log in
3. Select a source and resize the client window, try double clicking and resizing to the smallest width and height
4. Replace existing sources with 200 new sources while still logged in
5. Log out
6. Close client and log in in offline mode
7. Log in, restart the server with new sources, wait until the client picks up the new sources and creates new source widgets while logged in
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging …
=>  scale source list and preview as window resizes

run.sh
Fixes #1214.
- `make venv`
- `. .venv/bin/activate`
- `./run.sh`
The client should start.
=> Remove obsolete MIME setup in run.sh

securedrop_client/gui/widgets.py
Fixes #1217 
Must be tested in Qubes or with local modifications, as clicking files in a development environment will have no effect.
1. Run the SecureDrop client from this branch
2. Connect to a server with file submissions
3. Download a file submission and attempt to open it
4. Resize the client window to its minimum size
5. Observe that #1061 and #1204 are still fixed and that there are no regressions in resize behavior.
=> Prevent event handler from being triggered twice

securedrop_client/gui/widgets.py, securedrop_client/resources/css/sdclient.css, securedrop_client/resources/images/left_pane.svg, securedrop_client/resources/images/left_pane_offline.svg, tests/integration/test_styles_sdclient.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1209
=> stretch background of left pane

alembic/env.py
Our virtualenv is based on Python 3.7, so this path does not in fact exist on the `sd-app` VM.
Note that this is an informational finding from the 2020 SecureDrop Workstation audit (`TOB-SDW-013`). Per the finding, the correct path already exists in `sys.path` at the time the incorrect path is inserted.
1. Build a package from this branch and install it in `sd-app`
2. Initialize a fresh `.securedrop_client` directory in `sd-app`
3. Observe that migrations are still correctly applied
=> Remove nonexistent Python 3.5 path

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1240
1. Export a file, any file, just press the Enter key (instead of clicking the Continue button) after typing in the password to unlock your luks-encrypted export device.
2. See that the file is no longer exported twice
Review issue #1240 and see if there are other ways to trigger a double export.
=> fix exporting twice on pressing the Enter key

CONTRIBUTING.md, README.md
Update description of project, add a CONTRIBUTING.md file and info on how to get help, and update CI project links.
Make sure links work and review language for spelling, grammar, accuracy, curse words, etc.
=> Add CONTRIBUTING.md and update CI integration links

tests/factory.py, tests/test_storage.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1247
Confirm that https://github.com/freedomofpress/securedrop-client/issues/1247 is fixed when testing locally.
=> fix flaky integrity errors during test

README.md
[Readme only] Just updating with more info about why we use `xvfb` and to run tests without it.
=> add more docs on xvfb usage

securedrop_client/utils.py
Resolves https://github.com/freedomofpress/securedrop-client/issues/1227
Also first review and merge: https://github.com/freedomofpress/securedrop-export/pull/74
=> make relpath traversal check clearer

Makefile
Use `TESTOPTS` to improve readability.
Run semgrep in `make test` and `make test-random` which means we run semgrep in CI.
=> improve readability of test targets

securedrop_client/gui/widgets.py
**Summary**: Prevents a Qt warning from being printed to stderr when selecting each source from the list of sources for the first time. As far as I can tell, the TAB order was properly applied anyway, but it was an opportunity for me to start reading Qt code.
**Reproduction steps**
0. Checkout the `main` branch
1. Run the client: `./run.sh`
2. Log in (for example as `journalist`)
3. Select one or more sources from the list of sources
4. Observe that the following warning is printed to stderr the first time each source is selected:
```
QWidget::setTabOrder: 'first' and 'second' must be in the same window
```
**Explanation**
The TAB order only makes sense when two widgets belong to the same parent. Because `QWidget::setTabOrder` only receives the widgets themselves as parameters, it relies …
=> Minor fix Qt TAB order warning

.circleci/config.yml
Adds a **Run lint** jobs to the CI pipeline, to make it easier to spot linting issues.
- I added the job to the `test-buster` group to take advantage of the fact that dependencies need to be installed for testing purposes.
- **Trade-off**: while a separate `lint-buster` group could run concurrently, I don't like much the idea of spending CPU cycles downloading and installing dependencies too often. YMMV
- I added the job _after_ **Run tests**, because I'd likely fix the test suite first, then lint the code.
- Note that on the other hand, linting is significantly faster than running the test suite. Depending on how automated code formatting / import sorting is in people's editors, it may be nicer to fail fast.
- I added the checks in the order they were run in `make check`.
Fixes …
=> Add CI job to make easier to spot linting issues

securedrop_client/logic.py, securedrop_client/sync.py, tests/test_sync.py
When we have confirmation that a conversation or source was successfully deleted on the server, schedule an immediate sync to get the change reflected in the UI as soon as possible.
Run the client. Watch the logs. Verify that:
=> Introduce immediate sync upon source/conversation deletion

README.md
We've replaced pypi.securedrop.org with an LFS repo. Update README accordingly.
=> pypi.securedrop.org is no more

securedrop_client/db.py, securedrop_client/logic.py, tests/test_logic.py
Fixes #1291 
Follow-up to [0]. The original intention was to remove perms for
group/other, which was accomplished, but we inadvertently added an
executable bit on these files, which shouldn't be there.
There are still a few 644-mode files created by the tests, but I consider these artifacts of the testing logic and not representative of behavior in prod. You can see yourself with:
```
$ find -s /tmp -type d -name 'sdc-*' | xargs -r rm -r # to make sure there are no old tmpdirs polluting results
$ make test
$ find /tmp -type f -iname 'svs.sqlite' | xargs stat -c %a | sort | uniq -c
108 600
178 644
$ find /tmp -type f -iname 'sync_flag' | xargs stat -c %a | sort | uniq -c
3 600
2 644
```
Use the find/grep commands above and ensure you see zero 700-mode files. I don't think it's necessary to …
=> Update db/flag perms 700 -> 600

securedrop_client/gui/widgets.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1286
As followup, instead of hiding text in the replybox when a conversation is being deleted, we can show the text as disabled. We can continue conversation about this as needed here: https://github.com/freedomofpress/securedrop-client/issues/1303
1. using the `venv-debian` virtual environment, run the client (or package the client from this PR branch and install it in `sd-app`)
2. apply this diff to make testing easier: https://gist.github.com/creviera/8ed991737752a35785033ceac903d878
3. delete all files and messages for a source
- the replybox does not show a white textarea 
- you cannot type into the replybox and send replies during the deletion operation
If these changes modify code paths involving cryptography, the …
=> hide ReplyTextEdit when deletion of conversation in progress

.github/workflows/l10n.yml
Towards #1302.  After freedomofpress/infrastructure#3604, uses a GitHub personal access token belonging to a bot account allowed to push to `freedomofpress/securedrop-client@main`.
* **NB.**  The resulting `update-translation-catalogs` commit has been rebased out for this pull request.
- `l10n` GitHub Actions workflow succeeds on `main`: cannot be tested prior to merge *into* `main`.  :-(
=> uses repository secret `GH_TOKEN` for push privileges to `main`

securedrop_client/gui/widgets.py
Fixes #1289
1. Set up client with the following sources:
* Source with one file widget 
* Source with tear
* Source with tear followed by one file widget
* Source with tear followed by message or reply widget (for reference)
2. Now add lots of messages, replies, and/or files until you can scroll for each scenario above
If these changes modify the …
=> add more spacing between tear and other widgets

securedrop_client/gui/main.py
=> Fix remove inaccurate message when source is selected

securedrop_client/gui/__init__.py, securedrop_client/gui/buttons.py, securedrop_client/gui/widgets.py, securedrop_client/resources/css/button.css, securedrop_client/resources/css/sdclient.css, tests/gui/test_widgets.py, tests/integration/test_styles_sdclient.py
**Why now / motivation**: The UI code can be made simpler to work with by embracing the ways and features of the Qt framework. For example: the 90% of the accessibility of the app should come for free from using Qt in the ways it's intended to. (Like 90% of a website accessibility comes from the use of _semantic HTML markup_.) Because of that, following the thread of accessibility issues is a good way to identify and apply bite-sized refactoring to our widgets, and improve the maintainability of the code as well as the user experience.
The less time we need to spend thinking about _how_ the UI code works/fails, the more we can dedicate to _what_ our users need. The framework's job is precisely to help us with that, and I think investing into aligning the existing code to the framework …
=> Refactor LoginOfflineButton as QPushButton

Makefile, README.md
No longer tell developers to use `virtualenv` in the docs, and add a reminder to activate the virtual environment after running `make venv`. /cc @zenmonkeykstop 
Confirm no errors when using `make venv`.
=> add dev reminder to activate venv and update docs

securedrop_client/gui/login_dialog.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, tests/gui/test_widgets.py, tests/integration/test_styles_sdclient.py
Fixes #35
:warning: This PR introduces a new translatable string (`"Quit"`), and instructions will need to be given to the translators. Specifically, the string is not currently visible (there is no menu bar), but would be read out as an available action (to quit the application).
I extracted the `LoginDialog` class to it own file.
I'm introducing the Quit _user action_ as a `QAction` in a move to embrace Qt's framework because I'm convinced that will help us reason about the app.
If …
=> Allow users to quit the application using their keyboard

securedrop_client/gui/widgets.py, securedrop_client/resources/css/sender_icon.css
Adding a PyQt tool-tip to reply badges, displaying: first name/last name (or both, if provided), or username in the scenario that the full name has not been specified. A simple change in the tool-tip's display has also been added to the `sender_icon.css` file.
Fixes #1168 
1. Login as journalist via client. Ensure that the tool-tip displays the default username of the reply badges.
2. Configure the first name and last name in the web-based administration interface. Check that the tool-tip displays user's full name. 
3. Test scenarios in which the user has set only one credential (either first or last name) and ensure that the tool-tip displays either of them.
4. Login as dellsberg via client. Repeat steps 1 to 4.
5. Update journalist's credentials through the web-based administration …
=> Tooltip to reply badges1168

securedrop_client/gui/login_dialog.py, securedrop_client/gui/widgets.py
This is a pure refactoring (no user-facing effects). It is a follow up on https://github.com/freedomofpress/securedrop-client/pull/1339#discussion_r751674758.
Details in the commit message :slightly_smiling_face: 
Regression testing on #1339:
1. Launch the SecureDrop Client
2. In the login dialog, fill in the credentials
3. Press <kbd>Enter</kbd>
If …
=> Refactor simplify buttons creation in Login Dialog

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/gui/test_widgets.py, tests/test_logic.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1285
This is in draft mode to get feedback early while I work on adding an alembic migration test and confirm fix.
https://github.com/freedomofpress/securedrop-client/issues/1285 is fixed
If these changes modify the database schema, you should include a database migration. Please check as …
=> Prevent content from re-appearing after "Files and Messages" deletion

changelog.md
Towards https://github.com/freedomofpress/securedrop-client/issues/1275
=> append new 0.5.0 changes to changelog

README.md, securedrop_client/locale/messages.pot
Acouple minor readme changes, including no longer tracking list of supported features in the README, since this is better tracked externally, or in the workstation docs.
This also updates the `messages.pot` file after running `make extract-strings` to pick up strings, see https://github.com/freedomofpress/securedrop-client/pull/1348
=> Readme update

securedrop_client/gui/base/__init__.py, securedrop_client/gui/base/inputs.py, securedrop_client/gui/login_dialog.py, securedrop_client/gui/widgets.py, tests/gui/base/test_inputs.py, tests/gui/test_widgets.py
This is the third step to be split out of #1369.
It moves the `PasswordEdit` definition to its own file/module. Eventually, more form inputs could be extracted there, but for now there is only this one.
This step is necessary to prevent a circular dependency when extracting the `LoginDialog` out of `widgets.py`.
If these changes modify the database …
=> Refactor extract PasswordEdit to 'gui.base' namespace

securedrop_client/gui/auth/__init__.py, securedrop_client/gui/auth/sign_in/__init__.py, securedrop_client/gui/auth/sign_in/button.py, securedrop_client/gui/login_dialog.py, securedrop_client/gui/widgets.py
This is the fourth step to be split out of #1369.
It moves the `SignInButton` definition to its own file/module. Eventually, the `LoginDialog` will be part o the `auth` package too,.
This step is necessary to prevent a circular dependency when extracting the `LoginDialog` out of `widgets.py`.
If these changes modify the database schema, you should …
=> Refactor extract SignInButton to 'gui.auth.sign_in' namespace

securedrop_client/gui/auth/__init__.py, securedrop_client/gui/auth/sign_in/__init__.py, securedrop_client/gui/auth/sign_in/error_bar.css, securedrop_client/gui/auth/sign_in/error_bar.py, securedrop_client/gui/login_dialog.py, securedrop_client/gui/widgets.py, tests/gui/auth/sign_in/test_error_bar.py, tests/gui/test_widgets.py
This is the 5th step to be split out of #1369.
It moves the `LoginErrorBar` definition to its own file/module. Eventually, the `LoginDialog` will be part o the `auth` package too,.
This step is necessary to prevent a circular dependency when extracting the `LoginDialog` out of `widgets.py`.
If these changes modify the database schema, you should include …
=> Refactor extract LoginErrorBar to 'gui.auth.sign_in' namespace

securedrop_client/gui/auth/use_offline/__init__.py, securedrop_client/gui/auth/use_offline/button.py, securedrop_client/gui/login_dialog.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot
This is the 6th step to be split out of #1369.
It moves the `LoginOfflineLink` definition to its own file/module. Eventually, the `LoginDialog` will be part o the `auth` package too,.
This step is necessary to prevent a circular dependency when extracting the `LoginDialog` out of `widgets.py`.
If these changes modify the database schema, you should …
=> Refactor extract LoginOfflineLink to 'gui.auth.use_offline' namespace

securedrop_client/locale/messages.pot
The year gets updated automatically when the translatable strings are extracted.
This fixes the `main` build which nightlies started failing on Jan. 1st.
Visual review should be enough?
What do you think of `FIRST AUTHOR`, should we replace it by something meaningful?
If these changes modify the database schema, you should include a database migration. …
=> Update copyright year

.circleci/config.yml
Refs #1384. (Fixes it for this repo; we'll need to make the same changes across projects.)
Circle CI is updating the images they maintain in Docker Hub [0].
Ostensibly we're supported to switch from `circleci/python:3.7-buster`
to `cimg/python`, but the latter image is based on Ubuntu Focal,
whereas we have a hard requirement for Debian Buster (until we migrate
to Debian Bullseye). So instead let's use `debian:buster`, which
is not a CircleCI image, but fits our use case.
Some changes are required: make sure sudo is present, update paths
not to assume a normal user, install xvfb. Otherwise, fairly
straightforward.
[0] https://circleci.com/docs/2.0/next-gen-migration-guide
Is CI passing?
=> Ensure circleci docker images are supported

securedrop_client/gui/widgets.py
Ensures that the last message of a conversation is never too close to the reply box.
:pear: @creviera 
Fixes @ninavizz's unhappiness.
=> Fix missing bottom margin in conversation

securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/sync.py, tests/gui/test_widgets.py, tests/test_sync.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1344
Fixes https://github.com/freedomofpress/securedrop-client/issues/1343
=> Speed up source deletion

securedrop_client/gui/conversation/__init__.py, securedrop_client/gui/conversation/delete/__init__.py, securedrop_client/gui/conversation/delete/dialog.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, tests/gui/conversation/delete/test_dialog.py, tests/gui/test_widgets.py
:crystal_ball: **Review recommendations**: I split the changes in two commits, so that tests can be run (unchanged) after the class as been moved, then can be run again (without changes to the non-test code) after they are moved. :slightly_smiling_face: 
This is the 10th step to be split out of #1369.
It moves the `DeleteConversationDialog` definition to its own file/module.
If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please …
=> Refactor move DeleteConversationDialog to 'gui.conversation' namespace

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/release.md
Adds bug and issue templates with language largely taken from the SecureDrop server repo. I've incorporated @ninavizz's proposed changes in https://github.com/freedomofpress/securedrop/pull/6175 with some modifications; if you review this PR, please also review Nina's, so we can keep language in sync between the two.
The release template is new. It should resemble previous release tickets like #1275, with two notable differences:
- I've added placeholders for RM and Deputy RM roles
- I've added a pre-flight testing step using apt-qa.
This assumes that we'll want to continue to do most QA using nightlies (which does have the benefit of high developer agility -- we can build those quickly and on-demand without worrying about RC increments) while getting important pre-release confidence in …
=> Add bug, feature, release templates

securedrop_client/api_jobs/sync.py, securedrop_client/db.py, tests/api_jobs/test_sync.py, tests/factory.py, tests/functional/cassettes/test_delete_source.yaml, tests/functional/cassettes/test_download_file.yaml, tests/functional/cassettes/test_export_dialog.yaml, tests/functional/cassettes/test_login_as_journalist.yaml, tests/functional/cassettes/test_login_from_offline.yaml, tests/functional/cassettes/test_logout_as_journalist.yaml, tests/functional/cassettes/test_offline_delete_source_attempt.yaml, tests/functional/cassettes/test_offline_read_conversation.yaml, tests/functional/cassettes/test_offline_send_reply_to_source.yaml, tests/functional/cassettes/test_offline_star_source.yaml, tests/functional/cassettes/test_receive_message_from_source.yaml, tests/functional/cassettes/test_seen_and_unseen.yaml, tests/functional/cassettes/test_send_reply_to_source.yaml, tests/functional/cassettes/test_star_source.yaml, tests/functional/cassettes/test_unseen_source_becomes_seen_on_click.yaml, tests/functional/cassettes/test_user_icon_click.yaml, tests/gui/test_widgets.py, tests/test_storage.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1143
Closes https://github.com/freedomofpress/securedrop-client/issues/1157
This PR removes the `/user` api call and instead uses the `/users` endpoint to update and manage the current user as well as all other users. Since an API call is removed and a new one is introduced, the functional test cassettes needed to be regenerated (see the cassettes section in the README for more details if needed).
Followup: Once https://github.com/freedomofpress/securedrop/pull/6225 is released, we can remove the old way of creating users based on a reply's `journalist_uuid`. For now, I left this in to continue to support showing replies associated with no corresponding user account on the server (`/users` doesn't actually return any user …
=> Prepare for a smooth transition for new Deleted User

.github/ISSUE_TEMPLATE/release.md, tests/conftest.py, tests/gui/auth/test_dialog.py, tests/test_app.py
Closes #1398 by:
1. testing that the Client appears translated when run under a (translated) valid `$LANG`; and
2. adding a manual check for (1) in preflight testing.
=> tests localization and documents preflight check

Makefile, README.md
To be able to install the dependencies you need Python 3.7 installed.
For newer Fedora/Debian versions where `python3` points at a different
version, a variable can be set to use a different binary:
`PYTHON=python3.7 make venv`
This is also documented in the README.
Fixes #1399.
* Run `make venv`, observe it still runs `python3 -m venv ...`.
* Then try `PYTHON=python3.7 make venv`, observe it now runs `python3.7 -m venv ...`
If these changes add or remove files other than client code, …
=> Document need for Python 3.7 and make `make venv` more flexible

securedrop_client/api_jobs/sync.py, securedrop_client/db.py, securedrop_client/gui/widgets.py, securedrop_client/storage.py, tests/api_jobs/test_sync.py, tests/gui/test_widgets.py, tests/test_storage.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1414
Fixes https://github.com/freedomofpress/securedrop-client/issues/1416
Fixes https://github.com/freedomofpress/securedrop-client/issues/1411
This PR fixes all the issues above by ensuring that a pending or failed reply (aka "draft reply", because it exists in the `draftreplies` table) cannot have a null sender. One of the issues that came up during our testing was that we were allowing null `journalist_id` in the `draftreplies` table. Once the data was in this state, there would be issues whenever the client would have to update badges (on authentication change, when a user's name changed, and when badge needed to be updated to show the "deleted" sparkles icon).
In case you are a QA tester, ensure that your local …
=> Re-associate draft replies with "deleted" user account

securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/sync.py, tests/gui/test_widgets.py, tests/test_sync.py
As discussed today in pre-release check-in, revert source deletion changes and defer to next release so that we can fully resolve https://github.com/freedomofpress/securedrop-client/issues/1422. This reverts https://github.com/freedomofpress/securedrop-client/pull/1386.
- Ensure that the revert does not break subsequent changes
- Changes should be reviewed as part of rc4 QA
-  [x] **The reviewer will need to test these changes**
If these changes add or remove files other than client …
=> Revert source deletion changes

alembic/versions/eff1387cfd0b_add_deletedconversation_table.py, securedrop_client/db.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/storage.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_models.py, tests/test_storage.py
Delete local files and relevant source records immediately as soon as conversation is scheduled for deletion on the server (do not wait for sync to delete).
Fixes #1429
Replaces https://github.com/freedomofpress/securedrop-client/pull/1424
Will be relevant for #1344
**High-level approach:**
- When the server has successfully scheduled files for deletion, files and records are deleted locally, and the source's UUID (not id) is inserted into a `deletedconversation` table (which is basically a flag). (We avoid storing source id and other PII/attributes.)
- For the first sync after the deletion request is made, if a source's UUID is in the `deletedconversation` table, we do not update their record. This is to avoid a situation where a stale sync re-populates source records that have been …
=> Delete conversation files and records as soon as server confirms scheduled deletion

securedrop_client/api_jobs/sync.py, securedrop_client/app.py, securedrop_client/database.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, securedrop_client/logic.py, securedrop_client/resources/css/source_menu.css, securedrop_client/state/__init__.py, securedrop_client/state/domain.py, securedrop_client/state/state.py, securedrop_client/sync.py, tests/api_jobs/test_sync.py, tests/conftest.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/integration/conftest.py, tests/state/test_domain.py, tests/state/test_state.py, tests/test_app.py, tests/test_logic.py
> :crystal_ball: **Reviewers!** The commits are built individually and are meant to do one thing at a time. ~~I left a couple of quirks when splitting them, that you'll likely notice if you review commit by commit, but~~ I think it's ~~still~~ worth [reviewing commit by commit] if the overall diff feels a bit overwhelming. :slightly_smiling_face: 
>
> Once we're there, I'll rebase the branch one more time so that it's fully up to date before merging, just let me know.
Closes https://github.com/freedomofpress/securedrop-client/issues/1354
Please refer to the issue for context.
**Summary**:
- This PR enables a journalist to download all the files of the currently visible conversation at once, via the conversation menu (a.k.a "source menu", a.k.a "kebab menu") or a keyboard shortcut …
=> Add download conversation

securedrop_client/gui/actions.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, tests/gui/test_actions.py, tests/gui/test_widgets.py
:crystal_ball: **Review recommendations**: I split the changes in three commits, so that tests can be run (unchanged) after the class as been moved, then can be run again (without changes to the non-test code) after they are moved. :slightly_smiling_face: 
This is the 12th step to be split out of #1369.
It moves the `DeleteSourceAction` and `DeleteConversationAction` definition to their own file/module. That module is at the top level at the moment because most actions benefit from being available at the "main widows" level when used with keyboard shortcuts (the widget needs to be in focus for the shortcut to be available, the main window is always in focus). Adding shortcuts for actions is discussed in https://github.com/freedomofpress/securedrop-client/issues/1358
Once we have clarity …
=> Refactor move user actions to 'gui.actions' namespace

securedrop_client/gui/actions.py, securedrop_client/gui/base/dialogs.py, securedrop_client/gui/conversation/delete/dialog.py, securedrop_client/gui/source/delete/dialog.py, securedrop_client/gui/widgets.py, tests/gui/conversation/delete/test_dialog.py, tests/gui/source/delete/test_dialog.py, tests/gui/test_actions.py
This PR replaces #1374 and #1375 because that is immediately relevant to fixing #1442.
Closes #1374
Closes #1375
**Summary**: Adding a command to ensure that the application state is updated when conversations are deleted adds very little complexity if all the commands are contained in the Qt action. Currently the actions that use a confirmation dialog don't actually issue any commands, the dialogs do. This PR ensures that actions consistently issue the relevant commands, whether they first display a confirmation dialog or not. Incidentally, that simplifies significantly the role, testing and implementation of the dialogs while fitting the Qt usage guidelines for dialogs.
Currently, the dialog classes send commands to the `Controller` when their buttons are triggered. This results in a …
=> Refactor ensure actions hold the "commands" and confirmation dialogs implement Qt's API for dialogs

securedrop_client/gui/actions.py, securedrop_client/gui/base/dialogs.py, securedrop_client/gui/conversation/delete/dialog.py, securedrop_client/gui/source/delete/dialog.py, securedrop_client/gui/widgets.py, securedrop_client/state/state.py, tests/gui/conversation/delete/test_dialog.py, tests/gui/source/delete/test_dialog.py, tests/gui/test_actions.py, tests/state/test_state.py
:crystal_ball: **Reviewers** (@creviera): This PR builds on #1447, please wait until that one is merged to rebase then review. Only two commits will remain :slightly_smiling_face: (In the meantime you can look at the last two commits to get an idea of the changes involved.)
Fixes #1442 
Ensure that the steps to reproduce defined in #1442 are handled:
- Select a source with files that have not yet been downloaded
- Delete the source conversation
- Select the source menu
This PR gives `DeleteConversationAction` access to the application state, which means we can now expand `state.State` to contain information about messages and use it to enable/disable the action dynamically. It's out of scope, but I thought it was worth mentioning.
If these changes modify code paths involving cryptography, …
=> Disable download when conversation was deleted

securedrop_client/queue.py
Fixes https://github.com/freedomofpress/securedrop-client/issues/1444
This is a draft reply until https://github.com/freedomofpress/securedrop-client/pull/1434 is merged, which will create a conflict.
Since this is a refactor-only, perform regression testing around the queue: 
* Cause a network outage to enqueue a `PauseQueueJob` and confirm that the behavior is the same as on `main`
* Send a reply
* Download a file
* Logout and log in again
If these changes add or remove files other …
=> Make RunnableQueue process any QueueJob instead of just ApiJob

securedrop_client/api_jobs/uploads.py, securedrop_client/db.py, securedrop_client/gui/widgets.py, securedrop_client/storage.py, tests/api_jobs/test_uploads.py, tests/test_models.py, tests/test_storage.py
Fixes #1445 
Fixes #1450
- Perform regression testing as indicated in #1432 and ensure no regression (i.e. deleted messages are not re-downloaded during stale sync, and deletion via the JI still works)
**Test with larger number of sources/database writes:** 
- Log into the client wait for sync. Ssh into your server, and using our QA script (loaddata), add a large number of sources to the sever (n>50). While client is syncing, begin to safe-delete some local conversations. 
If these …
=> Fix reply ordering and update source and reply attributes after safe delete

alembic/versions/9ba8d7524871_add_deletedsource_table.py, securedrop_client/db.py, securedrop_client/logic.py, securedrop_client/storage.py, tests/gui/test_widgets.py, tests/test_logic.py, tests/test_models.py, tests/test_storage.py, tests/test_sync.py
Fixes #1344.
- Setup: ensure your instance has a number (> 5) of sources with files, messages, and replies. For at least one source, save their codename. 
**Migration**
**Test local deletion: happy path**
- Choose a source in the client and download files/attachments for them. 
- Inspect Sources table and note their id
- Select "Delete Source"
**Test local deletion right after conversation deletion**
- Choose a source in the client and download files/attachments for them. 
- Inspect Sources table and note their id
- Select "Delete files and messages"
- Quickly select "Delete source" (inside same sync period)
**Test local deletion: network failure**
- Choose a source in the client and download files/attachments for them.
- Inspect Sources table and note their id 
- Select "Delete Source", …
=> Delete source files and records locally as soon as server confirms deletion

securedrop_client/gui/main.py
QWidget.move requires either a QPoint or (int, int) as arguments instead of (float, float)
=> minor fix in show_login

securedrop_client/logic.py
Followup for https://github.com/freedomofpress/securedrop-client/issues/1344
- Note that https://github.com/freedomofpress/securedrop-client/pull/1458 ensures that a stale sync will not add the source back, so there is no longer a need to keep track of timestamps in the gui. Either tomorrow or in a follow PR, after our scheduled release, we can remove this stale code. 
If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check …
=> update gui immediately after deletion

securedrop_client/logic.py, tests/test_logic.py
=> always "invalidate token" when you log out

securedrop_client/storage.py
Fixes #1472
Towards #1465
- Set up a staging environment with n > 10 sources. Since this is a race condition, you may have to test a lot of sources to create this behaviour.
- Wait for at least one sync, to ensure client and server are in same state.
- Start deleting sources via the client. The goal is to locally-delete a source right before a sync is applied (syncs are every 15 seconds).
If these changes add or remove files other than client code, the AppArmor profile may need to be …
=> Add locally-deleted Source to DeletedSource table

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
This came up during _pre-_QA testing for the upcoming release next week.
Resolves https://github.com/freedomofpress/securedrop-client/issues/1463
=> always show selected source widget as read

securedrop_client/logic.py, tests/test_logic.py
I still need to see if I can create an STR, but I ran into an issue at some point while stress testing deletion and saw that we were not handling a NoResultFound db error here.
Opening up a draft PR in the meantime, in case this comes up during QA testing for the client release, and to get @rocodes's attention on this early since I'll be out for the rest of the week.
I also made this change last week, so it's not super fresh and may need a little rework.
...
If these changes add or …
=> guard against a reply being sent to a source that was just deleted

securedrop_client/gui/main.py
Clear the global mouse selection. This issue occurs on systems with a global mouse selection (e.g. X11).
Fixes https://github.com/freedomofpress/securedrop-client-security/issues/2
=> Also clear global mouse selection after login

securedrop_client/gui/widgets.py, tests/gui/test_widgets.py
This reverts commit f9508edff93de0cc6cf0cc2a292006b7061e64d9.
Fixes regression described in https://github.com/freedomofpress/securedrop-client/issues/1465#issuecomment-1102964753 where an unselected source with new content shows up as read.
Follow the STR described by @cfm in the regression comment here: https://github.com/freedomofpress/securedrop-client/issues/1465#issuecomment-1102964753 
If these changes add or remove files other than client code, the AppArmor profile may need to …
=> Revert "always show selected source widget as read"

.circleci/config.yml
There's some bug in which building from a sdist tarball doesn't work.
Given that we wanted to move away from that anyways, switch to just
specifying the path to the directory instead.
Needs <https://github.com/freedomofpress/securedrop-debian-packaging/pull/332> to work.
:sparkles: @creviera for finding out the difference in behavior between the tarball and the directory builds!
If these changes add or remove files other than client code, the AppArmor profile may need to be updated. …
=> Fix CI build-buster job

securedrop_client/gui/conversation/__init__.py, securedrop_client/gui/conversation/export/__init__.py, securedrop_client/gui/conversation/export/print_dialog.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, tests/conftest.py, tests/gui/base/test_dialogs.py, tests/gui/conversation/export/test_print_dialog.py, tests/gui/test_widgets.py, tests/integration/conftest.py
Moves `widgets.PrintDialog` to `conversation.PrintFileDialog` in order to make future changes easier to review.
Very similar to https://github.com/freedomofpress/securedrop-client/pull/1492 
Removes the last reference to the non-GUI `export` module from `gui/widgets.py`. :confetti_ball:
Opens the way to uncoupling both export dialogs from the `Controller`, and encapsulating all references to that non-GUI export service into a single GUI object (interface if you wish). 
If these changes …
=> Refactor extract conversation.PrintFileDialog

securedrop_client/export.py, tests/test_export.py
On templates using R4.1 tools, `qvm-open-in-vm` redirects stdout/stderr to `/dev/null`, so instead we call `qrexec-client-vm` directly
Fixes https://github.com/freedomofpress/securedrop-workstation/issues/775
**In Qubes 4.0**:
**In Qubes 4.1**, using our VM templates with Qubes R4.1 repositories (i.e. bullseye, buster with manual upgrade, or after in-place upgrade to 4.1):
=> Unbreak export on Qubes OS R4.1

securedrop_client/logic.py, tests/test_logic.py
When starting to encapsulate the export behavior, I realized that most tests covering the signal emissions were actually not testing anything :grimacing: 
This PR fixes that situation as a preliminary step to refactoring that code.
See the commit message for details :slightly_smiling_face: 
:warning: **Reviewers** this PR is very small, but does require some back and forth between the tests and the code under test to confirm that I made the right judgement when fixing the tests that were inaccurate.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please check …
=> Fix missing and incorrect assertions in Controller tests

securedrop_client/logic.py, tests/test_logic.py
Removes necessary mocking and increases the test ~coverage~ depth by relying on [`QSignalSpy`][docs] to test Qt signals.
Builds upon https://github.com/freedomofpress/securedrop-client/pull/1501
This is a preliminary step to extracting the "export" responsibility out of the `Controller`. (I wanted to make sure the tests were working as intended and slightly more compact before moving them over.)
[docs]: https://doc.qt.io/qt-5/qsignalspy.html
:crystal_ball: **Reviewers**: once #1501 is merged, only the last commit will remain :slightly_smiling_face: 
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in …
=> Refactor export tests for portability

securedrop_client/export.py, securedrop_client/gui/conversation/export/dialog.py, securedrop_client/gui/conversation/export/print_dialog.py, securedrop_client/logic.py, tests/gui/conversation/export/test_dialog.py, tests/gui/conversation/export/test_print_dialog.py, tests/test_logic.py
The controller used to imperatively emit signals on the Export instances. This breaks the encapsulation provided by the Export class and defeats one of the main benefits of using signal: de-coupling components.
That, in turn, is one of the situations that made it more difficult for me to wrap my head around this code.
From Qt's documentation:
>  Signals are public access functions and can be emitted from anywhere,
but we recommend to only emit them from the class that defines the signal
and its subclasses.
The controller now emits a signal indicating that a preflight check is desirable (for example) and the Export instance connects its own slots to that signal.
See https://doc.qt.io/qt-5/signalsandslots.html
**Note**: As soon as we think of signals as a representation of events, it …
=> Refactor ensure signals are used as recommended by Qt

securedrop_client/gui/actions.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, securedrop_client/resources/css/source_menu.css
Adopts a verb-based naming convention for **actions** available to journalists.
This prevents the apparition of identically named actions in close proximity and allows to simplify the existing menu.
It is a prelimiary step to prepare the ground for the "Export All Files" feature.
See details in #1504
Fixes #1504
If these changes modify the database …
=> Ensure that action menu items are named using verbs, and capitalized consistently

securedrop_client/gui/widgets.py
Fixes #1509 
Useful for #1496 
=> Fix deprecation warnings, comparing int and float values

tests/gui/auth/sign_in/test_error_bar.py, tests/gui/auth/test_dialog.py, tests/gui/base/test_dialogs.py, tests/gui/base/test_inputs.py, tests/gui/base/test_misc.py, tests/gui/base/test_sdcheckbox.py, tests/gui/conversation/delete/test_dialog.py, tests/gui/conversation/export/test_dialog.py, tests/gui/conversation/export/test_print_dialog.py, tests/gui/source/delete/test_dialog.py, tests/gui/test_actions.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/helper.py, tests/integration/conftest.py, tests/state/test_state.py, tests/test_app.py, tests/test_resources.py
Fixes #1514 
Explanation:
An instance of `QApplication` must be in scope when rendering Qt widgets. _My understanding is that the instanciation of `QApplication` is what creates and starts the event loop._
In hindsight, the fact that only one application instance must be running at once not only make sense, but also could explain
why all test files would run fine individually (see **Comments** in #1514)  yet some combinations of files would often cause errors: if `QApplication` instances are destroyed and created in quick succession, a segfault would occur if the second instance was created before the first once (and the corresponding stuff, e.g. thread...) was properly gone.
In order to make sure that only one instance of `QApplication` was created, I moved the creation to a separate …
=> Ensure QApplication is instanciated only once in tests

securedrop_client/storage.py, tests/test_storage.py
Fixes #1474
- Choose a source with multiple file submissions. Download only one file via the client, and delete only that one submission via the JI, leaving the others intact but not yet downloaded.
=> When all submissions are deleted for a source, delete the enclosing directory

securedrop_client/storage.py, tests/test_storage.py
Follow up on https://github.com/freedomofpress/securedrop-client/pull/1475 (see https://github.com/freedomofpress/securedrop-client/pull/1475#pullrequestreview-1008589428)
Applying review suggestions before @rocodes is back, because they're trivial to undo whenever we want to.
If these changes modify the database schema, you should include a database …
=> Refactor assertions sequence for ease of troubleshooting

securedrop_client/app.py, securedrop_client/logic.py, tests/test_app.py
Fixes #1510  
Builds upon (but is technically independent from) #1515 
:warning: **Clarification**: It does fix the issue insofar as it was defined by errors in the functional tests suite. More `QThread` objects exist that are destroyed before their threads are closed, but this PR is enough to unlock our way to Python 3.9. (Which means that we're probably not testing around those other threads. :bulb:)
Works towards unblocking #1496 and is based on research I've made in the context of "Export All Files" (original: [show the diff of this file](https://github.com/freedomofpress/securedrop-client/commit/249cc873c2b286e2ce548b85f14fc4a9cdaa6fb2#diff-b9f8828b97a9e5a9772e99886228db6659dd993060e33ecbeda19ffbdad310f9)).
If these changes modify code paths involving cryptography, the opening of …
=> Ensure that the export and API threads are closed before the corresponding QThread instances are destroyed

files/usr.bin.securedrop-client
Access to this device-node is required on kernel versions 4.18 or greater (per commit message https://github.com/QubesOS/qubes-linux-utils/commit/4fe08d31e4d168688bfa246929ebbcdf54f54352 and AppArmor denials when testing with the newer kernel that ships with the Bullseye template).
Fixes the proxy error and disposable VM opening errors described in https://github.com/freedomofpress/securedrop-workstation/issues/600#issuecomment-1168104477
On a system that exhibits the issue, apply this fix (either by modifying the AppArmor profile in `/etc/apparmor.d`, or building a new package from this branch and installing it), restart AppArmor and verify that the issue is resolved.
=> Add /dev/xen/hypercall to AppArmor allow-list

MANIFEST.in
As of #1527, 2 languages are 100% translated and approved (listed in Weblate sort order)
1. `zh_Hans`: Chinese (Simplified)
2. `pt_PT`: Portuguese (Portugal)
Another 5 are 100% translated but only partially approved (listed in Weblate sort order):
3. `de`: German
4. `ca`: Catalan
5. `is`: Icelandic
6. `sv`: Swedish
7. `tr`: Turkish
To err on the side of conservatism for now, here we enable only `pt_PT` and `zh_Hans` as 100% translated and approved.
```sh-session
(.venv) user@sd-dev:~/securedrop-client$ python setup.py sdist 2> /dev/null | grep -E "(pt_PT|zh_Hans)"
creating securedrop-client-0.7.0/securedrop_client/locale/pt_PT
creating securedrop-client-0.7.0/securedrop_client/locale/pt_PT/LC_MESSAGES
creating securedrop-client-0.7.0/securedrop_client/locale/zh_Hans
creating …
```
=> feat: enable `pt_PT` and `zh_Hans` as supported languages

Makefile, requirements/dev-buster-requirements.in, requirements/dev-buster-requirements.txt
**The nightly build will start failing tonight** :crystal_ball:. 
----
:fire: This PR is somewhat urgent, because all builds will be failing until we fix this.
----
This PR does:
- Add a **make** target to generate `requirements/dev-buster-requirements.txt`, just in case we have to do this again. (We thought that we wouldn't have to upgrade dependencies until we stop supporting Buster. We were wrong. :slightly_smiling_face:) 
- Add a version constrain on **semgrep** on Buster to ensure today's community rules can be used successfully. (Bullseye's requirements are already past that version.)
- Update **black** because it shares dependencies with **semgrep** (namely: **click**). _Both version constraints are the minimum required for the build to succeed (for documentation purposes), but the …
=> Fix (tonight's) nightly build

.semgrep/custom-rules.yml, securedrop_client/gui/conversation/export/dialog.py, securedrop_client/gui/conversation/export/print_dialog.py
- Fixes #1534
- Makes semgrep rules a bit more resilient (though they still wouldn't have caught these issues, sadly)
Follow STR in #1534 and confirm that dialog titles now show up as translated.
You can insert the following into `securedrop_client/gui/conversation/export/dialog.py` and run `make semgrep-local` to confirm that the two rules are working as expected:
For `.format()` method:
```
self.starting_header = _(
"Preparing to export:".format(self.file_name)
)
```
For f-strings:
```
self.starting_header = _(
f"Preparing to export: {self.file_name}"
)
```
Both should cause semgrep to exit nonzero and report an error.
=> Make dialog titles translatable; tweak Semgrep rules

.circleci/config.yml
Removes the steps specific to Debian Buster from our CI pipeline, effectively removing support for Debian Buster.
=> Remove support for Debian Buster

.circleci/config.yml
> :crystal_ball: **Reviewers**: This PR is ready to review, but includes three commits from #1544 because they make the work easier. Only the very **last** commit (https://github.com/freedomofpress/securedrop-client/pull/1546/commits/0a6d4d7a43cf6b96d69c15ec271703f6fe6e5526 [click me!](https://github.com/freedomofpress/securedrop-client/pull/1546/commits/0a6d4d7a43cf6b96d69c15ec271703f6fe6e5526)) needs to be reviewed here. (I'll update this branch as soon as #1544 is merged.)
Splits the testing, linting, and diverse checks into distinct CI jobs. 
**Bonus**: a ~20% decrease in wall clock time (the trade-offs are called out in #1543).
Fixes #1543
=> Add granularity to ci pipeline for readability

securedrop_client/app.py, securedrop_client/config.py, securedrop_client/export.py, securedrop_client/gui/conversation/export/device.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, tests/conftest.py, tests/gui/conversation/export/test_device.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/integration/conftest.py, tests/test_app.py, tests/test_logic.py
:crystal_ball: _**Reviewers (@rocodes)**: This PR really makes sense to review commit by commit, especially because there is some refactoring / clean up / fixing in the beginning. However, the final approach was settled in the last three commits, so you may want to skip ahead._ :slightly_smiling_face: 
> **General idea**: The export service is a dependency of the GUI's `export.Device`. This PR ensures it is injected into the GUI. One immediate benefit is that the functional tests can now inhibit the Qubes OS dependency without knowing anything about the GUI internals, by providing a custom _export service_ when initializing the app. This allows to remove all the code that was specific to testing but was interleaved with the production code - inside `controller.qubes` conditionals.
This is …
=> Refactor remove controller dependency from export device (Part 1)

files/securedrop-client, securedrop_client/api_jobs/sync.py, tests/api_jobs/test_sync.py
Closes #1547 by:
1. teaching the `securedrop-client` script to check for a Qubes service flag like `SDEXTENDEDTIMEOUT_N` and export it as `SDEXTENDEDTIMEOUT=N`;
2. having the `MetadataSyncJob` (noisily) override its `sdclientapi.API.default_request_timeout` with `$SDEXTENDEDTIMEOUT` if set in the environment.
Point your SecureDrop Workstation at [my testing instance](https://wiki.freedom.press/wiki/User:Cory/SecureDrop_instance) per <https://github.com/freedomofpress/securedrop-client/issues/1547#issuecomment-1224985491> and <https://github.com/freedomofpress/securedrop-client/issues/1547#issuecomment-1226640519>.  Then:
1. Check out `1547-override-timeout` in `sd-app:/home/user/securedrop-client`.
2. Apply the following patch so that we can test `files/securedrop-client` within the …
=> feat: allow overriding `MetadataSyncJob` timeout via Qubes service flag

securedrop_client/api_jobs/downloads.py, securedrop_client/api_jobs/uploads.py, securedrop_client/export.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/queue.py, securedrop_client/storage.py
Addresses the logs aspect of https://github.com/freedomofpress/securedrop-client-security/issues/4
=> Fix remove untrusted strings from production logs

securedrop_client/export.py, securedrop_client/gui/conversation/export/dialog.py, securedrop_client/gui/conversation/export/print_dialog.py, tests/gui/conversation/export/test_dialog.py, tests/gui/conversation/export/test_print_dialog.py, tests/test_export.py
Addresses the user interface aspect of [#4 ](https://github.com/freedomofpress/securedrop-client-security/issues/4)
Fixes [#4](https://github.com/freedomofpress/securedrop-client-security/issues/4)
=> Remove unverified string from user interface

securedrop_client/gui/conversation/export/dialog.py, securedrop_client/locale/messages.pot
Removes an unused string that seems to be a holdover from 64ef17d832b7f738ac038e1a5c6ab2e085909efe
Confirmation that the string is not used anywhere in the code should be sufficient.
=> Remove unused export dialog string

requirements/dev-bookworm-requirements.txt, requirements/dev-bullseye-requirements.txt, requirements/dev-sdw-requirements.in, requirements/dev-sdw-requirements.txt
Upgrades **pytest-qt** so that **py** is not required anymore.
Additional context: the **py** package is in maintenance mode, and the parts we use were integrated into **pytest**. The **pytest-qt** package was still referring to the original **py** modules before `pytest-qt==4.2.0`.
Fixes #1595
=> Remove dependency on py package (deprecated)

securedrop_client/export.py, tests/test_export.py
Fixes #1594.
Check out this branch in your sd-app vm. Run the client and step through STR in linked issue. Ensure successful export, no errors in logs, and success confirmation message.
[self-contained]: …
=> fix: Accept empty result from sd-devices during export for backwards compatibility

README.md
Updates the readme in preparation for the 2022 Aaron Swartz Day and International Hackathon by:
- documenting how to use `socat` to proxy from a macOS Client development environment to a remote Server development environment
- *TK*
=> docs: update readme for 2022 Aaron Swartz Day

files/press.freedom.SecureDropClient.desktop
This is  follow up on https://github.com/freedomofpress/securedrop-client/pull/1589, that ensures that the file name that's referred to by the SecureDrop Client application actually exists.
**Note**: This commit creates a new file so that the application can be built while the build tooling is updated. Once the build tooling refers to the new file, the old one can be removed.
=> Rename desktop entry after freedesktop specifications

files/securedrop-client.desktop
This is a follow up on #1600 and https://github.com/freedomofpress/securedrop-builder/pull/402. It concludes the renaming of the SecureDrop Client desktop entry.
:crystal_ball: **Reviewers**: The CI pipeline will need to be re-triggered after https://github.com/freedomofpress/securedrop-builder/pull/402 is merged. Failures are expected before that.
Also related to: https://github.com/freedomofpress/securedrop-client/pull/1589
=> Rename desktop entry after freedesktop specifications (2)

securedrop_client/app.py
This changes the freedesktop filename to conform to reverse-dns hierarchy standards. It also ensures that the file name doesn't refer to a domain name that is no longer under FPF's control.
Fixes https://github.com/freedomofpress/securedrop-client/pull/1588#discussion_r1016195397
If these changes modify the database schema, you should include a database …
=> Rename desktop entry to follow freedesktop specifications

Makefile
The vulnerability is fixed in `sqlalchemy>=2.0.0b1`, and the most recent version in the 2.x series is currently `2.0.0b4`.
Unblocks: https://github.com/freedomofpress/securedrop-client/pull/1609 and every other PR currently being reviewed.
=> Ignore SQLAlchemy vulnerabitity without released mitigation

securedrop_client/locale/messages.pot, securedrop_client/logic.py, securedrop_client/queue.py, tests/test_logic.py, tests/test_queue.py
Fixes #1607.
- Currently after a metadata sync completes, if there are messages and replies to download from the server, the client shows a message "Retrieving messages" for 2.5 seconds before adding a job per message / reply to a queue.
- Due to the Guardian's volume of sources, messages, and replies, processing all message and reply download jobs after a metadata sync has completed can take a long time (around 20 minutes). 
- We would like to provide an easy way for the user to track download progress.
- Note: as messages are downloaded, the user can see the text being populated (i.e.`<Message not yet available>` being replaced by the decrypted message text) allowing the user to approximate overall download progress.
- This change adds message to the left side of the top nav bar showing …
=> Show message and reply retrieval progress message

Makefile, requirements/dev-mac-requirements.in, run.sh, scripts/setup-tmp-directories.sh
Changes:
* The code inside run.sh is pulled out into a script file setup-tmp-directories.sh as it needs to be run within the `make test` command as well
* New requirements files are added for Mac OS users.
=> Improve OSX setup flow based on experience

Makefile, README.md, run.sh
Fixes #1591
This also changes the install instructions on macOS in general, unifying the setup for Intel and arm64 machines. This also drops instructions to use pyenv in favour of installing Python 3.9 via Homebrew. This is necessary to allow x86_64 mode Python 3.9 virtual environments to work as we need them to.
=> Allow development environment to work on arm based macOS machines

.semgrep/custom-rules.yml, requirements/dev-bookworm-requirements.txt, requirements/dev-bullseye-requirements.txt, requirements/dev-sdw-requirements.in, requirements/dev-sdw-requirements.txt, securedrop_client/api_jobs/base.py, securedrop_client/app.py, securedrop_client/export.py, securedrop_client/gui/actions.py, securedrop_client/gui/base/checkbox.py, securedrop_client/gui/base/inputs.py, securedrop_client/gui/base/misc.py, securedrop_client/gui/conversation/delete/dialog.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/sync.py, tests/conftest.py, tests/functional/test_logout.py, tests/functional/test_user_profile_menu.py, tests/gui/base/test_misc.py, tests/gui/conversation/export/test_device.py, tests/gui/test_widgets.py, tests/integration/conftest.py, tests/integration/test_styles_file_download_button.py, tests/integration/test_styles_reply_status_bar.py, tests/integration/test_styles_sdclient.py, tests/integration/test_styles_speech_bubble_message.py, tests/integration/test_styles_speech_bubble_status_bar.py, tests/test_logic.py
We are currently not providing PyQt5 stubs to **mypy**. As a result, Qt types are not checked. Since half of the repo is a Qt GUI, we should fix that.
@zekehuntergreen wrote  ([source](https://github.com/freedomofpress/securedrop-client/pull/1604#discussion_r1047368531)):
> After reading the section in the docs on [None and Optional handling](https://mypy.readthedocs.io/en/stable/command_line.html#none-and-optional-handling) [the fact that **mypy** didn't identify the implicit `Optional[pyqtSignal]`] surprised me too! It sounds like the default behavior changed as of version 0.980 so that parameters with `None` as a default value are no longer treated as `Optional` be default.
>
> I think what's going on is that mypy can't find a library stub for `PyQt5.QtCore` so in the absence of a type …
=> Enable PyQt5 type checking

securedrop_client/queue.py
Fixes failing CI `lint-*` ([e.g.](https://app.circleci.com/pipelines/github/freedomofpress/securedrop-client/3053/workflows/50a49db6-3d9e-4842-a562-8920451e1206/jobs/18422)).  After #1611, specifically 64293d1, this `ignore` pragma is unnecessary and therefore invalid in strict mode.  It was introduced in #1486, which was reviewed and merged while #1611 was still in review.
- I have tested these changes in the appropriate Qubes environment
- I do not have an appropriate Qubes OS …
=> chore: remove unnecessary mypy `ignore` pragma

.github/ISSUE_TEMPLATE/release.md
Closes #1598 by linking to instructions for testing the `en_XA` pseudolocale as part of routine QA.
Documentation-only change.
=> docs: add reminder for pseudolocale QA

securedrop_client/gui/actions.py, securedrop_client/gui/conversation/__init__.py, securedrop_client/gui/conversation/export/__init__.py, securedrop_client/gui/conversation/export/device.py, securedrop_client/gui/conversation/export/print_transcript_dialog.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, tests/conftest.py, tests/gui/conversation/export/test_device.py, tests/gui/conversation/export/test_print_transcript_dialog.py
The shortest path to providing an option to print a conversation transcript to journalists.
Fixes #1435
We're explicitly making the decision to favor speed of delivery for this and next few features in the spirit of making the most of the pilot participant's feedback. (We: @zenmonkeykstop, @cfm, @gonzalo-bulnes)
General availability considerations are out of the table for the time being, and accordingly, I'll be pausing the ongoing work to improve code structure and implementation patterns (namely: testing patterns, usage of native Qt features, etc).
Once this and related work is released, we'll pause and re-assess, whether:
- we want to keep iterating on the pilot to answer outstanding questions
- start moving towards general availability
- collect and document learning about journalists …
=> Add action to (re-)generate and print conversation transcript

project.json
Relevant upstream PR: https://github.com/sqlalchemy/sqlalchemy/pull/8563
Does not affect us because we only use it with local SQLite databases. [We also ignore this in `securedrop`](https://github.com/freedomofpress/securedrop/blob/develop/project.json).
Just a configuration file for internal infrastructure, no testing required.
=> Update safety alerts: 51668 (sqlalchemy)

securedrop_client/app.py, securedrop_client/export.py, securedrop_client/gui/actions.py, securedrop_client/gui/conversation/__init__.py, securedrop_client/gui/conversation/export/__init__.py, securedrop_client/gui/conversation/export/device.py, securedrop_client/gui/conversation/export/transcript_dialog.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, tests/conftest.py, tests/functional/test_export_dialog.py, tests/gui/conversation/export/test_device.py, tests/gui/conversation/export/test_transcript_dialog.py, tests/gui/test_main.py, tests/gui/test_widgets.py, tests/integration/conftest.py, tests/test_app.py, tests/test_export.py
The shortest path to providing an option to export a conversation transcript to journalists.
This is a direct continuation of #1621, the same context applies.
- Takes the existing _export dialog_ as a reference
- Follows the existing patterns for testing it
1. Start the app
2. Select a conversation
3. For good measure download a file or two
4. Trigger "Export Conversation Transcript" in the _conversation menu_ (a.k.a source menu, kebab menu...)
(I can provide guidance for a lightweight tests like I did for #1621, but since exporting doesn't depend on hard to get hardware, I think we should eventually test the feature using an actual USB drive. **Edit**: here is the [patch](https://github.com/freedomofpress/securedrop-client/commit/c3f6f80394b5567163747a094227469e88791a9a).)
=> Add action to (re-)generate and export conversation transcript

securedrop_client/api_jobs/base.py, securedrop_client/api_jobs/downloads.py, tests/api_jobs/test_downloads.py
Towards #1633, but let's keep it open 
- Re-estimate file download speeds on Tor and link to updated metrics URL. Conservative estimate of speed is now 50000B/s (~0.4Mbit/s), down from 100000B/s. This will allow for longer intervals before file downloads time out. 
- Log API retry attempt in client logs if Timeout error is encountered
No logic changes, so pretty light test plan.
If these changes add or remove files other than client code, the AppArmor profile may need to be updated. …
=> Decrease estimation of Tor network speeds when calculating timeout

securedrop_client/export.py, securedrop_client/gui/actions.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, securedrop_client/logic.py, securedrop_client/resources/css/source_menu.css, tests/conftest.py, tests/gui/conversation/export/test_dialog.py, tests/gui/conversation/export/test_print_transcript_dialog.py, tests/gui/conversation/export/test_transcript_dialog.py, tests/gui/test_widgets.py, tests/test_export.py
Fixes #1629
Please refer to the issue for context on the design decisions.
- Confirm that "Export All Files and Messages":
The following confirmation dialog is shown if (and only if) there are files pending download:
<details>
<summary>Obsolete screenshots</summary>
</details>
=> Add sections to conversation menu, download files prior to conversation export

securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/resources/css/sdclient.css, tests/gui/test_main.py, tests/integration/test_styles_sdclient.py, tests/test_logic.py
Fixes #1608 
At our organization, the volume of data (sources, messages, replies, etc.) means that metadata syncs can take a very long time (around 10-20 minutes). While a sync is in progress, a user has very little information about how up-to-date the data that appears in the journalist's interface is. 
Before this change, the "last refresh" message only appears when the user is signed out or when they are disconnected from the network. After the change, the message is also displayed when the user is signed in with an active network connection. 
The sync status message moves from the "Activity status bar" to a new "Sync status bar" between the sync signal and the activity status bar. This is so that sync status can appear next to the retrieval progress message. …
=> Always show "last refresh" sync status message

files/securedrop-client.desktop
Fixes #1638 .
This reverts commit 10225d775226df0f9d7c2e2e03502582c5177741.
Both the new and old-style desktop files are required until a version of securedrop-workstation is available with Salt changes referencing the new file name.
Temporary reverts https://github.com/freedomofpress/securedrop-client/pull/1601
=> Restore non-freedesktopped desktop entry file

files/securedrop-client.desktop
Backports the fix from #1639, restoring the old-style desktop file.
=> [0.9.0] Backport #1639

.circleci/config.yml, securedrop_client/gui/actions.py, tests/gui/test_actions.py
Even if the current locale specifies an encoding that doesn't support other languages (e.g. `ISO 5598-1` a.k.a "latin-1" doesn't support many Unicode characters), the conversation transcript generation MUST NOT fail.
In practice, there is no direct relationship between the language in which the SecureDrop Client UI is displayed and the languages that may be used y sources and journalists in their conversations, so the transcript will always be encoded to UTF-8.
Fixes #1643 
_Pardon the "pirate talk" in the commit message :grimacing: :pirate_flag: the sequence is long enough to run in CI that I didn't want to go back and edit it._
=> Fix support non-ASCII transcripts

.circleci/config.yml, securedrop_client/gui/actions.py, tests/gui/test_actions.py
=> Backport unicode transcript fix

securedrop_client/app.py, securedrop_client/conversation/transcript/transcript.py, securedrop_client/gui/main.py, securedrop_client/gui/widgets.py, securedrop_client/logic.py, securedrop_client/sync.py
Per the mypy documentation[1], the syntax is:
`# type: ignore[error-code]`, with no space between ignore and [. It seems like mypy is fine with the space, but other tools (e.g. PyCharm) aren't, so use the non-spaced version.
[1] https://mypy.readthedocs.io/en/stable/type_inference_and_annotations.html#type-ignore-error-codes
=> Fix syntax of mypy ignore comments

securedrop_client/gui/actions.py, securedrop_client/gui/base/misc.py, securedrop_client/gui/widgets.py, securedrop_client/locale/messages.pot, tests/gui/base/test_misc.py, tests/gui/test_widgets.py
Fixes a few typos that were flagged by AO_Localization_Lab in Weblate.
=> Fix typos in user-facing copy

README.md
Add an index to the README since it is quite long and IMHO having an index improves readability for new comers like me.
No code was touched so no test plan is required.
[self-contained]: …
=> Add readme index for readability and fix numbering typos

securedrop_client/gui/conversation/delete/dialog.py, securedrop_client/locale/messages.pot
Fixes https://github.com/freedomofpress/securedrop-client/issues/1575
=> Fix user-facing copy mistake

Makefile, test-functional.sh
Run the functional tests in isolation (one by one) [again](https://github.com/freedomofpress/securedrop-client/pull/1525), to work around frequent timeouts that don't happen that way.
Details in the commit message! :speech_balloon:
=> Revert "Remove unnecessary work around segmentation faults :)"

run.sh
Optionally can replace #1652.  Check XDG_SESSION_TYPE and if wayland, set QT_QPA_PLATFORM var when running the client.
Annoyingly, the warning ("Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway") is displayed even when the QT_QPA_PLATFORM environment variable is set.
Activate venv, `run.sh`:
If …
=> Auto-detect Wayland in run.sh

setup.py
Fixes the project's home page url attribute in `setuptools.setup` call in `setup.py`.
None required.
=> change home page url in setup.py

scripts/verify-mo.py
`freedomofpress/securedrop` has stricter linting (ruff) and older typing (Python 3.8) than I tested with in #1666.  This makes `verify-mo.py` compatible with both, after freedomofpress/securedrop#6953.
CI passes.
- I have tested these changes in the appropriate Qubes environment
- I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
If these changes add or remove files other than client code, the AppArmor profile may need to be …
=> chore: make `verify-mo.py` compatible with `securedrop`

Makefile
* urllib3: Same as the last one, we're not concerned with malicious redirects.
* pip: We don't install dependencies from mercurial repositories
=> Ignore urllib3 and pip alerts

client/securedrop_client/locale/messages.pot
Fixes CI failure caused by rotation of the Earth around the Sun by running `make extract-strings`.
=> Run `make extract-strings` to update copyright year

debian/setup-venv.sh
This is mostly a safety measure, as pip will automatically enable require hashes mode when it sees hashes in the requirements.txt file.
Previously we couldn't do this because dh-virtualenv wasn't flexible enough, but we've now dropped that and can do it directly!
Fixes #1791.
=> Use --require-hashes when installing requirements.txt

.github/dependabot.yml
prod dependencies require manual work (building wheels), but we should be fine for dependabot doing dev updates. Unfortunately we have to configure each component manually, oh well.
Fixes #1774.
=> Enable dependabot for Python dev dependencies

.circleci/config.yml
These are failing because of <https://github.com/freedomofpress/securedrop-client/issues/1681>.
Our plan is to just replace them entirely with proxy v2, so just skip these jobs for now so commits can at least get a green check again.
=> Skip CI jobs for proxy on bookworm

.github/dependabot.yml
Refs #1823
These are pinned to the Debian versions and shouldn't be updated. Plus
dependabot errors on them anyways (e.g.
<https://github.com/freedomofpress/securedrop-client/network/updates/786279544>).
In <https://github.com/freedomofpress/securedrop-client/pull/1827#issuecomment-1941820767>
it updated a production dependency, which we don't want. I'm not sure
whether this will have an impact or whether it'll update it regardless
since a dev dependency wants the newer urllib, we'll see.
=> More dependabot config tweaks

scripts/Dockerfile, scripts/build-debs.sh, scripts/dep-check.sh, scripts/image_prep.sh
Ready for review, but depends on #1817 to be merged first.
So far we've been using an ad-hoc image in which the necessary
dependencies are all downloaded at build time, which is nice for tooling
simplicity but adds up the more things we need to download each time.
This adopts the same system used in the SecureDrop server build process.
The tooling builds an image with some dependencies and installs the
minimal Rust toolchain in an image. The image_prop and dep-check scripts
verify all the dependencies are up to date, and rebuild the image if
not.
=> Make Rust toolchain available during package building

.github/workflows/ci.yml, Makefile, client/.githooks/pre-commit, debian/securedrop-keyring.preinst, debian/setup-venv.sh, poetry.lock, proxy/entrypoint.sh, pyproject.toml, scripts/build-debs.sh, scripts/fixup-changelog.sh, scripts/shellcheck.sh, update_version.sh
Copy the `shellcheck.sh` script from the SecureDrop server repository and add it to the central `make lint` target. I added SC2164 as a global exclusion since we don't really care about `cd` potentially failing.
The following fixes are being made:
* client/.githooks/pre-commit: Use $() instead of backticks.
* debian/setup-venv.sh: Ignore quoting words, all the variables are a single word only.
* proxy/entrypoint.sh: Adjust shebang since we use bashisms.
* scripts/build-debs.sh: Set variable and then export it
* scripts/fixup-changelog.sh: Quote our variables, don't use `! -z`.
Fixes #814.
=> Add shellcheck

client/securedrop_client/gui/auth/dialog.py, client/securedrop_client/gui/auth/sign_in/button.py, client/securedrop_client/gui/auth/sign_in/error_bar.py, client/securedrop_client/gui/base/checkbox.py, client/securedrop_client/gui/base/dialogs.py, client/securedrop_client/gui/conversation/export/export_wizard.py, client/securedrop_client/gui/conversation/export/export_wizard_page.py, client/securedrop_client/gui/main.py, client/securedrop_client/resources/__init__.py, client/tests/test_resources.py
pkg_resources is deprecated and we're supposed to use
importlib.resources instead. Unfortunately it's very awkward
to use because it wants to support being able to read from
possibly compressed archives or other Python package distribution
formats.
Since our distribution mechanism is Debian packages, we can avoid
all of this entirely and just read the files off disk like any
other file.
Take the opportunity to simplify font loading: instead of hardcoding
each font, just load every TTF in the fonts/ directory by using a
recursive glob.
And then drop some tests that don't test anything useful
Fixes #1672.
Fixes #1836.
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging …
=> Stop using pkg_resources

debian/control
This was deprecated in bullseye and removed in bookworm. It provided the `gvfs-copy` and `gvfs-rename` commands, which I couldn't find any usage of in our code.
Fixes #1787.
=> Remove gvfs-bin dependency

.github/workflows/build.yml, .github/workflows/piuparts/Dockerfile, .github/workflows/piuparts/run-piuparts.sh, debian/control, debian/securedrop-export.postrm
Ready for review, depends on #1842 first.
I'm mostly posting this because it works and is better than the status quo, but I'm a bit disappointed that we had to exempt nearly half of our packages to the point where this wouldn't have caught, e.g. #1787. I'm also going to play with using a chroot to see if that fixes workstation-config and workstation-viewer, but I don't want to block this on that. 
piuparts tests package installation, upgrade and removal. We don't care
that much about the last one so it's just a warning for now.
For each package, piuparts will install the package CI just built and
ensure that goes smoothly, making sure all the dependencies are present
and the postinst works. Issues that were found are being fixed in the
next commit.
At a later stage, once the released …
=> Have CI run piuparts

.github/workflows/piuparts/run-piuparts.sh, debian/securedrop-export.postrm
Fixes CI failures that shellcheck picked up:
- `run-piuparts.sh` (addressed)
- `securedrop-export.postrm` (suppressed)
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-database-migra …
=> Appease shellcheck (run-piuparts.sh, securedrop-export.postrm)

client/MANIFEST.in, export/MANIFEST.in, log/MANIFEST.in, proxy/MANIFEST.in
These are in fact used, when the package is installed into the virtualenv. (Contrast with SecureDrop server, which installs an empty package into the virtualenv, just copies our file tree over and relies on sys.path modifications to import things.)
This reverts commit 785be31863260c872a48c7226cfc352579693c86.
Fixes #1874.
=> Revert "Remove obsolete MANIFEST.in files"

client/setup.py, debian/securedrop-export.postrm
WIP 
Fixes #1874 
After #1854 and #1844, there were two issues with building packages.  
- `securedrop-export` built successfully, but when installing, postrm generated an error due to not being POSIX compliant
- `securedrop-client` built "successfully" but a number of packages were missing. This was confusing until @cfm pointed me at setup.py, noticing that it specifies packages by name, and does not include all the packages. `MANIFEST.in` was filling that gap for us, which probably wasn't intentional.   
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is required. Please …
=> Use find_packages in securedrop-client setup.py; use bash in securedrop-export postrm 

.github/workflows/build.yml, .github/workflows/cargo-vet.yml, .github/workflows/ci.yml, .github/workflows/sdk.yml, .github/workflows/test.yml
If the branch is not main and not a release branch, then cancel old in-progress jobs.
Reduces the queue size when refactoring or quickly pushing new things.
This is roughly the same behavior CircleCI had.
Inspired by <https://stackoverflow.com/questions/68418857/how-to-cancel-existing-runs-when-a-new-push-happens-on-github-actions-but-only>.
Fixes #1858.
=> Cancel old GHA builds if new commits are pushed

client/tests/gui/test_widgets.py
Instead of randomizing whether we're testing sender_is_current_user or not, just parameterize the test to properly test both cases, which increases coverage and reduces variance.
I noticed this because of ruff in a roundabout way, as it flagged the use of insecure randomization.
If these changes modify the database schema, you should …
=> Parameterize sender_is_current_user in test instead of randomization

client/securedrop_client/gui/conversation/export/export_wizard_page.py, export/README.md, export/securedrop_export/archive.py, export/securedrop_export/disk/cli.py
- Blocked by #1873
Some stragglers:
- Remove `encryption_method` from archive.py (looks like a regression maybe based on rebasing/squashing - was meant to be fully removed during VeraCrypt work)
- Fix UI issue where `EXPORT_ERROR` did not update the UI (Seen once in testing by cfm:  https://github.com/freedomofpress/securedrop-client/pull/1777#pullrequestreview-1894631155) 
- Update export README to include veracrypt instructions and note about compatible printers
And one new change:
- Adjust umask only before writing to the export USB (Fixes #1726) - Per [sec eng approval ](https://github.com/freedomofpress/securedrop-client/issues/1726#issuecomment-1932771841) and discussion with previous sec eng. 
If these changes modify code paths involving cryptography, the opening …
=> Export improvements + documentation

.github/workflows/build.yml, debian/control, debian/rules, debian/securedrop-client.postinst
dh_apparmor generates the appropriate postinst and postrm snippets for (re)loading apparmor profiles in a way that seems more robust than our current usage of `aa-enforce`.
If apparmor isn't enabled, then it gracefully skips instead of aborting the installation. This allows for installing the client package in contexts where apparmor isn't available, like containers. Notably we can now enable piuparts testing for the client.
Fixes #1853.
```
17 profiles are in enforce mode.
...
/usr/bin/securedrop-client <-- this
...
4 processes are in enforce mode.
/usr/bin/dash (10941) /usr/bin/securedrop-client <-- and
/usr/bin/python3.9 (10944) /usr/bin/securedrop-client <-- this
```
=> Use dh_apparmor for installing profile

.github/workflows/build.yml, debian/securedrop-client.lintian-overrides, debian/securedrop-export.lintian-overrides, debian/securedrop-keyring.lintian-overrides, debian/securedrop-log.lintian-overrides, debian/securedrop-proxy.lintian-overrides, debian/securedrop-workstation-config.lintian-overrides, debian/securedrop-workstation-viewer.lintian-overrides, debian/source/lintian-overrides, debian/source/options, scripts/build-debs-real.sh, scripts/build-debs.sh, scripts/lintian/Dockerfile
lintian is the Debian package linter and catches a number of things we can improve in our packages. For now I've suppressed everything and annotated them with TODO/FIXME for others to take on or address incrementally.
lintian is run at the end of `make build-debs` unless the "FAST" environment variable is set. Any warning or error causes the build to fail, but it can be suppressed in the corresponding lintian-overrides file.
Internally there's a bit of work so we can identify the *.changes file that we just built, so we first build into a temporary directory, copy the files into our repository's build, then run lintian in the temporary directory.
Refs #1785.
=> Run lintian on Debian packages

client/securedrop_client/gui/conversation/export/export_wizard_constants.py, client/securedrop_client/locale/messages.pot
Also add a space in between the period next sentence for ERROR_EXPORT_CLEANUP.
=> Fix typos in export_wizard_constants.py

client/.githooks/pre-commit, client/Makefile, client/README.md
Closes #1673 by removing the pre-commit hook for `make check-strings`, which will now be enforced by CI.
Visual review.
=> chore: remove pre-commit hooks

client/securedrop_client/gui/conversation/export/export_wizard_constants.py, client/securedrop_client/locale/messages.pot, export/securedrop_export/disk/cli.py, export/tests/disk/test_cli.py, export/tests/lsblk_sample.py
Addresses QA feedback in https://github.com/freedomofpress/securedrop-client/issues/1867#issuecomment-1991887267
* Remove backticks on the word "sd-devices" in a user-facing error message (note: I looked into monospaced fonts and formatting alternatives, but didn't want to introduce a new UI/font style that we don't use elsewhere in the client, for consistency. Open to revisiting this later though)
* Support export to an unlocked unpartitioned drive (scenario: the whole block device has been encrypted and is already unlocked when the user launches the wizard)  
Note: I have already built debs and run through the following, but would include basic functionality testing in the test plan.
If these changes modify code paths involving cryptography, the opening of files in VMs …
=> Support unlocked unpartitioned VeraCrypt block device for export

client/securedrop_client/gui/conversation/export/export_wizard_constants.py, client/securedrop_client/locale/messages.pot, export/securedrop_export/disk/cli.py, export/tests/disk/test_cli.py, export/tests/lsblk_sample.py
=> [0.10.0] Backport "Support unlocked unpartitioned VeraCrypt block device for export"

debian/rules
We already delete the individual .pyc files because they're not reproducible, but leave behind empty `__pycache__` folders. This can be annoying if people are doing builds out of a development checkout that has these folders that won't be present on a pristine build.
So remove the empty folders right after deleting the .pyc files.
Fixes #1907.
If these changes add or remove files other than client code, the AppArmor profile may need to be updated. Please check as …
=> Remove __pycache__ folders from packages

debian/rules
=> [0.10.0] Backport "Remove __pycache__ folders from packages"

client/Makefile, client/securedrop_client/locale/messages.pot
leave `VERSION` constant in a header in .pot files rather than the actual version string, since that header isn't in use. 
See https://github.com/freedomofpress/securedrop/pull/7034 for prior context 
[self-contained]: …
=> Exclude client version string from Project-Id-Version of .pot files

client/Makefile, client/securedrop_client/locale/messages.pot
=> [0.10.0] backport 1915 (Exclude client version string from localization files)

export/securedrop_export/disk/cli.py, export/tests/disk/test_cli.py
Fixes file permissions on USB export drive (ref #1726 and adds test case. The initial change (in #1777) correctly changed the permission on the export directory, but not on the files being copied into that directory.
```
$ mkdir -p /tmp/export/export_data/
$ echo "foo" > /tmp/export/export_data/test.txt
$ python3
>> from securedrop_export.disk.cli import CLI
>> cli = CLI()
>> usb = cli.get_volume()  # will show you have a MountedVolume object attached
>> cli.write_data_to_device(usb, "/tmp/export", "test")
>> # Command succeeds, usb is locked/unmounted, and contains a folder called "test" with `export_data/test.txt` in it, with 644 permissions
```
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) …
=> Ensure files on USB have read permissions, not just enclosing directory.

pyproject.toml
`make bandit` reports results from the root project venv, if it's located in the project root.  Filing this as a draft - if we want to instead instruct people to use a cache dir outside of the project root for poetry environment, we should add setup notes to the readme
If these changes modify the database schema, you should include a …
=> Exclude root project .venv from bandit

.github/workflows/test.yml
Better mimics the Qubes VM environment. I didn't set up passwordless-sudo (like Qubes) since it isn't needed right now.
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-database-migr …
=> Run tests as not-root

export/securedrop_export/disk/cli.py, export/tests/disk/test_cli.py
=> [0.10.0] Backport "Ensure files on USB have read permissions, not just enclosing directory."

.github/workflows/test.yml
=> [0.10.0] Backport "Run tests as not-root"

client/securedrop_client/gui/conversation/export/print_transcript_dialog.py, client/tests/gui/conversation/export/test_print_transcript_dialog.py
Fixes Print Transcript failure (0.10.0)
Fixes https://github.com/freedomofpress/securedrop-client/issues/1937
=> Let parent handle PrintTranscriptDialog dialog close 

client/securedrop_client/gui/conversation/export/print_transcript_dialog.py, client/tests/gui/conversation/export/test_print_transcript_dialog.py
=> [0.10.1] Backport "Let parent handle PrintTranscriptDialog dialog close "

scripts/backport.py
Introduced in <https://github.com/freedomofpress/securedrop/pull/6875>, makes creating backport PRs much easier.
=> Copy the backport.py script from securedrop server

Makefile
This port's @cfm's <https://github.com/freedomofpress/securedrop/pull/6787> with a little less abstraction.
Fixes #1789.
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-database-mig …
=> Automatically collect package build log with `script`

client/files/securedrop-client, debian/securedrop-client.postinst, debian/securedrop-export.postinst, debian/securedrop-keyring.postinst, debian/securedrop-workstation-config.postinst
Just use bash unconditionally for its nicer features, there's very little advantage to using dash at our scale.
Fixes #1878.
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-database …
=> Use bash for all Debian packaging scripts

debian/control
=> Install debian package requirements via sdw-config

.github/workflows/nightlies.yml
Instead of needing to wait up to 24 hours for nightly packages to be built, just do it instantly. This will allow for faster development cycles because securedrop-apt-test will now reflect what is in "main", making securedrop-workstation CI more useful too.
The only thing we need to add after the push trigger is a concurrency limiter so multiple jobs aren't pulling/pushing to the build-logs and securedrop-apt-test repositories at the same time.
Fixes #1959.
If these …
=> Push "nightly" after each merged PR

debian/control
Fixes #1956 for real this time.
Qubes `qubes-core-agent-passwordless-root` is installed separately in template via the `qubes-vm-recommended` metapackage, so it's removed from here.
=> Remove Qubes-specific package from securedrop-workstation-config dependencies

.github/workflows/build.yml, .github/workflows/cargo-vet.yml, .github/workflows/ci.yml, .github/workflows/sdk.yml, .github/workflows/test.yml
Ready for review, needs discussion
We need to also trigger on the "merge_group" event for GitHub's merge queue to work. This is the same as <https://github.com/freedomofpress/securedrop-dev-docs/pull/130>.
=> Enable "merge_group" events for GitHub's merge queue

client/README.md
Update python version referenced in readme.  Refs https://github.com/freedomofpress/securedrop-client/pull/1958 
Visual review
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-databa …
=> Update readme to reference python3.11

poetry.lock
jinja is a dependency of safety, so update it to address CVE-2024-34064.
I doubt safety is affected, but upgrading was easier than checking.
This does not upgrade jinja for use in the client, which is not affected by this vulnerability.
=> Upgrade jinja to 3.1.4 (dev tools)

Makefile
Fixes #1993.
```sh-session
$ rm -rf build
$ make build-debs  # ^C at will... ;-)
```
=> build(`build-debs`): create `build/` directory before calling `script`

log/README.md
@deeplow and I have walked through the `log/` portion of this repository and mapped out:
- what spawns what services;
- what triggers what RPCs; and
- what reads/writes from/to what.
It should be descriptive and uncontroversial, except that we couldn't account for:
1. `securedrop-log`, which nothing in either `securedrop-client` or `securedrop-workstation` appears to invoke; or
2. `securedrop_log`, which nothing in either `securedrop-client` or `securedrop-workstation` appears to load.
Are they remnants of an earlier implementation, before the `securedrop-redis-log → securedrop-log-saver` buffering pipeline and the `sd-rsyslog → qrexec securedrop.Log` RPC?
=> docs(readme): add architecture diagram

debian/control
xterm is barely usable as a terminal, so install xfce4-terminal so we can use modern features like copy and paste.
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-database-migration …
=> Install xfce4-terminal in all VMs for debugging

.github/workflows/cargo-vet.yml, .github/workflows/ci.yml, .github/workflows/security.yml, .github/workflows/test.yml, Cargo.toml, rust-toolchain.toml, scripts/Dockerfile
The "release" profile now strips debuginfo[1], so we need to re-enable it so
the Debian packaging can strip it and ship it in a separate dbgsym package.
[1] https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#enable-strip-in-release-profiles-by-default
Fixes #2024.
If these changes modify the database schema, you should include a …
=> Upgrade Rust toolchain to 1.78.0

.github/workflows/build.yml, .github/workflows/piuparts/Dockerfile, .github/workflows/piuparts/run-piuparts.sh, debian/control
For some reason dh_shlibs can't automatically parse the libqubesdb dependency, so specify it manually for now.
To make piuparts happy, we need to enable the Qubes apt repository. While we're at it, also enable the SD apt repository using the .sources file too, instead of downloading the signing key and using the old line .list format.
If …
=> Add missing qubesdb dependencies, fix piuparts

.github/workflows/sdk.yml
We just need a tool to wait until the HTTP service is working, and it turns out we can use curl for that by running it in a one-line bash loop, avoiding the need to download and extract dockerize.
This approach was inspired by the securedrop.org repository CI.[1]
[1] https://github.com/freedomofpress/securedrop.org/blob/6df3cd790a8cdc7409585c30813d01a5f6a5c37c/.circleci/config.yml#L59
Fixes #1999.
=> Use curl instead of dockerize in SDK CI

log/setup.py
This was a bad collision between 588988a ("Remove unused securedrop-log code") and 90424f8 ("log: reorganize code to split server from client").
The first commit removed all the Python packages from the securedrop-log component, removing the discovery of packages was needed. The second commit created a new Python package with the log_server code, and relied on the line being present.
This reverts the removal in 588988a.
If these changes add or remove files other than …
=> Re-instate Python package discovery in securedrop-log's setup.py

Makefile
Same as <https://github.com/freedomofpress/fpf-misc-resources/pull/46>, where I wrote:
>  To quote a jinja2 maintainer: "This CVE is a bad joke"[1].
> 
> We don't use the vulnerable functions anyways.
> 
> [1] https://bugzilla.redhat.com/show_bug.cgi?id=1677653#c4
=> Ignore bogus CVE-2019-8341

debian/rules, debian/securedrop-proxy.install, proxy/usr.bin.securedrop-proxy
Because this is a static Rust binary, it ends up being super simple, we just need to import the abstractions for DNS, OpenSSL and TLS certs.
Fixes #1889.
```diff
diff --git a/proxy/src/main.rs b/proxy/src/main.rs
index d1cb6563..64fd25dd 100644
--- a/proxy/src/main.rs
+++ b/proxy/src/main.rs
@@ -162,6 +162,15 @@ async fn proxy() -> Result<()> {
#[tokio::main(flavor = "current_thread")]
/// Entry-point: Every invocation handles a single request via `proxy()` and exits according to its success or failure.
async fn main() -> ExitCode {
+    if std::env::args().any(|arg| arg == "--apparmor-test") {
+        println!(
+            "{}",
+            std::fs::read_to_string("/var/lib/qubes/first-boot-completed")
+                .unwrap()
+        );
+ …
```
=> Add AppArmor profile for securedrop-proxy

.github/dependabot.yml
dependabot times out when trying to do all of our updates at once. This is still a beta feature, so let's go back to the old way that at least worked while GitHub fixes this.
This reverts commit 7933d2252d894ba60243ece12267417ea5cec443.
This reverts commit 87c09f9ff9b2e894a06e53be4b165a40b18e9652.
=> Revert "Consolidate pip dependabot updates into a single PR"

Cargo.lock, proxy/Cargo.toml, proxy/src/main.rs, proxy/tests/test_errors.py, supply-chain/audits.toml, supply-chain/imports.lock
There's a small change in how reqwest errors are printed (see <https://github.com/seanmonstar/reqwest/pull/2199>), so handle that in our code and update one test accordingly.
Import a number of audits and trust markers, and the rest have been audited.
Fixes #1985.
If these changes modify the database schema, you should include a database …
=> Upgrade reqwest to 0.12

debian/securedrop-whonix-config.securedrop-whonix-config.service
Towards freedomofpress/securedrop-workstation#1051, wraps the two commands in `securedrop-whonix-config`'s `ExecStartPost` directive in `bash -c`.  (We had this at some point last week; I think it got lost in a rebase.)
- I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
- These changes should not need testing in Qubes
=> fix: two-part `ExecStartPost` needs `bash -c`

client/Makefile
Refs https://github.com/freedomofpress/securedrop-client/pull/2053
=> Exclude Babel header from i18n diff in `make check-strings` 

.github/workflows/sdk.yml, client/securedrop_client/config.py, client/securedrop_client/sdk/__init__.py, client/tests/sdk/README.md, client/tests/sdk/data/test_download_submission_autoresume.yml, client/tests/sdk/data/test_download_submission_autoresume_fail.yml, client/tests/sdk/data/test_download_submission_stream_404.yml, client/tests/sdk/test_api.py, client/tests/sdk/utils.py, client/tests/test_config.py
Will fix #1994.
I've primarily edited `API.download_submission`. There's a big code block the only runs if `self.proxy` is False, and if the proxy is in use it doesn't do anything yet. I'll still need to make this work with proxy v2.
The change works like this: The output file is opened for writing at the beginning, and then there's a loop that continues until the download is complete, or it has been retried 3 times. (I have a comment to make `RETRY_LIMIT` configurable, but it's hard-coded right now.)
Inside this loop, it tries to download the submission by sending the correct request to `self._send_json_request`. I've made it so `stream=True` is passed to `requests.request` on the download requests, which means the `requests.request` call returns immediately, but the …
=> Auto-resumed failed downloads

debian/control, debian/securedrop-whonix-config.securedrop-whonix-config.service
Fixes <https://github.com/freedomofpress/securedrop-workstation/pull/1051#pullrequestreview-2097483051>.
1. [ ] Build `securedrop-whonix-config`.
2. [ ] Install directly into `whonix-gateway-17`.
3. [ ] On `sd-whonix`, `systemctl securedrop-whonix-config` shows a successful execution.
Or follow the test plan in <https://github.com/freedomofpress/securedrop-workstation/pull/1051#issue-2322099098>.
- I do not have an appropriate Qubes OS workstation set up (the reviewer …
=> fix(`securedrop-whonix-config`): depend on `anon-gw-anonymizer-config`

workstation-config/paxctld.conf
Otherwise grsec will stop it, see <https://github.com/freedomofpress/securedrop-client/issues/2037#issuecomment-2135222922>.
Fixes #2037.
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-run …
=> Allow nautilus to have RWX memory

.github/workflows/build.yml, Makefile
ready for review
Refs #2049 
- pins securedrop-builder version to allow building pre-RiiR sd-proxy packages.
=> [0.10.2] Pin builder version for builds at pre-rust-proxy ref

changelog.md
Update changelog for 0.10.2-rc1
Refs #2049
=> [0.10.2-rc1] Update changelog

client/securedrop_client/export.py
=> Fix print preflight status check

workstation-config/mimeapps.list.sd-viewer
Fixes freedomofpress/securedrop-workstation#1138 by setting Totem as the default application for `video/webm` files.
1. Apply this patch in `sd-large-bookworm-template`'s `/opt/sdw/mimeapps.list-sd-viewer`
2. Submit a `.webm` file to your SecureDrop test instance
3. Download it in the Client
4. Open it
5. [ ] The video plays in Totem in a disposable VM
- I do not have an appropriate Qubes OS workstation set up (the reviewer will need to test these changes)
- These …
=> fix(`sd-viewer`): open `.webm` videos in Totem

changelog.md, workstation-config/mimeapps.list.sd-viewer
=> [0.11.0] Backport "fix(`sd-viewer`): open `.webm` videos in Totem"

client/scripts/verify-mo.py
It now needs to suppress the `shell=True` line instead of the whole subprocess function call.
Fixes #2122
=> Adjust location of semgrep override

export/securedrop_export/print/service.py, export/tests/print/test_service.py
Fixes #2119
- Use check_call instead of check_output if don't need output
- Rename `safe_check_call` to `safe_check_output` for clarity, since that's what it does
Note: `safe_check_output` will error if stderr is not empty OR in a list of predefined messages of which we're aware. For example, we use this to suppress lpadmin warnings about printer drivers reaching deprecation. (:grimacing: ). 
In this case, one of our dependencies printed a console warning, and `safe_check_output` rightly complained. I could have continued to use that method and just added an `ignore_stderr_startswith` but that feels brittle, it depends on the error string never changing.
The next thing we should do is move to a fully modern supported print workflow, as we have discussed in a few places. …
=> Use check_call instead of check_output where output is not required

client/securedrop_client/gui/conversation/export/export_wizard.py, client/securedrop_client/gui/conversation/export/export_wizard_page.py
- Disable Continue button while export QProcess is running, in addition to staying on the current page. This prevents the issue of a doubleclick or button-mash moving the wizard to a failure state (#1926, #2098). 
- Display error hint on Export Failed screen (#2098)
- (small refactor: default behaviour of `update_content` is to show error hints, since that's what we want in all cases except the final screen)
Fixes #2098 , Fixes #1926
see https://github.com/freedomofpress/securedrop-workstation/issues/1103#issuecomment-2217204131
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any …
=> Avoid export failure with extra button-presses; show helpful error message on every Export Wizard Screen 

Cargo.lock, Makefile, supply-chain/imports.lock
Could lead to undefined behavior; see <https://rustsec.org/advisories/RUSTSEC-2024-0357> for details.
=> Upgrade `openssl` crate for RUSTSEC-2024-0357

client/securedrop_client/gui/base/dialog_button.css, client/securedrop_client/gui/base/dialogs.css, client/securedrop_client/gui/conversation/export/print_dialog.py, client/securedrop_client/gui/conversation/export/print_transcript_dialog.py
Fixes #2125
The easiest way to test may be to give sd-app network access, install all required dependencies, check out this branch in `sd-app`, and run `./run.sh --sdc-home=/home/user/.securedrop_client` with the venv activated, although you can also build from the tip of this branch and install the deb in sd-app.
If these changes modify …
=> Add more UI feedback to print, print transcript dialogs

debian/control
The svs-disp package was made obsolete in Oct. 2020 (https://github.com/freedomofpress/securedrop-builder/pull/198), and given the fresh installs for both 4.1 and 4.2 since then, there's no need to continue keeping the Provides/Conflicts/Replaces stanzas.
If these changes modify the database schema, you should include a database …
=> Remove references to obsolete securedrop-workstation-svs-disp package

debian/control, debian/securedrop-client.lintian-overrides
The client package contains a few complied Python extensions (markupsafe and SQLalchemy), which contain debug symbols that can be stripped out to a dbgsym package.
The automatic shlibs dependency also sets a versioned dependency on libc based on the compiled files.
Fixes #1848.
=> Switch securedrop-client to Architecture: any

client/securedrop_client/api_jobs/downloads.py, client/securedrop_client/gui/widgets.py, client/tests/api_jobs/test_downloads.py
DownloadDecryptionException is specially handled in Controller.on_file_download_failure(), so if we raise a different exception class, the download animation will never be stopped because file_missing is never emitted.
It is worth a proper re-examination of our exception heirarchy and reducing the amount of indirection in the download flow, but that can be done outside of a hotfix.
More debug logging is added to trace when slots are triggered.
Refs #1633.
Without this PR:
With this PR:
=> Have BaseErrors trigger DownloadDecryptionException in download flow

client/securedrop_client/api_jobs/downloads.py, client/securedrop_client/gui/widgets.py, client/tests/api_jobs/test_downloads.py
=> [0.13.2] Backport #2196: Have BaseErrors trigger DownloadDecryptionException in download flow

client/run.sh
Instead of requiring the user to tail the logs in a separate process, just have run.sh do it for us.
=> Have run.sh automatically emit full debug logs

client/securedrop_client/api_jobs/sync.py
Ironically calling `logging.warn` triggers warnings that it's deprecated, use the full warning instead.
=> Don't use deprecated `logging.warn`

scripts/build-debs.sh
If HEAD points to a tag, then run it through `git tag -v` to print the tag's signature instead of just the commit's.
=> Have `make build-debs` print tag signature, if any

client/securedrop_client/gui/base/dialog_button.css
Add hover state to ModalDialog.dangerous button styling, used for Delete Source dialog confirmation.
There was no hover colour branding guideline for Cantankerous Coral that I could find in our ux resources, so I have chosen a very slightly different coral shade arbitrarily based on trying to keep the same saturation and not add more colours to the palette. I am not a designer. I do not have strong opinions on colour. The most important thing is that the destructive action's _non_-default button (the destructive action) undergoes a high-contrast change (white background, coral text -> coral background, white text) when moused over, to give as much feedback as possible to the user. 
If these changes modify code paths involving cryptography, the opening of files in VMs or …
=> Add hover styling to ModalDialog.dangerous (destructive) buttons

client/securedrop_client/gui/actions.py, client/securedrop_client/gui/source/delete/dialog.py, client/securedrop_client/locale/messages.pot, client/tests/gui/source/delete/test_dialog.py, client/tests/gui/test_widgets.py
Refactor DeleteSourceDialog so it takes a set of sources instead of a single source. Display a user-friendly error message if the empty set is provided. Add parameterized unit tests to test empty, n=1, and n>1 conditions. This does not include any actual batch delete functionality, but it is in preparation for that change.
I was tempted to also refactor the DeleteSource and DeleteConversation dialogs into one dialog element, since there's no reason not to and is in line with what we did on the Print, Print Conversation, and Print Transcript dialogs, but I think it's too much scope creep. But it would be a straightforward refactor PR later on if anyone wants to take it on.
This PR makes minor string changes that will need il8n.
Towards #2160 
If these changes modify code …
=> Refactor DeleteSourceDialog so it accepts Set[Source]

client/tests/sdk/test_api.py
Fixes #2223 by teaching `test_download_submission_autoresume()`'s `StubbedStderr` mock to report the actual `Content-Length` header of the pre-mocked response.  Otherwise, the test will fail if the pre-mocked response is smaller than the hard-coded value.
1. Start a SecureDrop development server with no `LOADDATA_ARGS`: just `make dev`.
2. `make regenerate-sdk-cassettes` succeeds.
=> fix(`test_download_submission_autoresume`): don't hard-code mock's `Content-Length` header

client/securedrop_client/gui/main.py, client/securedrop_client/gui/widgets.py, client/tests/functional/test_offline_delete_source.py, client/tests/functional/test_offline_star_source.py, client/tests/gui/test_main.py, client/tests/gui/test_widgets.py, client/tests/integration/test_styles_sdclient.py
Move Status pane ("top pane") to the bottom of the app, and rename.
Towards #2160
Refs https://github.com/freedomofpress/securedrop-client/issues/2160#issuecomment-2341456728 
[self-contained]: …
=> Move Top Pane to Bottom

proxy/tests/conftest.py, proxy/tests/test_errors.py, proxy/tests/test_proxy.py, pyproject.toml
We had temporarily disabled it until proxy v2 landed, which has now happened!
=> Re-enable ruff in proxy/ folder

.github/workflows/build.yml, .github/workflows/cargo-vet.yml, .github/workflows/ci.yml, .github/workflows/sdk.yml, .github/workflows/test.yml
Hopefully this will help us avoid unclear failures, see <https://github.com/freedomofpress/securedrop-client/issues/1880#issuecomment-2364080506>.
=> Don't have CI cancel GitHub merge queue jobs

debian/control, debian/securedrop-client.lintian-overrides, debian/securedrop-export.lintian-overrides, debian/setup-venv.sh
For our purposes, venv should be a drop-in replacement for virtualenv, with the advantage that it's maintained in the standard library and is a bit slimmer. Diffoscoping shows internal changes to the activation scripts and entry points but nothing that should functionally affect us.
SecureDrop server is already using venv for its packages, so this brings us into alignment.
Also do a little cleanup on the dependencies because lintian started complaining a bit more; ensure that both securedrop-client and securedrop-export have explicit `python3` dependencies, and remove the now obsolete `${python3:Depends}` magic dependencies.
=> Switch to builtin venv instead of virtualenv

client/securedrop_client/sdk/__init__.py
Add more debug and error logging to make it easier to trace why things have failed.
Roughly, every failure branch should have an error-level log entry. In some cases where knowing additional context would be useful, a debug-level entry is also created with unredacted information.
Fixes #2206.
If these changes modify the database schema, …
=> Improve logging of API failures

client/.semgrep/custom-rules.yml, client/securedrop_client/gui/actions.py, client/securedrop_client/gui/main.py, client/securedrop_client/gui/shortcuts.py, client/securedrop_client/gui/widgets.py, client/tests/gui/test_shortcuts.py
If you have two shortcuts that point to the same key combo, you'll get "QAction::event: Ambiguous shortcut overload: <sequence>" in the logs and neither action will be taken.
Centralize them in one place so it's easy for humans to spot duplicates. A test verifies uniqueness as well.
A semgrep rule enforces that people use the new Shortcuts enum instead of just writing the sequence in the function call directly.
=> Verify client shortcuts are unique

Cargo.lock, supply-chain/audits.toml, supply-chain/imports.lock
futures-util 0.3.30 was yanked because it had a use after free, see <https://github.com/rust-lang/futures-rs/pull/2886>.
=> Upgrade futures- crates to 0.3.31 to fix use after free

client/securedrop_client/gui/widgets.py, client/securedrop_client/logic.py, client/securedrop_client/storage.py, client/tests/functional/data/test_deleted_file_filewidget.yml, client/tests/functional/test_deleted_file_filewidget.py, client/tests/gui/test_widgets.py, client/tests/test_logic.py, client/tests/test_storage.py
Fixes #2217 by ensuring that database queries expecting exactly one File, Message, or Reply are error-handled. Note: This is a deliberately limited-scope fix; a broader discussion about database error-handling improvements will happen in https://github.com/freedomofpress/securedrop-client/issues/2222
- Reproduce #2217 and ensure no app crash:
- Enable debug logs on the client. Submit a large file for a source (or a normal size file but use [toxiproxy](https://github.com/freedomofpress/securedrop-client/wiki/Developer-Tips-&-Tricks#faking-a-slow-network-in-client-dev) so that your download speed is limited).
- Begin downloading the file, then quicky, before the download can complete, delete the source.
If these changes modify code paths involving cryptography, the opening …
=> Improve error-handling for deleted files, messages, and replies

client/securedrop_client/api_jobs/downloads.py
Our error handling expects that failures from DownloadJobs raise DownloadExceptions, so let's do that.
This is roughly the same concept as a9f0590f746a, just in a different part of the code. The exception handling has to exist in each class (instead of `one_or_none()`) because we need to know the corresponding type to pass to DownloadException.
Fixes #2274.
=> Handle get_db_object() failures as DownloadException

client/MANIFEST.in
Adds support for the `fr` locale in securedrop-client
=> Add support for the fr locale

changelog.md, debian/changelog
Towards #2282 - adds changelog for 0.14.0-rc1
=> Prepare  0.14.0-rc1 version bump

client/securedrop_client/gui/source/delete/dialog.py, client/tests/gui/source/delete/test_dialog.py
Fixes #2290.
Hides disabled CONTINUE button on delete sources dialog when no sources are selected.
- start the client and select and delete a source
- without selecting another source, click DELETE SOURCES
n/a
=> [0.14.0] Hide continue button on delete dialog if no sources selected.

client/securedrop_client/gui/source/delete/dialog.py, client/tests/gui/source/delete/test_dialog.py
=> [0.14.0] Backport "[0.14.0] Hide continue button on delete dialog if no sources selected."

client/securedrop_client/gui/source/delete/dialog.py, client/securedrop_client/locale/messages.pot, client/tests/functional/data/test_confirm_before_deleting_lots_of_sources.yml, client/tests/functional/test_delete_sources.py
Closes #2297 by blocking the `DeleteSourceDialog`'s "continue" button for 5 seconds, with a countdown timer.
This can be tested easily with `make dev` with:
```patch
--- a/client/securedrop_client/gui/source/delete/dialog.py
+++ b/client/securedrop_client/gui/source/delete/dialog.py
@@ -27,7 +27,7 @@ from securedrop_client.gui.base import ModalDialog
-LOTS_OF_SOURCES = 30
+LOTS_OF_SOURCES = 2
SEC = 1000  # ms
```
Then:
1. [ ] With 1 or 2 sources selected, the `Yes, delete N source accounts button` is immediately enabled and works as expected.
2. [ ] With all 3 sources selected, the `Yes, delete N source accounts button`:
1. [ ] is initially disabled;
2. [ ] counts down from 5 seconds; and then
3. [ ] becomes enabled and works as expected.
=> feat(`DeleteSourceDialog`): when lots of sources are selected for deletion, block the continue button for 5 seconds

client/securedrop_client/gui/actions.py, client/securedrop_client/gui/source/delete/dialog.py, client/securedrop_client/gui/widgets.py, client/securedrop_client/locale/messages.pot, client/securedrop_client/logic.py, client/tests/gui/source/delete/test_dialog.py, client/tests/gui/test_actions.py, client/tests/gui/test_widgets.py, client/tests/integration/conftest.py
Fixes #2298.
- start client pointed at a dev instance with ~100 sources
=> Add warning when all sources are selected for deletion

client/securedrop_client/config.py, client/securedrop_client/sdk/__init__.py, client/tests/sdk/README.md, client/tests/test_config.py
Instead of using a custom `/etc/sd-sdk.conf` for setting a custom proxy VM, use our now established pattern of using QubesDB or the environment.
I am somewhat dubious of the use case of using a different proxy VM, but I can see how it could be useful for some debugging operations.
Update and remove a lot of documentation around updating VCR cassettes that was outdated but referenced this configuration mechanism.
Fixes #2040.
=> sdk: Configure custom proxy VM via QubesDB/env; update docs

.github/workflows/cargo-vet.yml, supply-chain/audits.toml, supply-chain/config.toml, supply-chain/imports.lock
It wanted to perform some trivial reordering of the audits file.
Refs <https://github.com/freedomofpress/securedrop-tooling/issues/17>.
=> Upgrade to cargo-vet 0.10.0

client/securedrop_client/gui/conversation/export/export_wizard_constants.py, client/securedrop_client/locale/messages.pot, export/README.md, export/files/application-x-sd-export.xml
Addresses [translators' feedback](https://weblate.securedrop.org/translate/securedrop/securedrop-client/en/?checksum=febe74af3844dfa9#comments) that referring to export "devices" (as opposed to "drives") is ambiguous, especially out of context.
*This pull request is a proposal,* on the grounds that it will take no more time to review this proposed solution than to talk about the problem it tries to solve.  Feel free to close this or suggest alternatives.
=> chore: standardize on "drive" for USB export devices

client/Makefile, client/README.md, client/poetry.lock, client/pyproject.toml, client/run.sh
Fixes #2333.
Updates pyproject.toml to install a later version of PyQt5 - but only for macOS. Slightly later versions provide arm64 wheels, which makes installing the development environment a **lot** easier.
As arm64 PyQt5 wheels are only available for slightly later versions - install the latest possible version for macOS (darwin), but leave Linux packages at the specific pinned version (so it keeps it in sync with Debian bookworm).
Happy to tweak this if needed, and I understand this isn't your primary target environment if the change isn't wanted.
- Check that the development client works under macOS without x86_64 Homebrew (screenshot attached from me running it, it's not perfect UI wise - but it works)
- Check that installing under Linux does **not** install …
=> Update macOS support to run on arm64

export/files/send-to-usb.desktop
I think this will fix https://github.com/freedomofpress/securedrop-workstation/issues/1123 . Qubes sanitizes desktop files to [only allow certain characters](https://github.com/QubesOS/qubes-desktop-linux-common/blob/b0e1172a92cba584c652351f6a3df4dea609f0ea/qubesappmenus/receive.py#L62), and we're violating that in the `Name` field, where we use quotation marks.
If these changes add or remove files other than client code, the AppArmor profile may need to be updated. …
=> Remove quotation marks around .desktop entry name

client/securedrop_client/app.py, client/securedrop_client/export.py, client/securedrop_client/gui/base/misc.py, client/tests/api_jobs/test_base.py, client/tests/gui/conversation/delete/test_dialog.py, client/tests/gui/test_main.py, client/tests/gui/test_widgets.py, client/tests/integration/test_styles_sdclient.py, client/tests/test_app.py, client/tests/test_logic.py, client/tests/test_queue.py, client/tests/test_storage.py, export/securedrop_export/disk/service.py, export/securedrop_export/print/service.py, log/log_server/log_saver.py, pyproject.toml
bugbear was one of the most popular flake8 plugins and now ruff supports it. Running it found a number of missing "assert" statements, among other issues I all found valuable to fix:
* Useless statements that were probably missing a leading "assert"
* Mutable default arguments that should be constructed at function runtime
* Unused loop variables that don't start with _
* Usage of str.strip() with a multi-character string
I suppressed four types of errors:
* Raising an exception inside an exception handler without using `from err`; would be nice to address later, but there were too many to assess.
* Loop variables being bound past their lifetime; the two uses were only in tests and safe so I applied individual suppressions as we'd want to flag problematic uses in real …
=> Enable ruff's flake8-bugbear ruleset

client/setup.py, export/setup.py, log/setup.py
These are outdated since we now require Python 3.11, and in the case of the client, will pull in the old securedrop-sdk package that we no longer use.
=> Remove outdated setuptools install_requires and python_requires

Makefile
Ignores Safety alert no. 74735 (CVE-2024-56201) in `jinja2` per freedomofpress/fpf-misc-resources#60.
=> chore: ignore CVE-2024-56201 in `jinja2`

.github/workflows/cargo-vet.yml, .github/workflows/ci.yml, .github/workflows/security.yml, .github/workflows/test.yml, rust-toolchain.toml, scripts/Dockerfile
No changes appear needed.
Fixes #2355.
=> Upgrade Rust toolchain to 1.84.1

changelog.md, client/securedrop_client/api_jobs/uploads.py, client/securedrop_client/sdk/__init__.py, client/tests/api_jobs/test_uploads.py, client/tests/sdk/test_api.py, debian/changelog, log/log_client_files/sd-rsyslog, log/log_server/log_saver.py, log/log_server/redis_log.py
Cherry-pick commits from 0.14.1 release to main. Note that some commits have multiple cherry-pick tags because they were first cherry-picked to the release branch and then back to main 🙃 .
One extra commit to bump the date for the rc changelog entry to make lintian happy.
=> Backport 0.14.1

client/poetry.lock, client/securedrop_client/api_jobs/downloads.py, client/securedrop_client/gui/base/__init__.py, client/securedrop_client/gui/base/progress.py, client/securedrop_client/gui/widgets.py, client/securedrop_client/logic.py, client/securedrop_client/sdk/__init__.py, client/securedrop_client/utils.py, client/tests/api_jobs/test_downloads.py, client/tests/gui/base/test_progress.py, client/tests/gui/test_widgets.py, client/tests/integration/test_styles_file_download_button.py, client/tests/sdk/utils.py, client/tests/test_utils.py
TODO:
* Visual alignment issue; need padding on the right side
Display a vanilla progress bar for file downloads that simply shows how much of the file has been downloaded so far.
A new FileDownloadProgressBar widget replaces the existing animated spinner, and we inject a signal through to the SDK to pass the current progress back to the widget.
The widget both displays the overall total progress as a percentage and also calculates the download speed by using an exponential moving average to smooth it out. A timer runs every 100ms to recalculate the speed.
A new utils.humanize_speed() is used to translate the raw bytes/second into a human-readable version with a focus on keeping the length of the string roughly consistent so there's less visual shifting.
Once the download …
=> Display download progress for file downloads

client/securedrop_client/gui/base/progress.py, client/tests/gui/base/test_progress.py
The current 100ms refresh is too fast to actually read the numbers, so slow it down to 1s, which is roughly what browsers do. We continue to calculate speed at a 100ms interval to have good smoothing.
Refs <https://github.com/freedomofpress/securedrop-client/issues/1104#issuecomment-2825726618>.
Refs <https://github.com/freedomofpress/securedrop-client/issues/1104#issuecomment-2826921573>.
If these changes add or remove files other than client code, the AppArmor …
=> Visually update download progress bars every second

client/securedrop_client/gui/widgets.py
If you make the client window as narrow as it can go, when a progress bar is displayed, the "Downloading" text gets cutoff, because there isn't enough space for all the different elements to be displayed.
Make it fit by hiding the "Encrypted file on server" text during the download. If the download fails, it'll get restored by the existing `_set_file_state()`.
Fixes #2423.
If these changes add or remove files other than client code, the AppArmor profile may need to be …
=> Make progress bars fit in narrow windows

scripts/build-debs.sh
See <https://github.com/freedomofpress/securedrop/pull/7478#discussion_r2008409253>, and review along with freedomofpress/securedrop#7478.
=> build: replicate `freedomofpress/securedrop`'s verification of head, tag, and working tree

.github/workflows/test.yml, debian/control, debian/setup-venv.sh, export/Makefile, export/poetry.lock, export/pyproject.toml, export/securedrop_export/print/print_dialog.py, export/securedrop_export/print/service.py, export/tests/print/test_service.py
Ready for review. Should wait for https://github.com/freedomofpress/securedrop-client/pull/2332 to be merged in order to do final testing prior to merge. But otherwise fine to have its review done.
Fixes #2156.
Setup:
Test prior to rebasing on top of https://github.com/freedomofpress/securedrop-client/pull/2332 (assuming merged and on main):
Test after rebasing on top of https://github.com/freedomofpress/securedrop-client/pull/2332:
- repeat https://github.com/freedomofpress/securedrop-client/pull/2332's test plan
If these changes modify code paths involving cryptography, the opening of files in VMs or network (via the RPC service) traffic, Qubes testing in the staging environment is required. For fine tuning of the graphical user interface, testing in any environment in Qubes is …
=> Replace XPP with GTK print dialog

changelog.md, debian/changelog
Ready for Review
Changelog for 0.15.0
**TODO**:
=> 0.15.0 Changelog

.github/workflows/cargo-vet.yml, .github/workflows/ci.yml, .github/workflows/security.yml, .github/workflows/test.yml, rust-toolchain.toml, scripts/Dockerfile
Fixes #2449
Also updates rust-init version to 1.28.2
=> Update Rust toolchain 1.84.1 -> 1.87.0 and rust-init to 1.28.2

app/.gitignore, app/package.json, app/run.sh, app/src/frontend/App.tsx, app/src/frontend/preload.d.ts, app/src/main.ts, app/src/preload.ts, app/src/proxy.test.ts, app/src/proxy.ts, app/src/utils.ts, app/src/vite-env.d.ts, app/tsconfig.json
Fixes #2504 
Implements `proxy` to send requests to `sd-proxy`, with the proxy command + proxy origin configured via environment.
[self-contained]: https://github.com/freedomofpress/securedrop-client#generating-and-running-dat …
=> [app] handle requests to sd-proxy

export/securedrop_export/print/service.py
When printing plaintext files or printing the transcript, the messages would get wrapped truncated mid-word instead of wrapping words around. By sending it via libreoffice, this kind of formatting is automatically handled.
Fixes #2442. It also has the side-effect of increasing the page margins. My assumption is that it's fine and not worth fiddling on libreoffice via parameters.
| **Before**| **After** |
|---|---|
| ![Screenshot 2025-06-30 at 13-15-14 before pdf](https://github.com/user-attachments/assets/121b9c1a-3e2b-46d8-987b-86667f6dd2bc) | ![Screenshot 2025-06-30 at 13-15-36 after pdf](https://github.com/user-attachments/assets/7b305f16-eb46-482c-88ec-407cbccbb9ca)
=> Plaintext to print via libreoffice (fix wrapping)

.github/dependabot.yml
Have dependabot update our npm dependencies on a weekly basis. (Once we get farther along we could have it update electron packages on a faster schedule if we find the need.)
It should submit two PRs, one for production dependencies and another for development ones.
=> Configure weekly dependabot updates for app/

.github/workflows/app-integration.yaml, app/.testcontainers.properties, app/integration_tests/proxy.test.ts, app/integration_tests/setup.ts, app/package.json, app/pnpm-lock.yaml, app/tsconfig.web.json, app/vitest.config.ts
Work in progress
Unit tests live in `tests/` and integration tests live in `integration_tests`. There are now two different vitest projects configured for each, allowing different setup + cleanup, so we can run our suite of unit tests + integration tests separately.
Adds integration tests that (1) build + run the `sd-proxy` binary, and (2) pull and run a local httpbin podman container using [testcontainers](https://testcontainers.com/).
Also adds the integration test suite to our GH actions CI pipeline.
Running `pnpm integration-test` runs integration tests for proxy against local httpbin server
=> [integration_tests] add sd-proxy integration tests

app/pnpm-workspace.yaml
This is an attempt to fix #2535.  This `packages` value (i.e., the `app/` directory) is the [default](https://pnpm.io/pnpm-workspace_yaml) implicit for `app/pnpm-workspace.yaml`, but [Dependabot may need it to be explicit](https://github.com/freedomofpress/securedrop-client/actions/runs/16454068357/job/46506483513#step:3:329).
Visual review after CI.  The real test (i.e., whether this closes #2535) will be whether Dependabot can suggest updates ([e.g.](https://github.com/freedomofpress/securedrop-client/security/dependabot/171)) once this is on `main`.
=> build(pnpm): make `packages` explicit

client/README.md, proxy/README.md
Resolves #2429
Resolves #1689
This includes:
- Pointer to the `app` rewrite
- Pointers to the new `try-client-pr.py` script
- Updates to links that pointed to archived repos due to the monorepo transition
- Updates to links to developer documentation, which has moved to https://developers.securedrop.org/ (these all redirected, but it's nicer to point to the canonical URLs)
- Updates to project status where appropriate
- Consolidation of developer docs that were largely duplicative
- Removal of sections from the proxy README that are no longer applicable to the Rust implementation
=> Clean up client and proxy README files

app/src/renderer/views/SignIn.tsx
I noticed that when I typed anything into the username field of SignInView, a circular reference warning appeared:
This fixes it. Now instead of trying to clear the errors every time any values change, it only clears the errors if there are errors.
=> Fix circular reference warning

app/integration_tests/proxy.test.ts, app/src/main/proxy.test.ts, app/src/main/proxy.ts, app/src/main/sync.test.ts, app/src/main/sync.ts, app/src/renderer/views/SignIn.tsx, app/src/types.ts
Adding the generic type annotation to `ProxyResponse` is proving to be more cumbersome than useful. Revert back to having `ProxyJSONResponse` just return a `JSONObject` in its data, and cast as needed in the caller.
=> [app] remove generic type from ProxyResponse

app/package.json
Fixes #2571.
This renames the productName from `SecureDrop Admin` to `SecureDrop`, which changes the Electron app data folder from `~/.config/SecureDrop App/` to `~/.config/SecureDrop/`.
You can now delete `~/.config/SecureDrop App/`, and the next time you run the SD app it write data to `~/.config/SecureDrop/`, which is where the sqlite3 database is stored.
The title of the app in the title bar is still "SecureDrop App", because that's in the `<title>` tag in `app/src/renderer/index.html`.
=> Rename the app to SecureDrop, to avoid spaces in the config path

app/src/main/index.ts, app/src/preload/index.ts, app/src/renderer/i18n.ts, app/src/renderer/test-component-setup.tsx, app/tsconfig.web.json
Note: this depends on #2592.
Allows usage of the `LANG` environment variable.
Split from #2559.
[self-contained]: https://github.com/freedomofpress/securedrop-client/tree/main/client#generating-and-running-database-migrations
=> Fetch system language from backend

app/src/renderer/components/Avatar.test.tsx, app/src/renderer/components/Avatar.tsx, app/src/renderer/components/LoadingIndicator.test.tsx, app/src/renderer/components/LoadingIndicator.tsx, app/src/renderer/test-component-setup.tsx, app/src/renderer/views/Inbox/MainContent.tsx, app/src/renderer/views/Inbox/MainContent/Conversation.test.tsx, app/src/renderer/views/Inbox/MainContent/Conversation.tsx, app/src/renderer/views/Inbox/Sidebar/SourceList.tsx, app/src/renderer/views/Inbox/Sidebar/SourceList/Source.test.tsx, app/src/renderer/views/Inbox/Sidebar/SourceList/Source.tsx
This prevents them from needing to be re-rendered if the input props don't change. Together this is sufficient to make e.g. starring a source not require re-rendering all the unaffected sources. It does not yet fix the overall performance of loading new source rows.
In general:
* `memo`: applied to entire components
* `useMemo`: applied to calculated values
* `useCallback`: applied to functions
The more complicated places that these wrap are good candidates for splitting out into separate components, which'll also make profiling them easier. But I'll defer that for another PR.
Much of this was driven by Claude Code.
Refs #2616.
Here's a video recording of me stepping through the profiler part (with audio).
https://github.com/user-attachments/assets/191dc3a5-50a0-4140-9165-79987e2e4ec9 …
=> Memoize most React components

app/src/renderer/views/Inbox/Sidebar/SourceList.tsx
The primary function of the list is source selection; all the text rendered there is selectable in other ways, and the preview text is truncated anyway.
Fixes #2626.
[self-contained]: https://github.com/freedomofpress/securedrop-client/tree/main/client#generating-and-running-database-migrations
=> Disallow selection of text in SourceList

app/package.json, app/pnpm-lock.yaml, app/src/renderer/views/Inbox/Sidebar/SourceList.test.tsx, app/src/renderer/views/Inbox/Sidebar/SourceList.tsx, app/src/renderer/views/Inbox/Sidebar/SourceList/Source.test.tsx, app/src/renderer/views/Inbox/Sidebar/SourceList/Source.tsx
This PR fixes the performance issues which have been plaguing the app so far by using [virtual scrolling](https://medium.com/@swatikpl44/virtual-scrolling-in-react-6028f700da6b). It adds the [react-window](https://www.npmjs.com/package/react-window) dependency to simplify the implementation of it. We may want to also implement this for conversation views, though those may be more complex because each item might have different heights.
Basically, rather than rendering all 1000 sources to the DOM (including all of their child components), this only renders the sources that are visible at the time based on the scrollbar position. So instead of rendering 1000 sources, it renders maybe 15 or so, depending on the window height. And as you scroll, it deletes the ones that are out of view and …
=> Implement virtual scrolling

app/package.json, app/pnpm-lock.yaml, app/src/renderer/views/Inbox/Sidebar/SourceList.tsx
Set the required `width` property to 100% to keep the existing width.
[self-contained]: https://github.com/freedomofpress/securedrop-client/tree/main/client#generating-and-running-database-migrations
=> Add missing @types/react-window

app/electron.vite.config.ts, app/integration_tests/proxy.test.ts, app/src/main/database/index.ts, app/src/main/proxy.test.ts, app/src/main/proxy.ts, app/src/main/sync.test.ts, app/src/renderer/views/Inbox/MainContent.test.tsx, app/src/types.ts, app/tsconfig.node.json, app/tsconfig.web.json
This would've caught the missing react-window types and in general is a bit stricter on typing and closer to our strict mypy config.
[self-contained]: https://github.com/freedomofpress/securedrop-client/tree/main/client#generating-and-running-database-migrations
=> Set noImplicitAny in tsconfig

app/src/main/sync.test.ts, app/src/renderer/features/conversation/conversationSlice.test.ts, app/src/renderer/features/journalists/journalistsSlice.test.ts, app/src/renderer/features/sources/sourcesSlice.test.ts, app/src/renderer/features/sources/sourcesSlice.ts, app/src/renderer/features/sync/syncSlice.test.ts, app/src/renderer/features/sync/syncSlice.ts, app/src/renderer/store.ts, app/src/renderer/views/Inbox/Sidebar/Account.tsx, app/src/renderer/views/Inbox/Sidebar/SourceList.test.tsx
I spoke with @vickiniu and we decided that it made sense to split the sync functionality into its own Redux slice. Before, in the `sourcesSlice` slice, `syncSources` triggered the metadata sync. But this synced sources, journalists, and the active conversation, if there was one.
This PR creates a new `syncSlice` and moves the `syncSources` logic into it, but renames it `syncMetadata`.
All of the functionality should remain the same.
=> Split sync functionality into its own Redux slice

.github/workflows/nightlies.yml
See warning at e.g. https://github.com/freedomofpress/securedrop-client/actions/runs/18055974620/job/51385958151.
=> Fix typo in nightlies CI config

app/src/main/fetch/bufferedWriter.test.ts, app/src/main/fetch/bufferedWriter.ts, app/src/main/fetch/queue.test.ts, app/src/main/fetch/queue.ts
Completes decryption implementation in fetch worker, decrypting file submissions as well.
Some slight refactoring of the logic just to clean up the three decryption pathways:
- [message/reply] Decrypting from in-memory buffer
- [message/reply] Retrying decryption from ciphertext saved to disk
- [file] Decrypting from download encrypted file
Also modifies the `BufferedWriter` implementation to always return a buffer and not throw errors to simplify handling. I think we don't really need to worry about the case where we `getBuffer()` and then write data afterwards, but open to having more error handling there if we want to keep that guarantee. …
=> [app] decrypt file submissions in fetch worker

client/README.md
Somewhere along the way, the `staging/production environment` subgraph stopped inheriting the graph-level `TD` attribute.  An explicit `direction TB` directive aligns the subgraphs so that they're easier to compare.
=> docs: vertical-align environment diagrams for easier visual comparison
